In [25]:
import requests

url = 'http://openapi.seoul.go.kr:8088/(인증키)/json/SebcCollegeInfoKor/1/100/'

response = requests.get(url)
print(response.content)

b'{"SebcCollegeInfoKor":{"list_total_count":64,"RESULT":{"CODE":"INFO-000","MESSAGE":"\xec\xa0\x95\xec\x83\x81 \xec\xb2\x98\xeb\xa6\xac\xeb\x90\x98\xec\x97\x88\xec\x8a\xb5\xeb\x8b\x88\xeb\x8b\xa4"},"row":[{"MAIN_KEY":"BE_LiST23-0034","YEAR":"2013","CATE1_NAME":"\xec\x9d\xbc\xeb\xb0\x98\xeb\x8c\x80\xed\x95\x99","NAME_KOR":"\xec\x84\x9c\xec\x9a\xb8\xec\x8b\x9c\xeb\xa6\xbd\xeb\x8c\x80\xed\x95\x99\xea\xb5\x90","BRANCH":"\xeb\xb3\xb8\xea\xb5\x90","STATE":"\xea\xb8\xb0\xec\xa1\xb4","TYPE":"\xea\xb3\xb5\xeb\xa6\xbd","POSTCODE":"","ADD_KOR":"\xec\x84\x9c\xec\x9a\xb8 \xeb\x8f\x99\xeb\x8c\x80\xeb\xac\xb8\xea\xb5\xac \xec\x84\x9c\xec\x9a\xb8\xec\x8b\x9c\xeb\xa6\xbd\xeb\x8c\x80\xeb\xa1\x9c 163 (\xec\xa0\x84\xeb\x86\x8d\xeb\x8f\x99 90\xeb\xb2\x88\xec\xa7\x80) ","ADD_KOR_ROAD":"","H_KOR_CITY":"\xec\x84\x9c\xec\x9a\xb8\xed\x8a\xb9\xeb\xb3\x84\xec\x8b\x9c","H_KOR_GU":"\xeb\x8f\x99\xeb\x8c\x80\xeb\xac\xb8\xea\xb5\xac","H_KOR_DONG":"\xed\x9c\x98\xea\xb2\xbd2\xeb\x8f\x99","TEL":"02-6490-6114","FAX":"02-2210-5576","HP":"http://www.uos.ac.kr"},{"MAIN_KEY":"BE_LiST23-0035","YEAR":"2013","CATE1_NAME":"\xec\xa0\x84\xeb\xac\xb8\xeb\x8c\x80\xed\x95\x99(3\xeb\x85\x84\xec\xa0\x9c)","NAME_KOR":"\xec\x84\x9c\xec\x9a\xb8\xec\x97\xac\xec\x9e\x90\xea\xb0\x84\xed\x98\xb8\xeb\x8c\x80\xed\x95\x99\xea\xb5\x90","BRANCH":"\xeb\xb3\xb8\xea\xb5\x90","STATE":"\xea\xb8\xb0\xec\xa1\xb4","TYPE":"\xec\x82\xac\xeb\xa6\xbd","POSTCODE":"","ADD_KOR":"\xec\x84\x9c\xec\x9a\xb8 \xec\x84\x9c\xeb\x8c\x80\xeb\xac\xb8\xea\xb5\xac \xed\x99\x8d\xec\xa0\x9c3\xeb\x8f\x99 \xec\x84\x9c\xec\x9a\xb8\xec\x97\xac\xec\x9e\x90\xea\xb0\x84\xed\x98\xb8\xeb\x8c\x80\xed\x95\x99","ADD_KOR_ROAD":"","H_KOR_CITY":"\xec\x84\x9c\xec\x9a\xb8\xed\x8a\xb9\xeb\xb3\x84\xec\x8b\x9c","H_KOR_GU":"\xec\x84\x9c\xeb\x8c\x80\xeb\xac\xb8\xea\xb5\xac","H_KOR_DONG":"\xed\x99\x8d\xec\xa0\x9c2\xeb\x8f\x99","TEL":"02-2287-1700","FAX":"02-395-8018","HP":"http://www.snjc.ac.kr"},{"MAIN_KEY":"BE_LiST23-0036","YEAR":"2013","CATE1_NAME":"\xec\x9d\xbc\xeb\xb0\x98\xeb\x8c\x80\xed\x95\x99","NAME_KOR":"\xec\x84\x9c\xec\x9a\xb8\xec\x97\xac\xec\x9e\x90\xeb\x8c\x80\xed\x95\x99\xea\xb5\x90","BRANCH":"\xeb\xb3\xb8\xea\xb5\x90","STATE":"\xea\xb8\xb0\xec\xa1\xb4","TYPE":"\xec\x82\xac\xeb\xa6\xbd","POSTCODE":"","ADD_KOR":"\xec\x84\x9c\xec\x9a\xb8\xed\x8a\xb9\xeb\xb3\x84\xec\x8b\x9c \xeb\x85\xb8\xec\x9b\x90\xea\xb5\xac \xed\x99\x94\xeb\x9e\x91\xeb\xa1\x9c 621 \xec\x84\x9c\xec\x9a\xb8\xec\x97\xac\xec\x9e\x90\xeb\x8c\x80\xed\x95\x99\xea\xb5\x90","ADD_KOR_ROAD":"","H_KOR_CITY":"\xec\x84\x9c\xec\x9a\xb8\xed\x8a\xb9\xeb\xb3\x84\xec\x8b\x9c","H_KOR_GU":"\xeb\x85\xb8\xec\x9b\x90\xea\xb5\xac","H_KOR_DONG":"\xea\xb3\xb5\xeb\xa6\x892\xeb\x8f\x99","TEL":"02-970-5114","FAX":"02-978-7931","HP":"http://www.swu.ac.kr"},{"MAIN_KEY":"BE_LiST23-0037","YEAR":"2013","CATE1_NAME":"\xec\xa0\x84\xeb\xac\xb8\xeb\x8c\x80\xed\x95\x99(2\xeb\x85\x84\xec\xa0\x9c)","NAME_KOR":"\xec\x84\x9c\xec\x9d\xbc\xeb\x8c\x80\xed\x95\x99\xea\xb5\x90","BRANCH":"\xeb\xb3\xb8\xea\xb5\x90","STATE":"\xed\x95\x99\xea\xb5\x90\xeb\xaa\x85 \xeb\xb3\x80\xea\xb2\xbd","TYPE":"\xec\x82\xac\xeb\xa6\xbd","POSTCODE":"","ADD_KOR":"\xec\x84\x9c\xec\x9a\xb8 \xec\xa4\x91\xeb\x9e\x91\xea\xb5\xac \xec\x84\x9c\xec\x9d\xbc\xeb\x8c\x80\xed\x95\x99\xea\xb8\xb8 22(\xeb\xa9\xb4\xeb\xaa\xa9\xeb\x8f\x99 49-3) \xec\x84\x9c\xec\x9d\xbc\xeb\x8c\x80\xed\x95\x99\xea\xb5\x90","ADD_KOR_ROAD":"","H_KOR_CITY":"\xec\x84\x9c\xec\x9a\xb8\xed\x8a\xb9\xeb\xb3\x84\xec\x8b\x9c","H_KOR_GU":"\xec\xa4\x91\xeb\x9e\x91\xea\xb5\xac","H_KOR_DONG":"\xeb\xa9\xb4\xeb\xaa\xa9\xec\xa0\x9c3.8\xeb\x8f\x99","TEL":"02-490-7300","FAX":"02-493-2576","HP":"http://www.seoil.ac.kr"},{"MAIN_KEY":"BE_LiST23-0038","YEAR":"2013","CATE1_NAME":"\xec\x9d\xbc\xeb\xb0\x98\xeb\x8c\x80\xed\x95\x99","NAME_KOR":"\xec\x84\xb1\xea\xb3\xb5\xed\x9a\x8c\xeb\x8c\x80\xed\x95\x99\xea\xb5\x90","BRANCH":"\xeb\xb3\xb8\xea\xb5\x90","STATE":"\xea\xb8\xb0\xec\xa1\xb4","TYPE":"\xec\x82\xac\xeb\xa6\xbd","POSTCODE":"","ADD_KOR":"\xec\x84\x9c\xec\x9a\xb8 \xea\xb5\xac\xeb\xa1\x9c\xea\xb5\xac \xed\x95\xad\xeb\x8f\x99 \xec\x84\xb1\xea\xb3\xb5\xed\x9a\x8c\xeb\x8c\x80\xed\x95\x99\xea\xb5\x90","ADD_KOR_ROAD":"","H_KOR_CITY":"\xec\x84\x9c\xec\x9a\xb8\xed\x8a\xb9\xeb\xb3\x84\xec\x8b\x9c","H_KOR_GU":"\xea\xb5\xac\xeb\xa1\x9c\xea\xb5\xac","H_KOR_DONG":"\xec\x98\xa4\xeb\xa5\x982\xeb\x8f\x99","TEL":"02-2610-4142","FAX":"02-2610-4248","HP":"http://www.skhu.ac.kr"},{"MAIN_KEY":"BE_LiST23-0039","YEAR":"2013","CATE1_NAME":"\xec\x9d\xbc\xeb\xb0\x98\xeb\x8c\x80\xed\x95\x99","NAME_KOR":"\xec\x84\xb1\xea\xb7\xa0\xea\xb4\x80\xeb\x8c\x80\xed\x95\x99\xea\xb5\x90","BRANCH":"\xeb\xb3\xb8\xea\xb5\x90","STATE":"\xea\xb8\xb0\xec\xa1\xb4","TYPE":"\xec\x82\xac\xeb\xa6\xbd","POSTCODE":"","ADD_KOR":"\xec\x84\x9c\xec\x9a\xb8 \xec\xa2\x85\xeb\xa1\x9c\xea\xb5\xac \xeb\xaa\x85\xeb\xa5\x9c\xeb\x8f\x993\xea\xb0\x80 \xec\x84\xb1\xea\xb7\xa0\xea\xb4\x80\xeb\x8c\x80\xed\x95\x99\xea\xb5\x90","ADD_KOR_ROAD":"","H_KOR_CITY":"\xec\x84\x9c\xec\x9a\xb8\xed\x8a\xb9\xeb\xb3\x84\xec\x8b\x9c","H_KOR_GU":"\xec\xa2\x85\xeb\xa1\x9c\xea\xb5\xac","H_KOR_DONG":"\xec\xa2\x85\xeb\xa1\x9c1.2.3.4\xea\xb0\x80\xeb\x8f\x99","TEL":"02-760-0114","FAX":"","HP":"http://www.skku.edu"},{"MAIN_KEY":"BE_LiST23-0040","YEAR":"2013","CATE1_NAME":"\xec\x9d\xbc\xeb\xb0\x98\xeb\x8c\x80\xed\x95\x99","NAME_KOR":"\xec\x84\xb1\xec\x8b\xa0\xec\x97\xac\xec\x9e\x90\xeb\x8c\x80\xed\x95\x99\xea\xb5\x90","BRANCH":"\xeb\xb3\xb8\xea\xb5\x90","STATE":"\xea\xb8\xb0\xec\xa1\xb4","TYPE":"\xec\x82\xac\xeb\xa6\xbd","POSTCODE":"","ADD_KOR":"\xec\x84\x9c\xec\x9a\xb8 \xec\x84\xb1\xeb\xb6\x81\xea\xb5\xac \xeb\x8f\x99\xec\x84\xa0\xeb\x8f\x993\xea\xb0\x80 \xec\x84\xb1\xec\x8b\xa0\xec\x97\xac\xec\x9e\x90\xeb\x8c\x80\xed\x95\x99\xea\xb5\x90","ADD_KOR_ROAD":"","H_KOR_CITY":"\xec\x84\x9c\xec\x9a\xb8\xed\x8a\xb9\xeb\xb3\x84\xec\x8b\x9c","H_KOR_GU":"\xec\x84\xb1\xeb\xb6\x81\xea\xb5\xac","H_KOR_DONG":"\xeb\x8f\x99\xec\x84\xa0\xeb\x8f\x99","TEL":"02-920-7114","FAX":"02-920-2018","HP":"http://www.sungshin.ac.kr"},{"MAIN_KEY":"BE_LiST23-0041","YEAR":"2013","CATE1_NAME":"\xec\x9d\xbc\xeb\xb0\x98\xeb\x8c\x80\xed\x95\x99","NAME_KOR":"\xec\x84\xb8\xec\xa2\x85\xeb\x8c\x80\xed\x95\x99\xea\xb5\x90","BRANCH":"\xeb\xb3\xb8\xea\xb5\x90","STATE":"\xea\xb8\xb0\xec\xa1\xb4","TYPE":"\xec\x82\xac\xeb\xa6\xbd","POSTCODE":"","ADD_KOR":"\xec\x84\x9c\xec\x9a\xb8 \xea\xb4\x91\xec\xa7\x84\xea\xb5\xac \xea\xb5\xb0\xec\x9e\x90\xeb\x8f\x99 \xec\x84\xb8\xec\xa2\x85\xeb\x8c\x80\xed\x95\x99\xea\xb5\x90","ADD_KOR_ROAD":"","H_KOR_CITY":"\xec\x84\x9c\xec\x9a\xb8\xed\x8a\xb9\xeb\xb3\x84\xec\x8b\x9c","H_KOR_GU":"\xea\xb4\x91\xec\xa7\x84\xea\xb5\xac","H_KOR_DONG":"\xea\xb5\xb0\xec\x9e\x90\xeb\x8f\x99","TEL":"02-3408-3114","FAX":"02-3408-3906","HP":"http://www.sejong.ac.kr"},{"MAIN_KEY":"BE_LiST23-0042","YEAR":"2013","CATE1_NAME":"\xec\x9d\xbc\xeb\xb0\x98\xeb\x8c\x80\xed\x95\x99","NAME_KOR":"\xec\x88\x99\xeb\xaa\x85\xec\x97\xac\xec\x9e\x90\xeb\x8c\x80\xed\x95\x99\xea\xb5\x90","BRANCH":"\xeb\xb3\xb8\xea\xb5\x90","STATE":"\xea\xb8\xb0\xec\xa1\xb4","TYPE":"\xec\x82\xac\xeb\xa6\xbd","POSTCODE":"","ADD_KOR":"\xec\x84\x9c\xec\x9a\xb8 \xec\x9a\xa9\xec\x82\xb0\xea\xb5\xac \xec\xb2\xad\xed\x8c\x8c\xeb\xa1\x9c47\xea\xb8\xb8 100 \xec\x88\x99\xeb\xaa\x85\xec\x97\xac\xec\x9e\x90\xeb\x8c\x80\xed\x95\x99\xea\xb5\x90","ADD_KOR_ROAD":"","H_KOR_CITY":"\xec\x84\x9c\xec\x9a\xb8\xed\x8a\xb9\xeb\xb3\x84\xec\x8b\x9c","H_KOR_GU":"\xec\x9a\xa9\xec\x82\xb0\xea\xb5\xac","H_KOR_DONG":"\xec\xb2\xad\xed\x8c\x8c\xeb\x8f\x99","TEL":"","FAX":"","HP":"http://www.sookmyung.ac.kr/"},{"MAIN_KEY":"BE_LiST23-0043","YEAR":"2013","CATE1_NAME":"\xec\x9d\xbc\xeb\xb0\x98\xeb\x8c\x80\xed\x95\x99","NAME_KOR":"\xec\x88\xad\xec\x8b\xa4\xeb\x8c\x80\xed\x95\x99\xea\xb5\x90","BRANCH":"\xeb\xb3\xb8\xea\xb5\x90","STATE":"\xea\xb8\xb0\xec\xa1\xb4","TYPE":"\xec\x82\xac\xeb\xa6\xbd","POSTCODE":"","ADD_KOR":"\xec\x84\x9c\xec\x9a\xb8 \xeb\x8f\x99\xec\x9e\x91\xea\xb5\xac \xec\x83\x81\xeb\x8f\x84\xeb\x8f\x99 511 \xec\x88\xad\xec\x8b\xa4\xeb\x8c\x80\xed\x95\x99\xea\xb5\x90","ADD_KOR_ROAD":"","H_KOR_CITY":"\xec\x84\x9c\xec\x9a\xb8\xed\x8a\xb9\xeb\xb3\x84\xec\x8b\x9c","H_KOR_GU":"\xeb\x8f\x99\xec\x9e\x91\xea\xb5\xac","H_KOR_DONG":"\xec\x83\x81\xeb\x8f\x841\xeb\x8f\x99","TEL":"02-820-0114","FAX":"","HP":"http://www.ssu.ac.kr"},{"MAIN_KEY":"BE_LiST23-0044","YEAR":"2013","CATE1_NAME":"\xec\xa0\x84\xeb\xac\xb8\xeb\x8c\x80\xed\x95\x99(2\xeb\x85\x84\xec\xa0\x9c)","NAME_KOR":"\xec\x88\xad\xec\x9d\x98\xec\x97\xac\xec\x9e\x90\xeb\x8c\x80\xed\x95\x99\xea\xb5\x90","BRANCH":"\xeb\xb3\xb8\xea\xb5\x90","STATE":"\xea\xb8\xb0\xec\xa1\xb4","TYPE":"\xec\x82\xac\xeb\xa6\xbd","POSTCODE":"","ADD_KOR":"\xec\x84\x9c\xec\x9a\xb8\xed\x8a\xb9\xeb\xb3\x84\xec\x8b\x9c \xec\xa4\x91\xea\xb5\xac \xec\x86\x8c\xed\x8c\x8c\xeb\xa1\x9c2\xea\xb8\xb8 10(\xec\x98\x88\xec\x9e\xa5\xeb\x8f\x99)","ADD_KOR_ROAD":"","H_KOR_CITY":"\xec\x84\x9c\xec\x9a\xb8\xed\x8a\xb9\xeb\xb3\x84\xec\x8b\x9c","H_KOR_GU":"\xec\xa4\x91\xea\xb5\xac","H_KOR_DONG":"\xed\x95\x84\xeb\x8f\x99","TEL":"02-3708-9000","FAX":"02-773-2625","HP":"http://www.sewc.ac.kr"},{"MAIN_KEY":"BE_LiST23-0045","YEAR":"2013","CATE1_NAME":"\xec\x9d\xbc\xeb\xb0\x98\xeb\x8c\x80\xed\x95\x99","NAME_KOR":"\xec\x97\xb0\xec\x84\xb8\xeb\x8c\x80\xed\x95\x99\xea\xb5\x90","BRANCH":"\xeb\xb3\xb8\xea\xb5\x90","STATE":"\xea\xb8\xb0\xec\xa1\xb4","TYPE":"\xec\x82\xac\xeb\xa6\xbd","POSTCODE":"","ADD_KOR":"\xec\x84\x9c\xec\x9a\xb8 \xec\x84\x9c\xeb\x8c\x80\xeb\xac\xb8\xea\xb5\xac \xec\x8b\xa0\xec\xb4\x8c\xeb\x8f\x99 \xec\x97\xb0\xec\x84\xb8\xeb\x8c\x80\xed\x95\x99\xea\xb5\x90","ADD_KOR_ROAD":"","H_KOR_CITY":"\xec\x84\x9c\xec\x9a\xb8\xed\x8a\xb9\xeb\xb3\x84\xec\x8b\x9c","H_KOR_GU":"\xec\x84\x9c\xeb\x8c\x80\xeb\xac\xb8\xea\xb5\xac","H_KOR_DONG":"\xec\x8b\xa0\xec\xb4\x8c\xeb\x8f\x99","TEL":"02-2123-2114","FAX":"02-392-0618","HP":"http://www.yonsei.ac.kr"},{"MAIN_KEY":"BE_LiST23-0046","YEAR":"2013","CATE1_NAME":"\xec\x9d\xbc\xeb\xb0\x98\xeb\x8c\x80\xed\x95\x99","NAME_KOR":"\xec\x9d\xb4\xed\x99\x94\xec\x97\xac\xec\x9e\x90\xeb\x8c\x80\xed\x95\x99\xea\xb5\x90","BRANCH":"\xeb\xb3\xb8\xea\xb5\x90","STATE":"\xea\xb8\xb0\xec\xa1\xb4","TYPE":"\xec\x82\xac\xeb\xa6\xbd","POSTCODE":"","ADD_KOR":"\xec\x84\x9c\xec\x9a\xb8 \xec\x84\x9c\xeb\x8c\x80\xeb\xac\xb8\xea\xb5\xac \xeb\x8c\x80\xed\x98\x84\xeb\x8f\x99 11-1 \xec\x9d\xb4\xed\x99\x94\xec\x97\xac\xec\x9e\x90\xeb\x8c\x80\xed\x95\x99\xea\xb5\x90","ADD_KOR_ROAD":"","H_KOR_CITY":"\xec\x84\x9c\xec\x9a\xb8\xed\x8a\xb9\xeb\xb3\x84\xec\x8b\x9c","H_KOR_GU":"\xec\x84\x9c\xeb\x8c\x80\xeb\xac\xb8\xea\xb5\xac","H_KOR_DONG":"\xec\x8b\xa0\xec\xb4\x8c\xeb\x8f\x99","TEL":"02-3277-2114","FAX":"02-393-5903","HP":"http://www.ewha.ac.kr"},{"MAIN_KEY":"BE_LiST23-0047","YEAR":"2013","CATE1_NAME":"\xec\xa0\x84\xeb\xac\xb8\xeb\x8c\x80\xed\x95\x99(2\xeb\x85\x84\xec\xa0\x9c)","NAME_KOR":"\xec\x9d\xb8\xeb\x8d\x95\xeb\x8c\x80\xed\x95\x99\xea\xb5\x90","BRANCH":"\xeb\xb3\xb8\xea\xb5\x90","STATE":"\xea\xb8\xb0\xec\xa1\xb4","TYPE":"\xec\x82\xac\xeb\xa6\xbd","POSTCODE":"","ADD_KOR":"\xec\x84\x9c\xec\x9a\xb8 \xeb\x85\xb8\xec\x9b\x90\xea\xb5\xac \xec\xb4\x88\xec\x95\x88\xec\x82\xb0\xeb\xa1\x9c 12","ADD_KOR_ROAD":"","H_KOR_CITY":"\xec\x84\x9c\xec\x9a\xb8\xed\x8a\xb9\xeb\xb3\x84\xec\x8b\x9c","H_KOR_GU":"\xeb\x85\xb8\xec\x9b\x90\xea\xb5\xac","H_KOR_DONG":"\xec\x9b\x94\xea\xb3\x842\xeb\x8f\x99","TEL":"02-950-7000","FAX":"02-906-5340","HP":"http://www.induk.ac.kr"},{"MAIN_KEY":"BE_LiST23-0048","YEAR":"2013","CATE1_NAME":"\xec\x9d\xbc\xeb\xb0\x98\xeb\x8c\x80\xed\x95\x99","NAME_KOR":"\xec\x9e\xa5\xeb\xa1\x9c\xed\x9a\x8c\xec\x8b\xa0\xed\x95\x99\xeb\x8c\x80\xed\x95\x99\xea\xb5\x90","BRANCH":"\xeb\xb3\xb8\xea\xb5\x90","STATE":"\xea\xb8\xb0\xec\xa1\xb4","TYPE":"\xec\x82\xac\xeb\xa6\xbd","POSTCODE":"","ADD_KOR":"\xec\x84\x9c\xec\x9a\xb8 \xea\xb4\x91\xec\xa7\x84\xea\xb5\xac \xea\xb4\x91\xec\x9e\xa5\xeb\xa1\x9c 5\xea\xb8\xb8 25-1(\xea\xb4\x91\xec\x9e\xa5\xeb\x8f\x99) \xec\x9e\xa5\xeb\xa1\x9c\xed\x9a\x8c\xec\x8b\xa0\xed\x95\x99\xeb\x8c\x80\xed\x95\x99\xea\xb5\x90","ADD_KOR_ROAD":"","H_KOR_CITY":"\xec\x84\x9c\xec\x9a\xb8\xed\x8a\xb9\xeb\xb3\x84\xec\x8b\x9c","H_KOR_GU":"\xea\xb4\x91\xec\xa7\x84\xea\xb5\xac","H_KOR_DONG":"\xea\xb4\x91\xec\x9e\xa5\xeb\x8f\x99","TEL":"02-450-0700","FAX":"","HP":"http://www.pcts.ac.kr"},{"MAIN_KEY":"BE_LiST23-0049","YEAR":"2013","CATE1_NAME":"\xec\xa0\x84\xeb\xac\xb8\xeb\x8c\x80\xed\x95\x99(3\xeb\x85\x84\xec\xa0\x9c)","NAME_KOR":"\xec\xa0\x81\xec\x8b\xad\xec\x9e\x90\xea\xb0\x84\xed\x98\xb8\xeb\x8c\x80\xed\x95\x99","BRANCH":"\xeb\xb3\xb8\xea\xb5\x90","STATE":"\xed\x8f\x90\xea\xb5\x90","TYPE":"\xec\x82\xac\xeb\xa6\xbd","POSTCODE":"","ADD_KOR":"\xec\x84\x9c\xec\x9a\xb8 \xec\xa2\x85\xeb\xa1\x9c\xea\xb5\xac \xea\xb2\xbd\xea\xb5\x90\xec\x9e\xa5\xea\xb8\xb88","ADD_KOR_ROAD":"","H_KOR_CITY":"\xec\x84\x9c\xec\x9a\xb8\xed\x8a\xb9\xeb\xb3\x84\xec\x8b\x9c","H_KOR_GU":"\xec\xa2\x85\xeb\xa1\x9c\xea\xb5\xac","H_KOR_DONG":"\xea\xb5\x90\xeb\x82\xa8\xeb\x8f\x99","TEL":"02-3700-3600","FAX":"02-3700-3400","HP":"http://redcross.cau.ac.kr"},{"MAIN_KEY":"BE_LiST23-0050","YEAR":"2013","CATE1_NAME":"\xec\x9d\xbc\xeb\xb0\x98\xeb\x8c\x80\xed\x95\x99","NAME_KOR":"\xec\xa4\x91\xec\x95\x99\xeb\x8c\x80\xed\x95\x99\xea\xb5\x90 \xec\x84\x9c\xec\x9a\xb8\xec\xba\xa0\xed\x8d\xbc\xec\x8a\xa4","BRANCH":"\xeb\xb3\xb8\xea\xb5\x90","STATE":"\xea\xb8\xb0\xec\xa1\xb4","TYPE":"\xec\x82\xac\xeb\xa6\xbd","POSTCODE":"","ADD_KOR":"\xec\x84\x9c\xec\x9a\xb8 \xeb\x8f\x99\xec\x9e\x91\xea\xb5\xac \xed\x9d\x91\xec\x84\x9d\xeb\xa1\x9c 84","ADD_KOR_ROAD":"","H_KOR_CITY":"\xec\x84\x9c\xec\x9a\xb8\xed\x8a\xb9\xeb\xb3\x84\xec\x8b\x9c","H_KOR_GU":"\xeb\x8f\x99\xec\x9e\x91\xea\xb5\xac","H_KOR_DONG":"\xed\x9d\x91\xec\x84\x9d\xeb\x8f\x99","TEL":"02-820-5114","FAX":"","HP":"http://www.cau.ac.kr"},{"MAIN_KEY":"BE_LiST23-0051","YEAR":"2013","CATE1_NAME":"\xec\x9d\xbc\xeb\xb0\x98\xeb\x8c\x80\xed\x95\x99","NAME_KOR":"\xec\xb4\x9d\xec\x8b\xa0\xeb\x8c\x80\xed\x95\x99\xea\xb5\x90","BRANCH":"\xeb\xb3\xb8\xea\xb5\x90","STATE":"\xea\xb8\xb0\xec\xa1\xb4","TYPE":"\xec\x82\xac\xeb\xa6\xbd","POSTCODE":"","ADD_KOR":"\xec\x84\x9c\xec\x9a\xb8 \xeb\x8f\x99\xec\x9e\x91\xea\xb5\xac \xec\x82\xac\xeb\x8b\xb9\xeb\x8f\x99 \xec\x82\xb031-3","ADD_KOR_ROAD":"","H_KOR_CITY":"\xec\x84\x9c\xec\x9a\xb8\xed\x8a\xb9\xeb\xb3\x84\xec\x8b\x9c","H_KOR_GU":"\xeb\x8f\x99\xec\x9e\x91\xea\xb5\xac","H_KOR_DONG":"\xec\x82\xac\xeb\x8b\xb93\xeb\x8f\x99","TEL":"02-3479-0200","FAX":"02-536-2602","HP":"http://www.chongshin.ac.kr"},{"MAIN_KEY":"BE_LiST23-0052","YEAR":"2013","CATE1_NAME":"\xec\x9d\xbc\xeb\xb0\x98\xeb\x8c\x80\xed\x95\x99","NAME_KOR":"\xec\xb6\x94\xea\xb3\x84\xec\x98\x88\xec\x88\xa0\xeb\x8c\x80\xed\x95\x99\xea\xb5\x90","BRANCH":"\xeb\xb3\xb8\xea\xb5\x90","STATE":"\xea\xb8\xb0\xec\xa1\xb4","TYPE":"\xec\x82\xac\xeb\xa6\xbd","POSTCODE":"","ADD_KOR":"\xec\x84\x9c\xec\x9a\xb8 \xec\x84\x9c\xeb\x8c\x80\xeb\xac\xb8\xea\xb5\xac \xeb\xb6\x81\xec\x95\x84\xed\x98\x84\xeb\x8f\x99 190-1 \xec\xb6\x94\xea\xb3\x84\xec\x98\x88\xec\x88\xa0\xeb\x8c\x80\xed\x95\x99\xea\xb5\x90","ADD_KOR_ROAD":"","H_KOR_CITY":"\xec\x84\x9c\xec\x9a\xb8\xed\x8a\xb9\xeb\xb3\x84\xec\x8b\x9c","H_KOR_GU":"\xec\x84\x9c\xeb\x8c\x80\xeb\xac\xb8\xea\xb5\xac","H_KOR_DONG":"\xec\xb6\xa9\xed\x98\x84\xeb\x8f\x99","TEL":"02-362-5700","FAX":"02-392-1777","HP":"http://www.chugye.ac.kr"},{"MAIN_KEY":"BE_LiST23-0053","YEAR":"2013","CATE1_NAME":"\xeb\xb0\xa9\xec\x86\xa1\xed\x86\xb5\xec\x8b\xa0\xeb\x8c\x80\xed\x95\x99","NAME_KOR":"\xed\x95\x9c\xea\xb5\xad\xeb\xb0\xa9\xec\x86\xa1\xed\x86\xb5\xec\x8b\xa0\xeb\x8c\x80\xed\x95\x99\xea\xb5\x90","BRANCH":"\xeb\xb3\xb8\xea\xb5\x90","STATE":"\xea\xb8\xb0\xec\xa1\xb4","TYPE":"\xea\xb5\xad\xeb\xa6\xbd","POSTCODE":"","ADD_KOR":"\xec\x84\x9c\xec\x9a\xb8 \xec\xa2\x85\xeb\xa1\x9c\xea\xb5\xac \xeb\x8f\x99\xec\x88\xad\xeb\x8f\x99 \xed\x95\x9c\xea\xb5\xad\xeb\xb0\xa9\xec\x86\xa1\xed\x86\xb5\xec\x8b\xa0\xeb\x8c\x80\xed\x95\x99\xea\xb5\x90","ADD_KOR_ROAD":"","H_KOR_CITY":"\xec\x84\x9c\xec\x9a\xb8\xed\x8a\xb9\xeb\xb3\x84\xec\x8b\x9c","H_KOR_GU":"\xec\xa2\x85\xeb\xa1\x9c\xea\xb5\xac","H_KOR_DONG":"\xec\x9d\xb4\xed\x99\x94\xeb\x8f\x99","TEL":"02-3668-4114","FAX":"02-744-5882","HP":"http://www.knou.ac.kr"},{"MAIN_KEY":"BE_LiST23-0054","YEAR":"2013","CATE1_NAME":"\xec\x9d\xbc\xeb\xb0\x98\xeb\x8c\x80\xed\x95\x99","NAME_KOR":"\xed\x95\x9c\xea\xb5\xad\xec\x84\xb1\xec\x84\x9c\xeb\x8c\x80\xed\x95\x99\xea\xb5\x90","BRANCH":"\xeb\xb3\xb8\xea\xb5\x90","STATE":"\xea\xb8\xb0\xec\xa1\xb4","TYPE":"\xec\x82\xac\xeb\xa6\xbd","POSTCODE":"","ADD_KOR":"\xec\x84\x9c\xec\x9a\xb8 \xeb\x85\xb8\xec\x9b\x90\xea\xb5\xac \xec\x83\x81\xea\xb3\x847\xeb\x8f\x99 \xed\x95\x9c\xea\xb5\xad\xec\x84\xb1\xec\x84\x9c\xeb\x8c\x80\xed\x95\x99\xea\xb5\x90","ADD_KOR_ROAD":"","H_KOR_CITY":"\xec\x84\x9c\xec\x9a\xb8\xed\x8a\xb9\xeb\xb3\x84\xec\x8b\x9c","H_KOR_GU":"\xeb\x85\xb8\xec\x9b\x90\xea\xb5\xac","H_KOR_DONG":"\xec\x83\x81\xea\xb3\x846.7\xeb\x8f\x99","TEL":"02-950-5401","FAX":"02-950-5411","HP":"http://www.bible.ac.kr"},{"MAIN_KEY":"BE_LiST23-0055","YEAR":"2013","CATE1_NAME":"\xea\xb0\x81\xec\xa2\x85\xeb\x8c\x80\xed\x95\x99(\xeb\x8c\x80\xed\x95\x99)","NAME_KOR":"\xed\x95\x9c\xea\xb5\xad\xec\x98\x88\xec\x88\xa0\xec\xa2\x85\xed\x95\xa9\xed\x95\x99\xea\xb5\x90","BRANCH":"\xeb\xb3\xb8\xea\xb5\x90","STATE":"\xea\xb8\xb0\xec\xa1\xb4","TYPE":"\xed\x8a\xb9\xeb\xb3\x84\xeb\xb2\x95\xea\xb5\xad\xeb\xa6\xbd","POSTCODE":"","ADD_KOR":"\xec\x84\x9c\xec\x9a\xb8 \xec\x84\xb1\xeb\xb6\x81\xea\xb5\xac \xec\x84\x9d\xea\xb4\x80\xeb\x8f\x99 ","ADD_KOR_ROAD":"","H_KOR_CITY":"\xec\x84\x9c\xec\x9a\xb8\xed\x8a\xb9\xeb\xb3\x84\xec\x8b\x9c","H_KOR_GU":"\xec\x84\xb1\xeb\xb6\x81\xea\xb5\xac","H_KOR_DONG":"\xec\x84\x9d\xea\xb4\x80\xeb\x8f\x99","TEL":"","FAX":"","HP":""},{"MAIN_KEY":"BE_LiST23-0056","YEAR":"2013","CATE1_NAME":"\xec\x9d\xbc\xeb\xb0\x98\xeb\x8c\x80\xed\x95\x99","NAME_KOR":"\xed\x95\x9c\xea\xb5\xad\xec\x99\xb8\xea\xb5\xad\xec\x96\xb4\xeb\x8c\x80\xed\x95\x99\xea\xb5\x90","BRANCH":"\xeb\xb3\xb8\xea\xb5\x90","STATE":"\xea\xb8\xb0\xec\xa1\xb4","TYPE":"\xec\x82\xac\xeb\xa6\xbd","POSTCODE":"","ADD_KOR":"\xec\x84\x9c\xec\x9a\xb8 \xeb\x8f\x99\xeb\x8c\x80\xeb\xac\xb8\xea\xb5\xac \xec\x9d\xb4\xeb\xac\xb8\xeb\xa1\x9c 107","ADD_KOR_ROAD":"","H_KOR_CITY":"\xec\x84\x9c\xec\x9a\xb8\xed\x8a\xb9\xeb\xb3\x84\xec\x8b\x9c","H_KOR_GU":"\xeb\x8f\x99\xeb\x8c\x80\xeb\xac\xb8\xea\xb5\xac","H_KOR_DONG":"\xec\x9d\xb4\xeb\xac\xb81\xeb\x8f\x99","TEL":"02-2173-2114","FAX":"","HP":"http://www.hufs.ac.kr"},{"MAIN_KEY":"BE_LiST23-0057","YEAR":"2013","CATE1_NAME":"\xec\x9d\xbc\xeb\xb0\x98\xeb\x8c\x80\xed\x95\x99","NAME_KOR":"\xed\x95\x9c\xea\xb5\xad\xec\xb2\xb4\xec\x9c\xa1\xeb\x8c\x80\xed\x95\x99\xea\xb5\x90","BRANCH":"\xeb\xb3\xb8\xea\xb5\x90","STATE":"\xea\xb8\xb0\xec\xa1\xb4","TYPE":"\xea\xb5\xad\xeb\xa6\xbd","POSTCODE":"","ADD_KOR":"\xec\x84\x9c\xec\x9a\xb8 \xec\x86\xa1\xed\x8c\x8c\xea\xb5\xac \xec\x98\xa4\xeb\xa5\x9c\xeb\x8f\x99 \xed\x95\x9c\xea\xb5\xad\xec\xb2\xb4\xec\x9c\xa1\xeb\x8c\x80\xed\x95\x99\xea\xb5\x90","ADD_KOR_ROAD":"","H_KOR_CITY":"\xec\x84\x9c\xec\x9a\xb8\xed\x8a\xb9\xeb\xb3\x84\xec\x8b\x9c","H_KOR_GU":"\xec\x86\xa1\xed\x8c\x8c\xea\xb5\xac","H_KOR_DONG":"\xec\x98\xa4\xeb\xa5\x9c\xeb\x8f\x99","TEL":"02-410-6564","FAX":"02-410-6569","HP":"http://www.knsu.ac.kr/"},{"MAIN_KEY":"BE_LiST23-0058","YEAR":"2013","CATE1_NAME":"\xea\xb8\xb0\xeb\x8a\xa5\xeb\x8c\x80\xed\x95\x99","NAME_KOR":"\xed\x95\x9c\xea\xb5\xad\xed\x8f\xb4\xeb\xa6\xac\xed\x85\x8d I \xeb\x8c\x80\xed\x95\x99 \xec\x84\x9c\xec\x9a\xb8\xea\xb0\x95\xec\x84\x9c\xec\xba\xa0\xed\x8d\xbc\xec\x8a\xa4","BRANCH":"\xeb\xb3\xb8\xea\xb5\x90","STATE":"\xea\xb8\xb0\xec\xa1\xb4","TYPE":"\xec\x82\xac\xeb\xa6\xbd","POSTCODE":"","ADD_KOR":"\xec\x84\x9c\xec\x9a\xb8 \xea\xb0\x95\xec\x84\x9c\xea\xb5\xac \xed\x99\x94\xea\xb3\xa1\xeb\x8f\x99 \xec\x82\xb060-1","ADD_KOR_ROAD":"","H_KOR_CITY":"\xec\x84\x9c\xec\x9a\xb8\xed\x8a\xb9\xeb\xb3\x84\xec\x8b\x9c","H_KOR_GU":"\xea\xb0\x95\xec\x84\x9c\xea\xb5\xac","H_KOR_DONG":"\xec\x9a\xb0\xec\x9e\xa5\xec\x82\xb0\xeb\x8f\x99","TEL":"02-2186-5800","FAX":"02-2186-5819","HP":"http://kangseo.kopo.ac.kr"},{"MAIN_KEY":"BE_LiST23-0059","YEAR":"2013","CATE1_NAME":"\xea\xb8\xb0\xeb\x8a\xa5\xeb\x8c\x80\xed\x

In [26]:
data = response.json()

In [27]:
data

{'SebcCollegeInfoKor': {'list_total_count': 64,
  'RESULT': {'CODE': 'INFO-000', 'MESSAGE': '정상 처리되었습니다'},
  'row': [{'MAIN_KEY': 'BE_LiST23-0034',
    'YEAR': '2013',
    'CATE1_NAME': '일반대학',
    'NAME_KOR': '서울시립대학교',
    'BRANCH': '본교',
    'STATE': '기존',
    'TYPE': '공립',
    'POSTCODE': '',
    'ADD_KOR': '서울 동대문구 서울시립대로 163 (전농동 90번지) ',
    'ADD_KOR_ROAD': '',
    'H_KOR_CITY': '서울특별시',
    'H_KOR_GU': '동대문구',
    'H_KOR_DONG': '휘경2동',
    'TEL': '02-6490-6114',
    'FAX': '02-2210-5576',
    'HP': 'http://www.uos.ac.kr'},
   {'MAIN_KEY': 'BE_LiST23-0035',
    'YEAR': '2013',
    'CATE1_NAME': '전문대학(3년제)',
    'NAME_KOR': '서울여자간호대학교',
    'BRANCH': '본교',
    'STATE': '기존',
    'TYPE': '사립',
    'POSTCODE': '',
    'ADD_KOR': '서울 서대문구 홍제3동 서울여자간호대학',
    'ADD_KOR_ROAD': '',
    'H_KOR_CITY': '서울특별시',
    'H_KOR_GU': '서대문구',
    'H_KOR_DONG': '홍제2동',
    'TEL': '02-2287-1700',
    'FAX': '02-395-8018',
    'HP': 'http://www.snjc.ac.kr'},
   {'MAIN_KEY': 'BE_LiST23-0036',
    'YEAR': '2013',
    'CATE1_NAME': '일반대학',
    'NAME_KOR': '서울여자대학교',
    'BRANCH': '본교',
    'STATE': '기존',
    'TYPE': '사립',
    'POSTCODE': '',
    'ADD_KOR': '서울특별시 노원구 화랑로 621 서울여자대학교',
    'ADD_KOR_ROAD': '',
    'H_KOR_CITY': '서울특별시',
    'H_KOR_GU': '노원구',
    'H_KOR_DONG': '공릉2동',
    'TEL': '02-970-5114',
    'FAX': '02-978-7931',
    'HP': 'http://www.swu.ac.kr'},
   {'MAIN_KEY': 'BE_LiST23-0037',
    'YEAR': '2013',
    'CATE1_NAME': '전문대학(2년제)',
    'NAME_KOR': '서일대학교',
    'BRANCH': '본교',
    'STATE': '학교명 변경',
    'TYPE': '사립',
    'POSTCODE': '',
    'ADD_KOR': '서울 중랑구 서일대학길 22(면목동 49-3) 서일대학교',
    'ADD_KOR_ROAD': '',
    'H_KOR_CITY': '서울특별시',
    'H_KOR_GU': '중랑구',
    'H_KOR_DONG': '면목제3.8동',
    'TEL': '02-490-7300',
    'FAX': '02-493-2576',
    'HP': 'http://www.seoil.ac.kr'},
   {'MAIN_KEY': 'BE_LiST23-0038',
    'YEAR': '2013',
    'CATE1_NAME': '일반대학',
    'NAME_KOR': '성공회대학교',
    'BRANCH': '본교',
    'STATE': '기존',
    'TYPE': '사립',
    'POSTCODE': '',
    'ADD_KOR': '서울 구로구 항동 성공회대학교',
    'ADD_KOR_ROAD': '',
    'H_KOR_CITY': '서울특별시',
    'H_KOR_GU': '구로구',
    'H_KOR_DONG': '오류2동',
    'TEL': '02-2610-4142',
    'FAX': '02-2610-4248',
    'HP': 'http://www.skhu.ac.kr'},
   {'MAIN_KEY': 'BE_LiST23-0039',
    'YEAR': '2013',
    'CATE1_NAME': '일반대학',
    'NAME_KOR': '성균관대학교',
    'BRANCH': '본교',
    'STATE': '기존',
    'TYPE': '사립',
    'POSTCODE': '',
    'ADD_KOR': '서울 종로구 명륜동3가 성균관대학교',
    'ADD_KOR_ROAD': '',
    'H_KOR_CITY': '서울특별시',
    'H_KOR_GU': '종로구',
    'H_KOR_DONG': '종로1.2.3.4가동',
    'TEL': '02-760-0114',
    'FAX': '',
    'HP': 'http://www.skku.edu'},
   {'MAIN_KEY': 'BE_LiST23-0040',
    'YEAR': '2013',
    'CATE1_NAME': '일반대학',
    'NAME_KOR': '성신여자대학교',
    'BRANCH': '본교',
    'STATE': '기존',
    'TYPE': '사립',
    'POSTCODE': '',
    'ADD_KOR': '서울 성북구 동선동3가 성신여자대학교',
    'ADD_KOR_ROAD': '',
    'H_KOR_CITY': '서울특별시',
    'H_KOR_GU': '성북구',
    'H_KOR_DONG': '동선동',
    'TEL': '02-920-7114',
    'FAX': '02-920-2018',
    'HP': 'http://www.sungshin.ac.kr'},
   {'MAIN_KEY': 'BE_LiST23-0041',
    'YEAR': '2013',
    'CATE1_NAME': '일반대학',
    'NAME_KOR': '세종대학교',
    'BRANCH': '본교',
    'STATE': '기존',
    'TYPE': '사립',
    'POSTCODE': '',
    'ADD_KOR': '서울 광진구 군자동 세종대학교',
    'ADD_KOR_ROAD': '',
    'H_KOR_CITY': '서울특별시',
    'H_KOR_GU': '광진구',
    'H_KOR_DONG': '군자동',
    'TEL': '02-3408-3114',
    'FAX': '02-3408-3906',
    'HP': 'http://www.sejong.ac.kr'},
   {'MAIN_KEY': 'BE_LiST23-0042',
    'YEAR': '2013',
    'CATE1_NAME': '일반대학',
    'NAME_KOR': '숙명여자대학교',
    'BRANCH': '본교',
    'STATE': '기존',
    'TYPE': '사립',
    'POSTCODE': '',
    'ADD_KOR': '서울 용산구 청파로47길 100 숙명여자대학교',
    'ADD_KOR_ROAD': '',
    'H_KOR_CITY': '서울특별시',
    'H_KOR_GU': '용산구',
    'H_KOR_DONG': '청파동',
    'TEL': '',
    'FAX': '',
    'HP': 'http://www.sookmyung.ac.kr/'},
   {'MAIN_KEY': 'BE_LiST23-0043',
    'YEAR': '2013',
    'CATE1_NAME': '일반대학',
    'NAME_KOR': '숭실대학교',
    'BRANCH': '본교',
    'STATE': '기존',
    'TYPE': '사립',
    'POSTCODE': '',
    'ADD_KOR': '서울 동작구 상도동 511 숭실대학교',
    'ADD_KOR_ROAD': '',
    'H_KOR_CITY': '서울특별시',
    'H_KOR_GU': '동작구',
    'H_KOR_DONG': '상도1동',
    'TEL': '02-820-0114',
    'FAX': '',
    'HP': 'http://www.ssu.ac.kr'},
   {'MAIN_KEY': 'BE_LiST23-0044',
    'YEAR': '2013',
    'CATE1_NAME': '전문대학(2년제)',
    'NAME_KOR': '숭의여자대학교',
    'BRANCH': '본교',
    'STATE': '기존',
    'TYPE': '사립',
    'POSTCODE': '',
    'ADD_KOR': '서울특별시 중구 소파로2길 10(예장동)',
    'ADD_KOR_ROAD': '',
    'H_KOR_CITY': '서울특별시',
    'H_KOR_GU': '중구',
    'H_KOR_DONG': '필동',
    'TEL': '02-3708-9000',
    'FAX': '02-773-2625',
    'HP': 'http://www.sewc.ac.kr'},
   {'MAIN_KEY': 'BE_LiST23-0045',
    'YEAR': '2013',
    'CATE1_NAME': '일반대학',
    'NAME_KOR': '연세대학교',
    'BRANCH': '본교',
    'STATE': '기존',
    'TYPE': '사립',
    'POSTCODE': '',
    'ADD_KOR': '서울 서대문구 신촌동 연세대학교',
    'ADD_KOR_ROAD': '',
    'H_KOR_CITY': '서울특별시',
    'H_KOR_GU': '서대문구',
    'H_KOR_DONG': '신촌동',
    'TEL': '02-2123-2114',
    'FAX': '02-392-0618',
    'HP': 'http://www.yonsei.ac.kr'},
   {'MAIN_KEY': 'BE_LiST23-0046',
    'YEAR': '2013',
    'CATE1_NAME': '일반대학',
    'NAME_KOR': '이화여자대학교',
    'BRANCH': '본교',
    'STATE': '기존',
    'TYPE': '사립',
    'POSTCODE': '',
    'ADD_KOR': '서울 서대문구 대현동 11-1 이화여자대학교',
    'ADD_KOR_ROAD': '',
    'H_KOR_CITY': '서울특별시',
    'H_KOR_GU': '서대문구',
    'H_KOR_DONG': '신촌동',
    'TEL': '02-3277-2114',
    'FAX': '02-393-5903',
    'HP': 'http://www.ewha.ac.kr'},
   {'MAIN_KEY': 'BE_LiST23-0047',
    'YEAR': '2013',
    'CATE1_NAME': '전문대학(2년제)',
    'NAME_KOR': '인덕대학교',
    'BRANCH': '본교',
    'STATE': '기존',
    'TYPE': '사립',
    'POSTCODE': '',
    'ADD_KOR': '서울 노원구 초안산로 12',
    'ADD_KOR_ROAD': '',
    'H_KOR_CITY': '서울특별시',
    'H_KOR_GU': '노원구',
    'H_KOR_DONG': '월계2동',
    'TEL': '02-950-7000',
    'FAX': '02-906-5340',
    'HP': 'http://www.induk.ac.kr'},
   {'MAIN_KEY': 'BE_LiST23-0048',
    'YEAR': '2013',
    'CATE1_NAME': '일반대학',
    'NAME_KOR': '장로회신학대학교',
    'BRANCH': '본교',
    'STATE': '기존',
    'TYPE': '사립',
    'POSTCODE': '',
    'ADD_KOR': '서울 광진구 광장로 5길 25-1(광장동) 장로회신학대학교',
    'ADD_KOR_ROAD': '',
    'H_KOR_CITY': '서울특별시',
    'H_KOR_GU': '광진구',
    'H_KOR_DONG': '광장동',
    'TEL': '02-450-0700',
    'FAX': '',
    'HP': 'http://www.pcts.ac.kr'},
   {'MAIN_KEY': 'BE_LiST23-0049',
    'YEAR': '2013',
    'CATE1_NAME': '전문대학(3년제)',
    'NAME_KOR': '적십자간호대학',
    'BRANCH': '본교',
    'STATE': '폐교',
    'TYPE': '사립',
    'POSTCODE': '',
    'ADD_KOR': '서울 종로구 경교장길8',
    'ADD_KOR_ROAD': '',
    'H_KOR_CITY': '서울특별시',
    'H_KOR_GU': '종로구',
    'H_KOR_DONG': '교남동',
    'TEL': '02-3700-3600',
    'FAX': '02-3700-3400',
    'HP': 'http://redcross.cau.ac.kr'},
   {'MAIN_KEY': 'BE_LiST23-0050',
    'YEAR': '2013',
    'CATE1_NAME': '일반대학',
    'NAME_KOR': '중앙대학교 서울캠퍼스',
    'BRANCH': '본교',
    'STATE': '기존',
    'TYPE': '사립',
    'POSTCODE': '',
    'ADD_KOR': '서울 동작구 흑석로 84',
    'ADD_KOR_ROAD': '',
    'H_KOR_CITY': '서울특별시',
    'H_KOR_GU': '동작구',
    'H_KOR_DONG': '흑석동',
    'TEL': '02-820-5114',
    'FAX': '',
    'HP': 'http://www.cau.ac.kr'},
   {'MAIN_KEY': 'BE_LiST23-0051',
    'YEAR': '2013',
    'CATE1_NAME': '일반대학',
    'NAME_KOR': '총신대학교',
    'BRANCH': '본교',
    'STATE': '기존',
    'TYPE': '사립',
    'POSTCODE': '',
    'ADD_KOR': '서울 동작구 사당동 산31-3',
    'ADD_KOR_ROAD': '',
    'H_KOR_CITY': '서울특별시',
    'H_KOR_GU': '동작구',
    'H_KOR_DONG': '사당3동',
    'TEL': '02-3479-0200',
    'FAX': '02-536-2602',
    'HP': 'http://www.chongshin.ac.kr'},
   {'MAIN_KEY': 'BE_LiST23-0052',
    'YEAR': '2013',
    'CATE1_NAME': '일반대학',
    'NAME_KOR': '추계예술대학교',
    'BRANCH': '본교',
    'STATE': '기존',
    'TYPE': '사립',
    'POSTCODE': '',
    'ADD_KOR': '서울 서대문구 북아현동 190-1 추계예술대학교',
    'ADD_KOR_ROAD': '',
    'H_KOR_CITY': '서울특별시',
    'H_KOR_GU': '서대문구',
    'H_KOR_DONG': '충현동',
    'TEL': '02-362-5700',
    'FAX': '02-392-1777',
    'HP': 'http://www.chugye.ac.kr'},
   {'MAIN_KEY': 'BE_LiST23-0053',
    'YEAR': '2013',
    'CATE1_NAME': '방송통신대학',
    'NAME_KOR': '한국방송통신대학교',
    'BRANCH': '본교',
    'STATE': '기존',
    'TYPE': '국립',
    'POSTCODE': '',
    'ADD_KOR': '서울 종로구 동숭동 한국방송통신대학교',
    'ADD_KOR_ROAD': '',
    'H_KOR_CITY': '서울특별시',
    'H_KOR_GU': '종로구',
    'H_KOR_DONG': '이화동',
    'TEL': '02-3668-4114',
    'FAX': '02-744-5882',
    'HP': 'http://www.knou.ac.kr'},
   {'MAIN_KEY': 'BE_LiST23-0054',
    'YEAR': '2013',
    'CATE1_NAME': '일반대학',
    'NAME_KOR': '한국성서대학교',
    'BRANCH': '본교',
    'STATE': '기존',
    'TYPE': '사립',
    'POSTCODE': '',
    'ADD_KOR': '서울 노원구 상계7동 한국성서대학교',
    'ADD_KOR_ROAD': '',
    'H_KOR_CITY': '서울특별시',
    'H_KOR_GU': '노원구',
    'H_KOR_DONG': '상계6.7동',
    'TEL': '02-950-5401',
    'FAX': '02-950-5411',
    'HP': 'http://www.bible.ac.kr'},
   {'MAIN_KEY': 'BE_LiST23-0055',
    'YEAR': '2013',
    'CATE1_NAME': '각종대학(대학)',
    'NAME_KOR': '한국예술종합학교',
    'BRANCH': '본교',
    'STATE': '기존',
    'TYPE': '특별법국립',
    'POSTCODE': '',
    'ADD_KOR': '서울 성북구 석관동 ',
    'ADD_KOR_ROAD': '',
    'H_KOR_CITY': '서울특별시',
    'H_KOR_GU': '성북구',
    'H_KOR_DONG': '석관동',
    'TEL': '',
    'FAX': '',
    'HP': ''},
   {'MAIN_KEY': 'BE_LiST23-0056',
    'YEAR': '2013',
    'CATE1_NAME': '일반대학',
    'NAME_KOR': '한국외국어대학교',
    'BRANCH': '본교',
    'STATE': '기존',
    'TYPE': '사립',
    'POSTCODE': '',
    'ADD_KOR': '서울 동대문구 이문로 107',
    'ADD_KOR_ROAD': '',
    'H_KOR_CITY': '서울특별시',
    'H_KOR_GU': '동대문구',
    'H_KOR_DONG': '이문1동',
    'TEL': '02-2173-2114',
    'FAX': '',
    'HP': 'http://www.hufs.ac.kr'},
   {'MAIN_KEY': 'BE_LiST23-0057',
    'YEAR': '2013',
    'CATE1_NAME': '일반대학',
    'NAME_KOR': '한국체육대학교',
    'BRANCH': '본교',
    'STATE': '기존',
    'TYPE': '국립',
    'POSTCODE': '',
    'ADD_KOR': '서울 송파구 오륜동 한국체육대학교',
    'ADD_KOR_ROAD': '',
    'H_KOR_CITY': '서울특별시',
    'H_KOR_GU': '송파구',
    'H_KOR_DONG': '오륜동',
    'TEL': '02-410-6564',
    'FAX': '02-410-6569',
    'HP': 'http://www.knsu.ac.kr/'},
   {'MAIN_KEY': 'BE_LiST23-0058',
    'YEAR': '2013',
    'CATE1_NAME': '기능대학',
    'NAME_KOR': '한국폴리텍 I 대학 서울강서캠퍼스',
    'BRANCH': '본교',
    'STATE': '기존',
    'TYPE': '사립',
    'POSTCODE': '',
    'ADD_KOR': '서울 강서구 화곡동 산60-1',
    'ADD_KOR_ROAD': '',
    'H_KOR_CITY': '서울특별시',
    'H_KOR_GU': '강서구',
    'H_KOR_DONG': '우장산동',
    'TEL': '02-2186-5800',
    'FAX': '02-2186-5819',
    'HP': 'http://kangseo.kopo.ac.kr'},
   {'MAIN_KEY': 'BE_LiST23-0059',
    'YEAR': '2013',
    'CATE1_NAME': '기능대학',
    'NAME_KOR': '한국폴리텍Ⅰ대학 서울정수캠퍼스',
    'BRANCH': '본교',
    'STATE': '기존',
    'TYPE': '사립',
    'POSTCODE': '',
    'ADD_KOR': '서울 용산구 보광로 73(보광동 238)',
    'ADD_KOR_ROAD': '',
    'H_KOR_CITY': '서울특별시',
    'H_KOR_GU': '용산구',
    'H_KOR_DONG': '보광동',
    'TEL': '02-2001-4000',
    'FAX': '02-2001-4119',
    'HP': 'http://jungsu.kopo.ac.kr'},
   {'MAIN_KEY': 'BE_LiST23-0060',
    'YEAR': '2013',
    'CATE1_NAME': '일반대학',
    'NAME_KOR': '한성대학교',
    'BRANCH': '본교',
    'STATE': '기존',
    'TYPE': '사립',
    'POSTCODE': '',
    'ADD_KOR': '서울 성북구 삼선동3가 389 한성대학교',
    'ADD_KOR_ROAD': '',
    'H_KOR_CITY': '서울특별시',
    'H_KOR_GU': '성북구',
    'H_KOR_DONG': '삼선동',
    'TEL': '02-760-4231',
    'FAX': '02-745-8943',
    'HP': 'http://www.hansung.ac.kr'},
   {'MAIN_KEY': 'BE_LiST23-0061',
    'YEAR': '2013',
    'CATE1_NAME': '일반대학',
    'NAME_KOR': '한양대학교',
    'BRANCH': '본교',
    'STATE': '기존',
    'TYPE': '사립',
    'POSTCODE': '',
    'ADD_KOR': '서울특별시 성동구 왕십리로 222 ',
    'ADD_KOR_ROAD': '',
    'H_KOR_CITY': '서울특별시',
    'H_KOR_GU': '성동구',
    'H_KOR_DONG': '사근동',
    'TEL': '02-2220-0114',
    'FAX': '',
    'HP': 'http://www.hanyang.ac.kr'},
   {'MAIN_KEY': 'BE_LiST23-0062',
    'YEAR': '2013',
    'CATE1_NAME': '전문대학(2년제)',
    'NAME_KOR': '한양여자대학교',
    'BRANCH': '본교',
    'STATE': '기존',
    'TYPE': '사립',
    'POSTCODE': '',
    'ADD_KOR': '서울 성동구 행당동 살곶이길 200',
    'ADD_KOR_ROAD': '',
    'H_KOR_CITY': '서울특별시',
    'H_KOR_GU': '성동구',
    'H_KOR_DONG': '사근동',
    'TEL': '02-2290-2114',
    'FAX': '02-2291-6111',
    'HP': 'http://www.hywoman.ac.kr'},
   {'MAIN_KEY': 'BE_LiST23-0063',
    'YEAR': '2013',
    'CATE1_NAME': '일반대학',
    'NAME_KOR': '한영신학대학교',
    'BRANCH': '본교',
    'STATE': '기존',
    'TYPE': '사립',
    'POSTCODE': '',
    'ADD_KOR': '서울 구로구 경인로 290-42  한영신학대학교',
    'ADD_KOR_ROAD': '',
    'H_KOR_CITY': '서울특별시',
    'H_KOR_GU': '구로구',
    'H_KOR_DONG': '개봉1동',
    'TEL': '02-2067-4500',
    'FAX': '02-2616-4102',
    'HP': 'http://www.hytu.ac.kr'},
   {'MAIN_KEY': 'BE_LiST23-0064',
    'YEAR': '2013',
    'CATE1_NAME': '일반대학',
    'NAME_KOR': '홍익대학교',
    'BRANCH': '본교',
    'STATE': '기존',
    'TYPE': '사립',
    'POSTCODE': '',
    'ADD_KOR': '서울특별시 마포구 와우산로 94(상수동)',
    'ADD_KOR_ROAD': '',
    'H_KOR_CITY': '서울특별시',
    'H_KOR_GU': '마포구',
    'H_KOR_DONG': '서강동',
    'TEL': '02-320-1114',
    'FAX': '02-320-1122',
    'HP': 'http://www.hongik.ac.kr/'},
   {'MAIN_KEY': 'BE_LiST23-0001',
    'YEAR': '2013',
    'CATE1_NAME': '일반대학',
    'NAME_KOR': '가톨릭대학교',
    'BRANCH': '제2캠퍼스',
    'STATE': '기존',
    'TYPE': '사립',
    'POSTCODE': '',
    'ADD_KOR': '서울 서초구 반포동 505',
    'ADD_KOR_ROAD': '',
    'H_KOR_CITY': '서울특별시',
    'H_KOR_GU': '서초구',
    'H_KOR_DONG': '반포4동',
    'TEL': '',
    'FAX': '',
    'HP': 'http://songeui.catholic.ac.kr'},
   {'MAIN_KEY': 'BE_LiST23-0002',
    'YEAR': '2013',
    'CATE1_NAME': '일반대학',
    'NAME_KOR': '가톨릭대학교',
    'BRANCH': '제3캠퍼스',
    'STATE': '기존',
    'TYPE': '사립',
    'POSTCODE': '',
    'ADD_KOR': '서울 종로구 창경궁로 296-12(혜화동) ',
    'ADD_KOR_ROAD': '',
    'H_KOR_CITY': '서울특별시',
    'H_KOR_GU': '종로구',
    'H_KOR_DONG': '이화동',
    'TEL': '02-740-9714',
    'FAX': '02-741-2801',
    'HP': 'http://catholic.ac.kr'},
   {'MAIN_KEY': 'BE_LiST23-0003',
    'YEAR': '2013',
    'CATE1_NAME': '일반대학',
    'NAME_KOR': '감리교신학대학교',
    'BRANCH': '본교',
    'STATE': '기존',
    'TYPE': '사립',
    'POSTCODE': '',
    'ADD_KOR': '서울 서대문구 냉천동 감리교신학대학',
    'ADD_KOR_ROAD': '',
    'H_KOR_CITY': '서울특별시',
    'H_KOR_GU': '서대문구',
    'H_KOR_DONG': '천연동',
    'TEL': '02-361-9114',
    'FAX': '02-361-9299',
    'HP': 'http://www.mtu.ac.kr'},
   {'MAIN_KEY': 'BE_LiST23-0004',
    'YEAR': '2013',
    'CATE1_NAME': '일반대학',
    'NAME_KOR': '건국대학교',
    'BRANCH': '본교',
    'STATE': '기존',
    'TYPE': '사립',
    'POSTCODE': '',
    'ADD_KOR': '서울 광진구 화양동',
    'ADD_KOR_ROAD': '',
    'H_KOR_CITY': '서울특별시',
    'H_KOR_GU': '광진구',
    'H_KOR_DONG': '화양동',
    'TEL': '02-450-3114',
    'FAX': '02-450-4126',
    'HP': 'http://www.konkuk.ac.kr'},
   {'MAIN_KEY': 'BE_LiST23-0005',
    'YEAR': '2013',
    'CATE1_NAME': '일반대학',
    'NAME_KOR': '경기대학교',
    'BRANCH': '제2캠퍼스',
    'STATE': '기존',
    'TYPE': '사립',
    'POSTCODE': '',
    'ADD_KOR': '서울 서대문구 경기대로9길 24 경기대학교',
    'ADD_KOR_ROAD': '',
    'H_KOR_CITY': '서울특별시',
    'H_KOR_GU': '서대문구',
    'H_KOR_DONG': '충현동',
    'TEL': '02-390-5114',
    'FAX': '031-249-8718',
    'HP': 'http://www.kyonggi.ac.kr'},
   {'MAIN_KEY': 'BE_LiST23-0006',
    'YEAR': '2013',
    'CATE1_NAME': '일반대학',
    'NAME_KOR': '경희대학교',
    'BRANCH': '본교',
    'STATE': '기존',
    'TYPE': '사립',
    'POSTCODE': '',
    'ADD_KOR': '서울 동대문구 회기동 경희대학교',
    'ADD_KOR_ROAD': '',
    'H_KOR_CITY': '서울특별시',
    'H_KOR_GU': '동대문구',
    'H_KOR_DONG': '회기동',
    'TEL': '02-961-0114',
    'FAX': '02-961-0930',
    'HP': 'http://www.khu.ac.kr'},
   {'MAIN_KEY': 'BE_LiST23-0007',
    'YEAR': '2013',
    'CATE1_NAME': '일반대학',
    'NAME_KOR': '고려대학교',
    'BRANCH': '본교',
    'STATE': '기존',
    'TYPE': '사립',
    'POSTCODE': '',
    'ADD_KOR': '서울 성북구 안암동 고려대학교',
    'ADD_KOR_ROAD': '',
    'H_KOR_CITY': '서울특별시',
    'H_KOR_GU': '성북구',
    'H_KOR_DONG': '안암동',
    'TEL': '02-3290-1114',
    'FAX': '',
    'HP': 'http://www.korea.ac.kr'},
   {'MAIN_KEY': 'BE_LiST23-0008',
    'YEAR': '2013',
    'CATE1_NAME': '일반대학',
    'NAME_KOR': '광운대학교',
    'BRANCH': '본교',
    'STATE': '기존',
    'TYPE': '사립',
    'POSTCODE': '',
    'ADD_KOR': '서울특별시 노원구 월계동 447-1',
    'ADD_KOR_ROAD': '',
    'H_KOR_CITY': '서울특별시',
    'H_KOR_GU': '노원구',
    'H_KOR_DONG': '월계1동',
    'TEL': '',
    'FAX': '',
    'HP': 'http://www.kw.ac.kr'},
   {'MAIN_KEY': 'BE_LiST23-0009',
    'YEAR': '2013',
    'CATE1_NAME': '일반대학',
    'NAME_KOR': '국민대학교',
    'BRANCH': '본교',
    'STATE': '기존',
    'TYPE': '사립',
    'POSTCODE': '',
    'ADD_KOR': '서울 성북구 정릉3동 국민대학교',
    'ADD_KOR_ROAD': '',
    'H_KOR_CITY': '서울특별시',
    'H_KOR_GU': '성북구',
    'H_KOR_DONG': '정릉3동',
    'TEL': '02-910-4114',
    'FAX': '',
    'HP': 'http://www.kookmin.ac.kr'},
   {'MAIN_KEY': 'BE_LiST23-0010',
    'YEAR': '2013',
    'CATE1_NAME': '전공대학',
    'NAME_KOR': '국제예술대학',
    'BRANCH': '본교',
    'STATE': '기존',
    'TYPE': '사립',
    'POSTCODE': '',
    'ADD_KOR': '서울 강남구 논현동 79',
    'ADD_KOR_ROAD': '',
    'H_KOR_CITY': '서울특별시',
    'H_KOR_GU': '강남구',
    'H_KOR_DONG': '논현2동',
    'TEL': '02-542-8197',
    'FAX': '02-517-1392',
    'HP': 'http://www.kica.ac.kr'},
   {'MAIN_KEY': 'BE_LiST23-0011',
    'YEAR': '2013',
    'CATE1_NAME': '일반대학',
    'NAME_KOR': '그리스도대학교',
    'BRANCH': '본교',
    'STATE': '기존',
    'TYPE': '사립',
    'POSTCODE': '',
    'ADD_KOR': '서울 강서구 화곡6동 그리스도대학교',
    'ADD_KOR_ROAD': '',
    'H_KOR_CITY': '서울특별시',
    'H_KOR_GU': '강서구',
    'H_KOR_DONG': '화곡본동',
    'TEL': '02-2600-2400',
    'FAX': '02-2698-8876',
    'HP': 'http://kcu.ac.kr'},
   {'MAIN_KEY': 'BE_LiST23-0012',
    'YEAR': '2013',
    'CATE1_NAME': '일반대학',
    'NAME_KOR': '덕성여자대학교',
    'BRANCH': '본교',
    'STATE': '기존',
    'TYPE': '사립',
    'POSTCODE': '',
    'ADD_KOR': '서울특별시 도봉구 삼양로 144길 33',
    'ADD_KOR_ROAD': '',
    'H_KOR_CITY': '서울특별시',
    'H_KOR_GU': '도봉구',
    'H_KOR_DONG': '쌍문1동',
    'TEL': '02-901-8000',
    'FAX': '',
    'HP': 'http://www.duksung.ac.kr'},
   {'MAIN_KEY': 'BE_LiST23-0013',
    'YEAR': '2013',
    'CATE1_NAME': '일반대학',
    'NAME_KOR': '동국대학교',
    'BRANCH': '본교',
    'STATE': '기존',
    'TYPE': '사립',
    'POSTCODE': '',
    'ADD_KOR': '서울 중구 필동3가 동국대학교',
    'ADD_KOR_ROAD': '',
    'H_KOR_CITY': '서울특별시',
    'H_KOR_GU': '중구',
    'H_KOR_DONG': '필동',
    'TEL': '02-2260-3114',
    'FAX': '02-2277-1274',
    'HP': 'http://www.dongguk.edu'},
   {'MAIN_KEY': 'BE_LiST23-0014',
    'YEAR': '2013',
    'CATE1_NAME': '일반대학',
    'NAME_KOR': '동덕여자대학교',
    'BRANCH': '본교',
    'STATE': '기존',
    'TYPE': '사립',
    'POSTCODE': '',
    'ADD_KOR': '서울 성북구 하월곡2동 동덕여자대학교',
    'ADD_KOR_ROAD': '',
    'H_KOR_CITY': '서울특별시',
    'H_KOR_GU': '성북구',
    'H_KOR_DONG': '삼선동',
    'TEL': '02-940-4000',
    'FAX': '02-940-4182',
    'HP': 'http://www.dongduk.ac.kr'},
   {'MAIN_KEY': 'BE_LiST23-0015',
    'YEAR': '2013',
    'CATE1_NAME': '전문대학(3년제)',
    'NAME_KOR': '동양미래대학교',
    'BRANCH': '본교',
    'STATE': '기존',
    'TYPE': '사립',
    'POSTCODE': '',
    'ADD_KOR': '서울시 구로구 경인로 445 동양미래대학교 (고척동 62-160)',
    'ADD_KOR_ROAD': '',
    'H_KOR_CITY': '서울특별시',
    'H_KOR_GU': '구로구',
    'H_KOR_DONG': '고척1동',
    'TEL': '02-2610-1700',
    'FAX': '02-2688-5494',
    'HP': 'http://www.dongyang.ac.kr/'},
   {'MAIN_KEY': 'BE_LiST23-0016',
    'YEAR': '2013',
    'CATE1_NAME': '사이버대학(대학)',
    'NAME_KOR': '디지털서울문화예술대학교',
    'BRANCH': '본교',
    'STATE': '기존',
    'TYPE': '사립',
    'POSTCODE': '',
    'ADD_KOR': '서울시 서대문구 통일로 37길 60 (홍제동 318-18)',
    'ADD_KOR_ROAD': '',
    'H_KOR_CITY': '서울특별시',
    'H_KOR_GU': '서대문구',
    'H_KOR_DONG': '홍제1동',
    'TEL': '02-2287-0222',
    'FAX': '02-379-8828',
    'HP': 'http://www.scau.ac.kr'},
   {'MAIN_KEY': 'BE_LiST23-0017',
    'YEAR': '2013',
    'CATE1_NAME': '일반대학',
    'NAME_KOR': '명지대학교 인문캠퍼스',
    'BRANCH': '제2캠퍼스',
    'STATE': '기존',
    'TYPE': '사립',
    'POSTCODE': '',
    'ADD_KOR': '서울 서대문구 남가좌동 50-3',
    'ADD_KOR_ROAD': '',
    'H_KOR_CITY': '서울특별시',
    'H_KOR_GU': '서대문구',
    'H_KOR_DONG': '남가좌2동',
    'TEL': '02-300-1556',
    'FAX': '02-300-1556',
    'HP': 'http://www.mju.ac.kr'},
   {'MAIN_KEY': 'BE_LiST23-0018',
    'YEAR': '2013',
    'CATE1_NAME': '전문대학(3년제)',
    'NAME_KOR': '명지전문대학',
    'BRANCH': '본교',
    'STATE': '기존',
    'TYPE': '사립',
    'POSTCODE': '',

In [28]:
import pandas as pd
temp = []
for d in data['SebcCollegeInfoKor']['row']:
    temp.append(d)
uni = pd.DataFrame(temp)
uni

,MAIN_KEY,YEAR,CATE1_NAME,NAME_KOR,BRANCH,STATE,TYPE,POSTCODE,ADD_KOR,ADD_KOR_ROAD,H_KOR_CITY,H_KOR_GU,H_KOR_DONG,TEL,FAX,HP
0,BE_LiST23-0034,2013,일반대학,서울시립대학교,본교,기존,공립,,서울 동대문구 서울시립대로 163 (전농동 90번지),,서울특별시,동대문구,휘경2동,02-6490-6114,02-2210-5576,http://www.uos.ac.kr
1,BE_LiST23-0035,2013,전문대학(3년제),서울여자간호대학교,본교,기존,사립,,서울 서대문구 홍제3동 서울여자간호대학,,서울특별시,서대문구,홍제2동,02-2287-1700,02-395-8018,http://www.snjc.ac.kr
2,BE_LiST23-0036,2013,일반대학,서울여자대학교,본교,기존,사립,,서울특별시 노원구 화랑로 621 서울여자대학교,,서울특별시,노원구,공릉2동,02-970-5114,02-978-7931,http://www.swu.ac.kr
3,BE_LiST23-0037,2013,전문대학(2년제),서일대학교,본교,학교명 변경,사립,,서울 중랑구 서일대학길 22(면목동 49-3) 서일대학교,,서울특별시,중랑구,면목제3.8동,02-490-7300,02-493-2576,http://www.seoil.ac.kr
4,BE_LiST23-0038,2013,일반대학,성공회대학교,본교,기존,사립,,서울 구로구 항동 성공회대학교,,서울특별시,구로구,오류2동,02-2610-4142,02-2610-4248,http://www.skhu.ac.kr
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
59,BE_LiST23-0029,2013,교육대학,서울교육대학교,본교,기존,국립,,서울 서초구 서초중앙로 96(서초동 1650),,서울특별시,서초구,서초1동,02-3475-2114,02-581-7711,http://www.snue.ac.kr
60,BE_LiST23-0030,2013,일반대학,서울기독대학교,본교,기존,사립,,서울 은평구 갈현로 4길 26-2호,,서울특별시,은평구,신사1동,02-380-2500,02-380-2535,http://www.scu.ac.kr
61,BE_LiST23-0031,2013,일반대학,서울대학교,본교,기존,국립대법인,,서울 관악구 관악로 1 서울대학교,,서울특별시,관악구,낙성대동,02-880-5114,02-885-5272,http://www.snu.ac.kr
62,BE_LiST23-0032,2013,사이버대학(대학),서울디지털대학교,본교,기존,사립,,서울 마포구 도화동 560번지,,서울특별시,마포구,도화동,02-1644-0982,02-2128-3006,http://www.sdu.ac.kr
63,BE_LiST23-0033,2013,사이버대학(대학),서울사이버대학교,본교,기존,사립,,서울 강북구 솔매로49길 60(미아동 193-15) 서울사이버대학교,,서울특별시,강북구,미아동,02-944-5000,02-980-2222,http://www.iscu.ac.kr

In [29]:
import requests

url = 'http://openapi.seoul.go.kr:8088/(인증키)/json/viewNightSpot/1/100/'

response = requests.get(url)
print(response.content)

b'{"viewNightSpot":{"list_total_count":51,"RESULT":{"CODE":"INFO-000","MESSAGE":"\xec\xa0\x95\xec\x83\x81 \xec\xb2\x98\xeb\xa6\xac\xeb\x90\x98\xec\x97\x88\xec\x8a\xb5\xeb\x8b\x88\xeb\x8b\xa4"},"row":[{"NUM":1.0,"SUBJECT_CD":"\xeb\xac\xb8\xed\x99\x94/\xec\xb2\xb4\xec\x9c\xa1","TITLE":"\xeb\x82\xa8\xec\x82\xb0\xec\x84\x9c\xec\x9a\xb8\xed\x83\x80\xec\x9b\x8c","ADDR":"\xec\x84\x9c\xec\x9a\xb8\xed\x8a\xb9\xeb\xb3\x84\xec\x8b\x9c \xec\x9a\xa9\xec\x82\xb0\xea\xb5\xac \xeb\x82\xa8\xec\x82\xb0\xea\xb3\xb5\xec\x9b\x90\xea\xb8\xb8 105","LA":"37.5511225714939","LO":"126.987867837993","TEL_NO":"02-3455-9277, 9288","URL":"https://www.seoultower.co.kr/","OPERATING_TIME":"\xec\x97\xb0\xec\xa4\x91\xeb\xac\xb4\xed\x9c\xb4 * \xed\x83\x80\xec\x9b\x8c\xeb\x82\xb4 \xea\xb0\x9c\xeb\xb3\x84\xec\x8b\x9c\xec\x84\xa4 \xec\x9a\xb4\xec\x98\x81\xec\x8b\x9c\xea\xb0\x84 \xec\x83\x81\xec\x9d\xb4","FREE_YN":"\xeb\xac\xb4\xeb\xa3\x8c","ENTR_FEE":"\xeb\x82\xa8\xec\x82\xb0\xea\xb3\xb5\xec\x9b\x90 \xec\x9e\x85\xec\x9e\xa5\xeb\xa3\x8c \xec\x97\x86\xec\x9d\x8c(\xec\xa0\x84\xeb\xa7\x9d\xeb\x8c\x80 \xeb\x93\xb1 \xea\xb0\x9c\xeb\xb3\x84 \xec\x9d\xb4\xec\x9a\xa9\xec\x8b\x9c\xec\x84\xa4 \xec\x9a\x94\xea\xb8\x88 \xeb\xb3\x84\xeb\x8f\x84)","CONTENTS":"<p>\xeb\x82\xa8\xec\x82\xb0\xec\x84\x9c\xec\x9a\xb8\xed\x83\x80\xec\x9b\x8c\xeb\x8a\x94 \xed\x9a\xa8\xec\x9c\xa8\xec\xa0\x81\xec\x9d\xb8 \xeb\xb0\xa9\xec\x86\xa1\xec\xa0\x84\xed\x8c\x8c \xec\x86\xa1\xec\x88\x98\xec\x8b\xa0\xea\xb3\xbc \xed\x95\x9c\xea\xb5\xad\xec\x9d\x98 \xec\xa0\x84\xed\x86\xb5\xeb\xaf\xb8\xeb\xa5\xbc \xec\x82\xb4\xeb\xa6\xb0 \xea\xb4\x80\xea\xb4\x91 \xec\xa0\x84\xeb\xa7\x9d\xec\x8b\x9c\xec\x84\xa4\xec\x9d\x98 \xea\xb8\xb0\xeb\x8a\xa5\xec\x9d\x84 \xea\xb2\xb8\xeb\xb9\x84\xed\x95\x9c \xea\xb5\xad\xeb\x82\xb4 \xec\xb5\x9c\xec\xb4\x88\xec\x9d\x98 \xec\xa2\x85\xed\x95\xa9\xec\xa0\x84\xed\x8c\x8c \xed\x83\x91\xec\x9c\xbc\xeb\xa1\x9c \xeb\xb0\xa9\xec\x86\xa1\xeb\xac\xb8\xed\x99\x94\xec\x99\x80 \xea\xb4\x80\xea\xb4\x91\xec\x82\xb0\xec\x97\x85\xec\x9d\x98 \xeb\xaf\xb8\xeb\x9e\x98\xeb\xa5\xbc \xec\x9c\x84\xed\x95\xb4 \xea\xb1\xb4\xeb\xa6\xbd\xeb\x90\x98\xec\x97\x88\xec\x8a\xb5\xeb\x8b\x88\xeb\x8b\xa4.</p>\\r\\n<p>\xec\x84\xb8\xea\xb3\x84 \xec\x9c\xa0\xeb\xaa\x85\xed\x95\x9c \xec\xa2\x85\xed\x95\xa9 \xed\x83\x91\xeb\x93\xa4\xec\x9d\xb4 \xea\xb7\xb8 \xeb\x82\x98\xeb\x9d\xbc \xeb\x98\x90\xeb\x8a\x94 \xea\xb7\xb8 \xeb\x8f\x84\xec\x8b\x9c\xec\x9d\x98 \xec\x83\x81\xec\xa7\x95\xec\xa0\x81\xec\x9d\xb8 \xec\xa1\xb4\xec\x9e\xac\xea\xb0\x80 \xeb\x90\x9c \xea\xb2\x83\xec\xb2\x98\xeb\x9f\xbc \xeb\x82\xa8\xec\x82\xb0\xec\x84\x9c\xec\x9a\xb8\xed\x83\x80\xec\x9b\x8c \xec\x97\xad\xec\x8b\x9c \xec\xa7\x80\xeb\x82\x9c 40\xec\x97\xac \xeb\x85\x84\xea\xb0\x84 \xeb\x8c\x80\xed\x95\x9c\xeb\xaf\xbc\xea\xb5\xad\xec\x9d\x98 \xeb\x8c\x80\xed\x91\x9c\xec\xa0\x81\xec\x9d\xb8 \xea\xb4\x80\xea\xb4\x91\xec\xa7\x80\xec\x9d\xb4\xec\x9e\x90 \xec\x84\x9c\xec\x9a\xb8\xec\x9d\x98 \xec\x83\x81\xec\xa7\x95\xeb\xac\xbc \xec\x97\xad\xed\x95\xa0\xec\x9d\x84 \xed\x95\xb4\xec\x99\x94\xec\x8a\xb5\xeb\x8b\x88\xeb\x8b\xa4.</p>\\r\\n<p>\xeb\x82\xa8\xec\x82\xb0\xec\x84\x9c\xec\x9a\xb8\xed\x83\x80\xec\x9b\x8c\xeb\x8a\x94 \xec\x84\x9c\xec\x9a\xb8 \xec\x8b\x9c\xeb\x82\xb4 \xec\xa0\x84 \xec\xa7\x80\xec\x97\xad\xec\x97\x90\xec\x84\x9c \xeb\xb0\x94\xeb\x9d\xbc\xeb\xb3\xb4\xec\x9d\xb4\xeb\x8a\x94 \xed\x83\x91\xec\x9d\x98 \xeb\x86\x92\xec\x9d\xb4\xec\x99\x80 \xeb\x8f\x85\xed\x8a\xb9\xed\x95\x9c \xea\xb5\xac\xec\xa1\xb0, \xed\x98\x95\xed\x83\x9c \xeb\x93\xb1\xec\x9c\xbc\xeb\xa1\x9c \xec\x9d\xb8\xed\x95\x98\xec\x97\xac \xec\x8b\x9c\xeb\xaf\xbc\xec\x9d\x98 \xea\xb4\x80\xec\x8b\xac\xea\xb3\xbc \xec\x82\xac\xeb\x9e\x91\xec\x9d\x98 \xeb\x8c\x80\xec\x83\x81\xec\x9d\xb4 \xeb\x90\x98\xec\x97\x88\xea\xb3\xa0, \xeb\x82\xb4\xec\x99\xb8\xea\xb5\xad\xec\x9d\xb8\xeb\x93\xa4\xec\x9d\xb4 \xec\xa6\x90\xea\xb2\xa8 \xec\xb0\xbe\xeb\x8a\x94 \xec\xa0\x9c1\xec\x9d\x98 \xea\xb4\x80\xea\xb4\x91 \xeb\xaa\x85\xec\x86\x8c\xeb\xa1\x9c\xec\x84\x9c\xec\x9d\x98 \xec\x9c\x84\xec\xb9\x98\xeb\xa5\xbc \xed\x99\x95\xea\xb3\xa0\xed\x9e\x88 \xed\x95\x98\xea\xb3\xa0 \xec\x9e\x88\xec\x8a\xb5\xeb\x8b\x88\xeb\x8b\xa4. \xec\xb5\x9c\xea\xb7\xbc\xec\x97\x90\xeb\x8a\x94 \xed\x95\x9c\xeb\xa5\x98 \xeb\xb0\x94\xeb\x9e\x8c\xec\x9d\x84 \xeb\xaa\xb0\xea\xb3\xa0 \xec\x98\xa8 \xea\xb0\x81\xec\xa2\x85 \xec\x98\x88\xeb\x8a\xa5, \xeb\x93\x9c\xeb\x9d\xbc\xeb\xa7\x88\xec\x9d\x98 \xec\xb4\xac\xec\x98\x81\xec\xa7\x80\xeb\xa1\x9c \xec\x9d\xb4\xeb\xa6\x84\xec\x9d\xb4 \xeb\x86\x92\xec\x95\x84\xec\xa7\x80\xeb\xa9\xb4\xec\x84\x9c \xeb\x82\xb4\xec\x99\xb8\xea\xb5\xad\xec\x9d\xb8 \xea\xb4\x80\xea\xb4\x91\xea\xb0\x9d\xeb\x93\xa4\xec\x9d\xb4 \xeb\xb0\x9c\xea\xb8\xb8\xec\x9d\xb4 \xeb\x81\x8a\xec\x9d\xb4\xec\xa7\x80 \xec\x95\x8a\xeb\x8a\x94 \xea\xb3\xb3\xec\x9e\x85\xeb\x8b\x88\xeb\x8b\xa4.</p>\\r\\n<p>(\xec\xb6\x9c\xec\xb2\x98 : \xeb\x82\xa8\xec\x82\xb0\xec\x84\x9c\xec\x9a\xb8\xed\x83\x80\xec\x9b\x8c \xed\x99\x88\xed\x8e\x98\xec\x9d\xb4\xec\xa7\x80)</p>\\r\\n<p>\xec\xa0\x84\xeb\xa7\x9d\xeb\x8c\x80 \xeb\xbf\x90\xeb\xa7\x8c \xec\x95\x84\xeb\x8b\x88\xeb\x9d\xbc \xeb\x82\xa8\xec\x82\xb0\xea\xb3\xb5\xec\x9b\x90\xec\x97\x90\xec\x84\x9c \xec\x82\xb0\xec\xb1\x85\xed\x95\x98\xeb\xa9\xb4\xec\x84\x9c, \xeb\x82\xa8\xec\x82\xb0\xec\xbc\x80\xec\x9d\xb4\xeb\xb8\x94\xec\xb9\xb4\xeb\xa5\xbc \xec\x9d\xb4\xec\x9a\xa9\xed\x95\x98\xeb\xa9\xb4\xec\x84\x9c, \xeb\x82\xa8\xec\x82\xb0\xeb\x91\x98\xeb\xa0\x88\xea\xb8\xb8 \xed\x8a\xb8\xeb\xa0\x88\xed\x82\xb9\xed\x95\x98\xeb\xa9\xb4\xec\x84\x9c \xec\x84\x9c\xec\x9a\xb8\xec\x9d\x98 \xec\x95\xbc\xea\xb2\xbd\xeb\x8f\x84 \xeb\x8b\xa4\xec\x96\x91\xed\x95\x98\xea\xb2\x8c \xea\xb0\x90\xec\x83\x81\xed\x95\xa0 \xec\x88\x98 \xec\x9e\x88\xec\x8a\xb5\xeb\x8b\x88\xeb\x8b\xa4.</p>","SUBWAY":"\xec\xa7\x80\xed\x95\x98\xec\xb2\xa0 4\xed\x98\xb8\xec\x84\xa0 \xed\x9a\x8c\xed\x98\x84\xec\x97\xad 3\xeb\xb2\x88 \xec\xb6\x9c\xea\xb5\xac \xeb\x8f\x84\xeb\xb3\xb4 \xec\x9d\xb4\xec\x9a\xa9","BUS":"\xeb\x82\xa8\xec\x82\xb0\xec\x88\x9c\xed\x99\x98\xeb\xb2\x84\xec\x8a\xa4 01A\xeb\xb2\x88, 01B\xeb\xb2\x88 \xec\x9d\xb4\xec\x9a\xa9  * \xeb\x82\xa8\xec\x82\xb0\xea\xb3\xb5\xec\x9b\x90 \xec\x83\x9d\xed\x83\x9c \xed\x99\x98\xea\xb2\xbd \xeb\xb3\xb4\xed\x98\xb8 \xec\x9d\xbc\xed\x99\x98\xec\x9c\xbc\xeb\xa1\x9c \xec\x8a\xb9\xec\x9a\xa9\xec\xb0\xa8\xeb\x9f\x89 \xed\x86\xb5\xed\x96\x89 \xec\xa0\x9c\xed\x95\x9c","PARKING_INFO":"","REG_DATE":"2024-06-05 00:00:00.0","MOD_DATE":"2024-06-24 16:59:59.0"},{"NUM":2.0,"SUBJECT_CD":"\xeb\xac\xb8\xed\x99\x94/\xec\xb2\xb4\xec\x9c\xa1","TITLE":"\xec\x9e\xa5\xec\xb6\xa9\xec\xb2\xb4\xec\x9c\xa1\xea\xb4\x80","ADDR":"\xec\x84\x9c\xec\x9a\xb8\xed\x8a\xb9\xeb\xb3\x84\xec\x8b\x9c \xec\xa4\x91\xea\xb5\xac \xeb\x8f\x99\xed\x98\xb8\xeb\xa1\x9c 241","LA":"37.5586406607183","LO":"127.006677513121","TEL_NO":"(\xec\x95\x88\xeb\x82\xb4) 02-2128-2800","URL":"http://www.sisul.or.kr/open_content/jangchung/","OPERATING_TIME":"\xed\x8f\x89\xec\x9d\xbc : 9:00 ~18:00 / \xec\xa3\xbc\xeb\xa7\x90 : \xea\xb2\xbd\xea\xb8\xb0 \xeb\x98\x90\xeb\x8a\x94 \xed\x96\x89\xec\x82\xac\xec\x8b\x9c \xec\x9a\xb4\xec\x98\x81\xec\x8b\x9c\xea\xb0\x84\xec\x97\x90 \xeb\x94\xb0\xeb\x9d\xbc \xec\x83\x81\xec\x9d\xb4","FREE_YN":"\xec\x9c\xa0\xeb\xa3\x8c","ENTR_FEE":"\xea\xb2\xbd\xea\xb8\xb0\xc2\xb7\xed\x96\x89\xec\x82\xac \xec\x8b\x9c\xeb\xa7\x88\xeb\x8b\xa4 \xec\x83\x81\xec\x9d\xb4","CONTENTS":"<p class=\\"0\\"><span lang=\\"EN-US\\">1963</span>\xeb\x85\x84 <span lang=\\"EN-US\\">2</span>\xec\x9b\x94 <span lang=\\"EN-US\\">1</span>\xec\x9d\xbc\xec\x97\x90 \xea\xb0\x9c\xec\x9e\xa5\xed\x95\x9c \xea\xb5\xad\xeb\x82\xb4 \xec\xb5\x9c\xec\xb4\x88\xec\x9d\x98 \xec\x8b\xa4\xeb\x82\xb4\xec\xb2\xb4\xec\x9c\xa1\xea\xb4\x80\xec\x9c\xbc\xeb\xa1\x9c\xec\x84\x9c \xec\x84\x9c\xec\x9a\xb8 \xec\xa4\x91\xea\xb5\xac \xec\x9e\xa5\xec\xb6\xa9\xeb\x8f\x99\xec\x97\x90 \xec\x9c\x84\xec\xb9\x98\xed\x95\x98\xea\xb3\xa0 \xec\x9e\x88\xec\x9c\xbc\xeb\xa9\xb0 \xec\xa7\x80\xed\x95\x98<span lang=\\"EN-US\\">2</span>\xec\xb8\xb5<span lang=\\"EN-US\\">, </span>\xec\xa7\x80\xec\x83\x81<span lang=\\"EN-US\\">3</span>\xec\xb8\xb5<span lang=\\"EN-US\\">, </span>\xec\x97\xb0\xeb\xa9\xb4\xec\xa0\x81 <span lang=\\"EN-US\\">11,399.2</span>\xe3\x8e\xa1<span lang=\\"EN-US\\">, </span>\xea\xb4\x80\xeb\x9e\x8c\xec\x84\x9d\xec\x9d\x80 <span lang=\\"EN-US\\">4,507</span>\xec\x84\x9d\xec\x9d\xb4\xeb\x8b\xa4<span lang=\\"EN-US\\">.</span></p>\\r\\n<p class=\\"0\\">\xec\xa3\xbc\xec\x9a\x94\xec\x8b\x9c\xec\x84\xa4\xeb\xa1\x9c\xeb\x8a\x94 \xec\xa3\xbc\xec\xb2\xb4\xec\x9c\xa1\xea\xb4\x80\xea\xb3\xbc \xeb\xb3\xb4\xec\xa1\xb0\xec\xb2\xb4\xec\x9c\xa1\xea\xb4\x80<span lang=\\"EN-US\\">, </span>\xeb\x8b\xa4\xeb\xaa\xa9\xec\xa0\x81\xec\x8b\xa4\xec\x9d\xb4 \xec\x9e\x88\xec\x9c\xbc\xeb\xa9\xb0 \xeb\xb6\x80\xeb\x8c\x80\xec\x8b\x9c\xec\x84\xa4\xeb\xa1\x9c\xeb\x8a\x94 \xed\x8e\xb8\xec\x9d\x98\xec\xa0\x90\xea\xb3\xbc \xec\xbb\xa4\xed\x94\xbc\xec\xa0\x84\xeb\xac\xb8\xec\xa0\x90 \xeb\x93\xb1\xec\x9d\xb4 \xec\x9e\x88\xeb\x8b\xa4<span lang=\\"EN-US\\">. </span>\xec\xb2\xb4\xec\x9c\xa1\xea\xb4\x80 \xec\x84\x9c\xed\x8e\xb8\xec\x9c\xbc\xeb\xa1\x9c \xec\x9e\xa5\xec\xb6\xa9\xeb\x8b\xa8\xea\xb3\xb5\xec\x9b\x90\xec\x9d\xb4 \xec\x9e\x88\xec\x9c\xbc\xeb\xa9\xb0<span lang=\\"EN-US\\">, </span>\xeb\x82\xa8\xec\xaa\xbd\xec\x9c\xbc\xeb\xa1\x9c \xec\x8b\xa0\xeb\x9d\xbc\xed\x98\xb8\xed\x85\x94<span lang=\\"EN-US\\">, </span>\xeb\xb6\x81\xec\xaa\xbd\xec\x97\x90\xeb\x8a\x94 \xeb\x8f\x99\xed\x98\xb8\xeb\xa1\x9c\xea\xb0\x80 \xeb\x8f\x99\xeb\x82\xa8\xec\xaa\xbd\xec\x97\x90\xec\x84\x9c \xeb\xb6\x81\xec\x84\x9c\xec\xaa\xbd\xec\x9c\xbc\xeb\xa1\x9c \xec\x9c\x84\xec\xb9\x98\xed\x95\xb4 \xec\x9e\x88\xeb\x8b\xa4<span lang=\\"EN-US\\">.</span></p>\\r\\n<p class=\\"0\\">\xec\xb2\xb4\xec\x9c\xa1\xea\xb4\x80 \xec\x99\xb8\xeb\xb6\x80\xeb\x8a\x94 \xec\x9b\x90\xec\x9d\x98 \xed\x98\x95\xed\x83\x9c\xec\x9d\xb4\xea\xb3\xa0 \xeb\x8f\x94\xec\x9c\xbc\xeb\xa1\x9c \xeb\x90\x9c \xec\xa7\x80\xeb\xb6\x95\xec\x9d\x84 \xea\xb0\x80\xec\xa7\x80\xea\xb3\xa0 \xec\x9e\x88\xec\x9c\xbc\xeb\xa9\xb0 \xeb\x86\x92\xec\x9d\xb4\xeb\x8a\x94 <span lang=\\"EN-US\\">26.53m</span>\xec\x9d\xb4\xeb\x8b\xa4<span lang=\\"EN-US\\">. </span>\xec\xb2\xb4\xec\x9c\xa1\xea\xb4\x80 \xeb\x82\xb4\xeb\xb6\x80\xec\x9d\x98 \xec\x9b\x90\xed\x98\x95 \xec\xbd\x94\xed\x8a\xb8\xeb\x8a\x94 \xeb\xb0\xb0\xea\xb5\xac<span lang=\\"EN-US\\">, </span>\xeb\x86\x8d\xea\xb5\xac<span lang=\\"EN-US\\">, </span>\xed\x95\xb8\xeb\x93\x9c\xeb\xb3\xbc \xea\xb2\xbd\xea\xb8\xb0\xea\xb0\x80 \xea\xb0\x80\xeb\x8a\xa5\xed\x95\x98\xeb\xa9\xb0<span lang=\\"EN-US\\">, </span>\xec\xbd\x94\xed\x8a\xb8\xeb\xa5\xbc \xec\xa4\x91\xec\x8b\xac\xec\x9c\xbc\xeb\xa1\x9c \xeb\xb3\xb8\xeb\xb6\x80\xec\x84\x9d \xeb\xb0\x8f \xed\x95\x98\xeb\x8b\xa8 \xea\xb0\x80\xeb\xb3\x80 \xea\xb4\x80\xeb\x9e\x8c\xec\x84\x9d\xea\xb3\xbc \xec\x83\x81\xeb\x8b\xa8 \xea\xb4\x80\xeb\x9e\x8c\xec\x84\x9d\xec\x9d\xb4 \xec\x9c\x84\xec\xb9\x98\xed\x95\xb4\xec\x84\x9c \xec\xa4\x91\xec\x95\x99\xec\x9c\xbc\xeb\xa1\x9c \xec\x8b\x9c\xec\x84\xa0\xec\x9d\x84 \xec\xa7\x91\xec\xa4\x91\xec\x8b\x9c\xed\x82\xa4\xeb\xa9\xb0<span lang=\\"EN-US\\">, </span>\xea\xb0\x81 \xea\xb4\x80\xeb\x9e\x8c\xec\x84\x9d\xec\x9d\x98 \xec\x9c\x84\xec\xb9\x98\xec\x97\x90 \xeb\x94\xb0\xeb\xa5\xb8 \xec\x8b\x9c\xea\xb0\x81\xec\xa0\x81 \xec\x82\xac\xea\xb0\x81\xec\xa7\x80\xeb\x8c\x80\xeb\xa5\xbc \xeb\xa7\x8c\xeb\x93\xa4\xec\xa7\x80 \xec\x95\x8a\xeb\x8a\x94\xeb\x8b\xa4<span lang=\\"EN-US\\">.</span></p>","SUBWAY":"\xec\xa7\x80\xed\x95\x98\xec\xb2\xa0 3\xed\x98\xb8\xec\x84\xa0 \xeb\x8f\x99\xeb\x8c\x80\xec\x9e\x85\xea\xb5\xac\xec\x97\xad 5\xeb\xb2\x88\xec\xb6\x9c\xea\xb5\xac (\xec\xb2\xb4\xec\x9c\xa1\xea\xb4\x80 \xec\xa7\x81\xec\xa0\x91\xec\x97\xb0\xea\xb2\xb0)","BUS":"\xec\x9e\xa5\xec\xb6\xa9\xec\xb2\xb4\xec\x9c\xa1\xea\xb4\x80\xec\x95\x9e 02-201(\xec\x84\x9c\xec\x9a\xb8) N13, 144, 301, 7212 / \xec\x9e\xa5\xec\xb6\xa9\xec\xb2\xb4\xec\x9c\xa1\xea\xb4\x80\xec\x95\x9e 02-202(\xec\x84\x9c\xec\x9a\xb8) N13, 144, 301, 7212 / \xeb\x8f\x99\xeb\x8c\x80\xec\x9e\x85\xea\xb5\xac\xec\x97\xad.\xec\x9e\xa5\xec\xb6\xa9\xeb\x8f\x99 02-222(\xec\x84\x9c\xec\x9a\xb8) 05, 02, 03","PARKING_INFO":"\xec\xb2\xb4\xec\x9c\xa1\xea\xb4\x80 \xeb\xb6\x81\xec\xb8\xa1 \xeb\xb6\x80\xec\x84\xa4\xec\xa3\xbc\xec\xb0\xa8\xec\x9e\xa5 \xec\x9d\xb4\xec\x9a\xa9     * \xed\x96\x89\xec\x82\xac\xec\x8b\x9c \xec\x9d\xbc\xeb\xb0\x98\xec\xa3\xbc\xec\xb0\xa8 \xec\x97\x86\xec\x9d\x8c","REG_DATE":"2024-06-19 10:17:30.0","MOD_DATE":"2024-12-11 15:11:42.0"},{"NUM":3.0,"SUBJECT_CD":"\xea\xb3\xb5\xec\x9b\x90/\xea\xb4\x91\xec\x9e\xa5","TITLE":"\xec\x9a\xa9\xec\x96\x91\xeb\xb4\x89\xec\xa0\x80\xec\xa0\x95 \xea\xb3\xb5\xec\x9b\x90","ADDR":"\xec\x84\x9c\xec\x9a\xb8 \xeb\x8f\x99\xec\x9e\x91\xea\xb5\xac \xeb\xb3\xb8\xeb\x8f\x99 \xec\x82\xb0 3-9","LA":"37.5118003827004","LO":"126.958588093172","TEL_NO":"(\xea\xb3\xb5\xec\x9b\x90\xec\x95\x88\xeb\x82\xb4) 02-820-9258","URL":"","OPERATING_TIME":"\xec\x9a\xb4\xec\x98\x81 \xec\xa0\x9c\xed\x95\x9c \xec\x97\x86\xec\x9d\x8c","FREE_YN":"\xeb\xac\xb4\xeb\xa3\x8c","ENTR_FEE":"\xeb\xac\xb4\xeb\xa3\x8c","CONTENTS":"<p class=\\"0\\">\xec\x9a\xa9\xec\x96\x91\xeb\xb4\x89\xec\xa0\x80\xec\xa0\x95\xec\x9d\x80 \xec\xa1\xb0\xec\x84\xa0\xec\x8b\x9c\xeb\x8c\x80\xec\x97\x90 \xec\xa0\x95\xec\xa1\xb0\xec\x9e\x84\xea\xb8\x88\xec\x9d\xb4 \xec\x95\x84\xeb\xb2\x84\xec\xa7\x80 \xec\x82\xac\xeb\x8f\x84\xec\x84\xb8\xec\x9e\x90\xec\x9d\x98 \xeb\xac\x98\xea\xb0\x80 \xec\x9e\x88\xeb\x8a\x94 \xea\xb2\xbd\xea\xb8\xb0\xeb\x8f\x84 \xec\x88\x98\xec\x9b\x90\xed\x98\x84\xeb\xa5\xad\xec\x9b\x90 \xec\xb0\xb8\xeb\xb0\xb0\xea\xb8\xb8\xec\x97\x90 \xed\x95\x9c\xea\xb0\x95\xec\x9d\x84 \xea\xb1\xb4\xeb\x84\x8c \xed\x9b\x84<span lang=\\"EN-US\\">, </span>\xec\x9e\xa0\xec\x8b\x9c \xed\x9c\xb4\xec\x8b\x9d\xed\x95\x98\xea\xb8\xb0 \xec\x9c\x84\xed\x95\x98\xec\x97\xac \xec\x84\xb8\xec\x9a\xb4 \xed\x96\x89\xea\xb6\x81\xec\x9c\xbc\xeb\xa1\x9c <span lang=\\"EN-US\\">\\"</span>\xec\x9a\xa9\xec\x9d\xb4 \xeb\x9b\xb0\xeb\x86\x80\xea\xb3\xa0 \xeb\xb4\x89\xed\x99\xa9\xec\x9d\xb4 \xeb\x86\x92\xec\x9d\xb4 \xeb\x82\x9c\xeb\x8b\xa4<span lang=\\"EN-US\\">\\"</span>\xeb\x8a\x94 \xeb\x9c\xbb\xec\x9d\x84 \xea\xb0\x80\xec\xa1\x8c\xec\x9c\xbc\xeb\xa9\xb0 <span lang=\\"EN-US\\">1</span><span lang=\\"EN-US\\">972</span>\xeb\x85\x84 <span lang=\\"EN-US\\">5</span>\xec\x9b\x94 <span lang=\\"EN-US\\">25</span>\xec\x9d\xbc \xec\x84\x9c\xec\x9a\xb8\xed\x8a\xb9\xeb\xb3\x84\xec\x8b\x9c \xec\x9c\xa0\xed\x98\x95\xeb\xac\xb8\xed\x99\x94\xec\x9e\xac \xec\xa0\x9c<span lang=\\"EN-US\\">6</span>\xed\x98\xb8\xeb\xa1\x9c \xec\xa7\x80\xec\xa0\x95\xeb\x90\x98\xec\x97\x88\xec\x8a\xb5\xeb\x8b\x88\xeb\x8b\xa4<span lang=\\"EN-US\\">. </span>\xec\x9a\xa9\xec\x96\x91\xeb\xb4\x89\xec\xa0\x80\xec\xa0\x95\xec\x97\x90\xec\x84\x9c <span lang=\\"EN-US\\">5</span>\xeb\xb6\x84\xec\x9d\x84 \xec\x98\xac\xeb\x9d\xbc\xea\xb0\x80\xeb\xa9\xb4 \xeb\x82\x98\xec\x98\xa4\xeb\x8a\x94 \xec\x9a\xa9\xec\x96\x91\xeb\xb4\x89\xec\xa0\x80\xec\xa0\x95 \xea\xb3\xb5\xec\x9b\x90\xec\x9d\x98 \xec\xa0\x84\xeb\xa7\x9d\xeb\x8c\x80\xeb\x8a\x94 \xec\x84\x9c\xec\x9a\xb8\xec\x9d\x98 \xec\x95\xbc\xea\xb2\xbd\xec\x9d\xb4 \xed\x95\x9c \xeb\x88\x88\xec\x97\x90 \xeb\xb3\xb4\xec\x9d\xb4\xeb\x8a\x94 \xeb\xaa\x85\xec\x86\x8c\xeb\xa1\x9c \xec\x86\x90\xea\xbc\xbd\xed\x9e\x88\xea\xb3\xa0 \xec\x9e\x88\xeb\x8b\xa4<span lang=\\"EN-US\\">. </span></p>","SUBWAY":"9\xed\x98\xb8\xec\x84\xa0 \xeb\x85\xb8\xeb\x93\xa4\xec\x97\xad 3\xeb\xb2\x88 \xec\xb6\x9c\xea\xb5\xac \xeb\x8f\x84\xeb\xb3\xb4 20\xeb\xb6\x84","BUS":"\xeb\x8f\x99\xec\x9e\x91\xec\x8b\xa4\xeb\xb2\x84\xec\x84\xbc\xed\x84\xb0 \xec\xa0\x95\xeb\xa5\x98\xec\x9e\xa5, \xed\x9d\x91\xec\x84\x9d\xeb\x8f\x99\xed\x9a\xa8\xec\x82\xac\xec\xa0\x95 \xed\x95\x98\xec\xb0\xa8 \xeb\x8f\x84\xeb\xb3\xb4 5\xeb\xb6\x84","PARKING_INFO":"\xec\x9a\xa9\xec\x96\x91\xeb\xb4\x89\xec\xa0\x80\xec\xa0\x95\xea\xb3\xb5\xec\x9b\x90 \xec\xa3\xbc\xec\xb0\xa8\xec\x9e\xa5 \xeb\x8f\x84\xeb\xb3\xb4 5\xeb\xb6\x84","REG_DATE":"2024-06-19 11:15:52.0","MOD_DATE":"2024-12-11 15:12:55.0"},{"NUM":4.0,"SUBJECT_CD":"\xeb\xac\xb8\xed\x99\x94/\xec\xb2\xb4\xec\x9c\xa1","TITLE":"\xec\xb0\xbd\xea\xb2\xbd\xea\xb6\x81","ADDR":"\xec\x84\x9c\xec\x9a\xb8\xed\x8a\xb9\xeb\xb3\x84\xec\x8b\x9c \xec\xa2\x85\xeb\xa1\x9c\xea\xb5\xac \xec\xb0\xbd\xea\xb2\xbd\xea\xb6\x81\xeb\xa1\x9c 185","LA":"37.579412935392185","LO":"126.99522255388881","TEL_NO":"02-762-4868","URL":"https://royal.khs.go.kr/cgg","OPERATING_TIME":"\xed\x99\x94~\xec\x9d\xbc 09:00~21:00 * \xeb\xa7\xa4\xec\xa3\xbc \xec\x9b\x94\xec\x9a\x94\xec\x9d\xbc \xec\xa0\x95\xea\xb8\xb0\xed\x9c\xb4\xea\xb4\x80, \xea\xb3\x84\xec\xa0\x88\xeb\xb3\x84 \xec\x9a\xb4\xec\x98\x81\xec\x8b\x9c\xea\xb0\x84 \xec\x83\x81\xec\x9d\xb4","FREE_YN":"\xec\x9c\xa0\xeb\xa3\x8c","ENTR_FEE":"\xec\x9c\xa0\xeb\xa3\x8c \xeb\x8c\x80\xec\x9d\xb8 1,000\xec\x9b\x90, \xed\x95\x9c\xeb\xb3\xb5\xec\xb0\xa9\xec\x9a\xa9\xec\x9e\x90 \xeb\xac\xb4\xeb\xa3\x8c","CONTENTS":"<p>\xec\xb0\xbd\xea\xb2\xbd\xea\xb6\x81(\xe6\x98\x8c\xe6\x85\xb6\xe5\xae\xae)\xec\x9d\x80 \xec\x84\xb1\xec\xa2\x85\xec\x9d\xb4 \xec\x84\xb8 \xeb\xaa\x85\xec\x9d\x98 \xeb\x8c\x80\xeb\xb9\x84\xeb\xa5\xbc \xec\x9c\x84\xed\x95\xb4 \xec\x98\x9b \xec\x88\x98\xea\xb0\x95\xea\xb6\x81\xec\x97\x90 \xec\xb0\xbd\xea\xb1\xb4\xed\x95\x9c \xea\xb6\x81\xec\x9d\xb4\xeb\x8b\xa4.</p>\\r\\n<p>&nbsp;</p>\\r\\n<p>\xec\xb0\xbd\xea\xb2\xbd\xea\xb6\x81\xec\x9d\x80 \xec\x9b\x90\xeb\x9e\x98 1418\xeb\x85\x84(\xec\x84\xb8\xec\xa2\x85 \xec\xa6\x89\xec\x9c\x84) \xec\x84\xb8\xec\xa2\x85\xec\x9d\xb4 \xec\x83\x81\xec\x99\x95 \xed\x83\x9c\xec\xa2\x85\xec\x9d\x84 \xec\x9c\x84\xed\x95\xb4 \xec\xb0\xbd\xea\xb1\xb4\xed\x95\x9c \xec\x88\x98\xea\xb0\x95\xea\xb6\x81(\xe5\xa3\xbd\xe5\xba\xb7\xe5\xae\xae)\xec\x9d\xb4 \xec\x9e\x88\xeb\x8d\x98 \xec\x9e\x90\xeb\xa6\xac\xec\x9d\xb4\xeb\x8b\xa4. \xec\x9d\xb4\xed\x9b\x84 1483\xeb\x85\x84(\xec\x84\xb1\xec\xa2\x85 14) \xec\x84\xb1\xec\xa2\x85\xec\x9d\xb4 \xec\x84\xb8 \xeb\xaa\x85\xec\x9d\x98 \xeb\x8c\x80\xeb\xb9\x84(\xec\x84\xb8\xec\xa1\xb0\xec\x9d\x98 \xec\x99\x95\xeb\xb9\x84 \xec\xa0\x95\xed\x9d\xac\xec\x99\x95\xed\x9b\x84, \xeb\x8d\x95\xec\xa2\x85\xec\x9d\x98 \xec\x99\x95\xeb\xb9\x84 \xec\x86\x8c\xed\x98\x9c\xec\x99\x95\xed\x9b\x84, \xec\x98\x88\xec\xa2\x85\xec\x9d\x98 \xec\x99\x95\xeb\xb9\x84 \xec\x95\x88\xec\x88\x9c\xec\x99\x95\xed\x9b\x84)\xeb\xa5\xbc \xec\x9c\x84\xed\x95\xb4 \xec\x88\x98\xea\xb0\x95\xea\xb6\x81\xec\x9d\x84 \xed\x81\xac\xea\xb2\x8c \xed\x99\x95\xec\x9e\xa5\xed\x95\x98\xea\xb3\xa0 \xea\xb6\x81\xec\x9d\x98 \xec\x9d\xb4\xeb\xa6\x84\xec\x9d\x84 \xec\xb0\xbd\xea\xb2\xbd\xea\xb6\x81\xec\x9d\xb4\xeb\x9d\xbc \xed\x95\x98\xec\x98\x80\xeb\x8b\xa4. \xec\xb0\xbd\xea\xb2\xbd\xea\xb6\x81\xec\x9d\x80 \xec\xb0\xbd\xeb\x8d\x95\xea\xb6\x81\xea\xb3\xbc \xea\xb2\xbd\xea\xb3\x84 \xec\x97\x86\xec\x9d\xb4 \xeb\x8f\x99\xea\xb6\x90(\xe6\x9d\xb1\xe9\x97\x95)\xec\x9d\xb4\xeb\x9d\xbc\xeb\x8a\x94 \xed\x95\x98\xeb\x82\x98\xec\x9d\x98 \xea\xb6\x81\xea\xb6\x90 \xec\x98\x81\xec\x97\xad\xec\x9d\xb4\xec\x97\x88\xec\x9c\xbc\xeb\xa9\xb0 \xec\xa3\xbc\xeb\xa1\x9c \xec\x99\x95\xec\x8b\xa4 \xea\xb0\x80\xec\xa1\xb1\xeb\x93\xa4\xec\x9d\x98 \xec\x83\x9d\xed\x99\x9c \xea\xb3\xb5\xea\xb0\x84\xec\x9c\xbc\xeb\xa1\x9c \xec\x82\xac\xec\x9a\xa9\xed\x95\x98\xec\x98\x80\xeb\x8b\xa4. \xec\xb0\xbd\xea\xb2\xbd\xea\xb6\x81\xec\x9d\x80 1592\xeb\x85\x84(\xec\x84\xa0\xec\xa1\xb0 25) \xec\x9e\x84\xec\xa7\x84\xec\x99\x9c\xeb\x9e\x80\xec\x9c\xbc\xeb\xa1\x9c \xec\x86\x8c\xec\x8b\xa4\xeb\x90\x9c \xea\xb2\x83\xec\x9d\x84 1616\xeb\x85\x84(\xea\xb4\x91\xed\x95\xb4\xea\xb5\xb0 8) \xec\xa4\x91\xea\xb1\xb4\xed\x95\x98\xec\x98\x80\xec\x9c\xbc\xeb\xa9\xb0, 1830\xeb\x85\x84(\xec\x88\x9c\xec\xa1\xb0 30) \xeb\x8c\x80\xed\x99\x94\xec\x9e\xac\xeb\xa1\x9c \xeb\x8c\x80\xeb\xb6\x80\xeb\xb6\x84\xec\x9d\x98 \xea\xb1\xb4\xeb\xac\xbc\xeb\x93\xa4\xec\x9d\xb4 \xec\x86\x8c\xec\x8b\xa4\xeb\x90\x98\xec\x97\x88\xeb\x8b\xa4\xea\xb0\x80 4\xeb\x85\x84 \xeb\x92\xa4\xec\x97\x90 \xec\xa4\x91\xea\xb1\xb4\xed\x95\x98\xec\x98\x80\xeb\x8b\xa4.</p>\\r\\n<p>&nbsp;</p>\\r\\n<p>\xea\xb7\xb8\xeb\x9f\xac\xeb\x82\x98 1907\xeb\x85\x84 \xec\x88\x9c\xec\xa2\x85\xec\x9d\xb4 \xed\x99\xa9\xec\x9c\x84\xec\x97\x90 \xec\x98\xa4\xeb\xa5\xb8 \xed\x9b\x84 \xec\xb0\xbd\xea\xb2\xbd\xea\xb6\x81 \xeb\x82\xb4\xec\x97

In [30]:
data = response.json()
data

{'viewNightSpot': {'list_total_count': 51,
  'RESULT': {'CODE': 'INFO-000', 'MESSAGE': '정상 처리되었습니다'},
  'row': [{'NUM': 1.0,
    'SUBJECT_CD': '문화/체육',
    'TITLE': '남산서울타워',
    'ADDR': '서울특별시 용산구 남산공원길 105',
    'LA': '37.5511225714939',
    'LO': '126.987867837993',
    'TEL_NO': '02-3455-9277, 9288',
    'URL': 'https://www.seoultower.co.kr/',
    'OPERATING_TIME': '연중무휴 * 타워내 개별시설 운영시간 상이',
    'FREE_YN': '무료',
    'ENTR_FEE': '남산공원 입장료 없음(전망대 등 개별 이용시설 요금 별도)',
    'CONTENTS': '<p>남산서울타워는 효율적인 방송전파 송수신과 한국의 전통미를 살린 관광 전망시설의 기능을 겸비한 국내 최초의 종합전파 탑으로 방송문화와 관광산업의 미래를 위해 건립되었습니다.</p>\r\n<p>세계 유명한 종합 탑들이 그 나라 또는 그 도시의 상징적인 존재가 된 것처럼 남산서울타워 역시 지난 40여 년간 대한민국의 대표적인 관광지이자 서울의 상징물 역할을 해왔습니다.</p>\r\n<p>남산서울타워는 서울 시내 전 지역에서 바라보이는 탑의 높이와 독특한 구조, 형태 등으로 인하여 시민의 관심과 사랑의 대상이 되었고, 내외국인들이 즐겨 찾는 제1의 관광 명소로서의 위치를 확고히 하고 있습니다. 최근에는 한류 바람을 몰고 온 각종 예능, 드라마의 촬영지로 이름이 높아지면서 내외국인 관광객들이 발길이 끊이지 않는 곳입니다.</p>\r\n<p>(출처 : 남산서울타워 홈페이지)</p>\r\n<p>전망대 뿐만 아니라 남산공원에서 산책하면서, 남산케이블카를 이용하면서, 남산둘레길 트레킹하면서 서울의 야경도 다양하게 감상할 수 있습니다.</p>',
    'SUBWAY': '지하철 4호선 회현역 3번 출구 도보 이용',
    'BUS': '남산순환버스 01A번, 01B번 이용  * 남산공원 생태 환경 보호 일환으로 승용차량 통행 제한',
    'PARKING_INFO': '',
    'REG_DATE': '2024-06-05 00:00:00.0',
    'MOD_DATE': '2024-06-24 16:59:59.0'},
   {'NUM': 2.0,
    'SUBJECT_CD': '문화/체육',
    'TITLE': '장충체육관',
    'ADDR': '서울특별시 중구 동호로 241',
    'LA': '37.5586406607183',
    'LO': '127.006677513121',
    'TEL_NO': '(안내) 02-2128-2800',
    'URL': 'http://www.sisul.or.kr/open_content/jangchung/',
    'OPERATING_TIME': '평일 : 9:00 ~18:00 / 주말 : 경기 또는 행사시 운영시간에 따라 상이',
    'FREE_YN': '유료',
    'ENTR_FEE': '경기·행사 시마다 상이',
    'CONTENTS': '<p class="0"><span lang="EN-US">1963</span>년 <span lang="EN-US">2</span>월 <span lang="EN-US">1</span>일에 개장한 국내 최초의 실내체육관으로서 서울 중구 장충동에 위치하고 있으며 지하<span lang="EN-US">2</span>층<span lang="EN-US">, </span>지상<span lang="EN-US">3</span>층<span lang="EN-US">, </span>연면적 <span lang="EN-US">11,399.2</span>㎡<span lang="EN-US">, </span>관람석은 <span lang="EN-US">4,507</span>석이다<span lang="EN-US">.</span></p>\r\n<p class="0">주요시설로는 주체육관과 보조체육관<span lang="EN-US">, </span>다목적실이 있으며 부대시설로는 편의점과 커피전문점 등이 있다<span lang="EN-US">. </span>체육관 서편으로 장충단공원이 있으며<span lang="EN-US">, </span>남쪽으로 신라호텔<span lang="EN-US">, </span>북쪽에는 동호로가 동남쪽에서 북서쪽으로 위치해 있다<span lang="EN-US">.</span></p>\r\n<p class="0">체육관 외부는 원의 형태이고 돔으로 된 지붕을 가지고 있으며 높이는 <span lang="EN-US">26.53m</span>이다<span lang="EN-US">. </span>체육관 내부의 원형 코트는 배구<span lang="EN-US">, </span>농구<span lang="EN-US">, </span>핸드볼 경기가 가능하며<span lang="EN-US">, </span>코트를 중심으로 본부석 및 하단 가변 관람석과 상단 관람석이 위치해서 중앙으로 시선을 집중시키며<span lang="EN-US">, </span>각 관람석의 위치에 따른 시각적 사각지대를 만들지 않는다<span lang="EN-US">.</span></p>',
    'SUBWAY': '지하철 3호선 동대입구역 5번출구 (체육관 직접연결)',
    'BUS': '장충체육관앞 02-201(서울) N13, 144, 301, 7212 / 장충체육관앞 02-202(서울) N13, 144, 301, 7212 / 동대입구역.장충동 02-222(서울) 05, 02, 03',
    'PARKING_INFO': '체육관 북측 부설주차장 이용     * 행사시 일반주차 없음',
    'REG_DATE': '2024-06-19 10:17:30.0',
    'MOD_DATE': '2024-12-11 15:11:42.0'},
   {'NUM': 3.0,
    'SUBJECT_CD': '공원/광장',
    'TITLE': '용양봉저정 공원',
    'ADDR': '서울 동작구 본동 산 3-9',
    'LA': '37.5118003827004',
    'LO': '126.958588093172',
    'TEL_NO': '(공원안내) 02-820-9258',
    'URL': '',
    'OPERATING_TIME': '운영 제한 없음',
    'FREE_YN': '무료',
    'ENTR_FEE': '무료',
    'CONTENTS': '<p class="0">용양봉저정은 조선시대에 정조임금이 아버지 사도세자의 묘가 있는 경기도 수원현륭원 참배길에 한강을 건넌 후<span lang="EN-US">, </span>잠시 휴식하기 위하여 세운 행궁으로 <span lang="EN-US">"</span>용이 뛰놀고 봉황이 높이 난다<span lang="EN-US">"</span>는 뜻을 가졌으며 <span lang="EN-US">1</span><span lang="EN-US">972</span>년 <span lang="EN-US">5</span>월 <span lang="EN-US">25</span>일 서울특별시 유형문화재 제<span lang="EN-US">6</span>호로 지정되었습니다<span lang="EN-US">. </span>용양봉저정에서 <span lang="EN-US">5</span>분을 올라가면 나오는 용양봉저정 공원의 전망대는 서울의 야경이 한 눈에 보이는 명소로 손꼽히고 있다<span lang="EN-US">. </span></p>',
    'SUBWAY': '9호선 노들역 3번 출구 도보 20분',
    'BUS': '동작실버센터 정류장, 흑석동효사정 하차 도보 5분',
    'PARKING_INFO': '용양봉저정공원 주차장 도보 5분',
    'REG_DATE': '2024-06-19 11:15:52.0',
    'MOD_DATE': '2024-12-11 15:12:55.0'},
   {'NUM': 4.0,
    'SUBJECT_CD': '문화/체육',
    'TITLE': '창경궁',
    'ADDR': '서울특별시 종로구 창경궁로 185',
    'LA': '37.579412935392185',
    'LO': '126.99522255388881',
    'TEL_NO': '02-762-4868',
    'URL': 'https://royal.khs.go.kr/cgg',
    'OPERATING_TIME': '화~일 09:00~21:00 * 매주 월요일 정기휴관, 계절별 운영시간 상이',
    'FREE_YN': '유료',
    'ENTR_FEE': '유료 대인 1,000원, 한복착용자 무료',
    'CONTENTS': '<p>창경궁(昌慶宮)은 성종이 세 명의 대비를 위해 옛 수강궁에 창건한 궁이다.</p>\r\n<p>&nbsp;</p>\r\n<p>창경궁은 원래 1418년(세종 즉위) 세종이 상왕 태종을 위해 창건한 수강궁(壽康宮)이 있던 자리이다. 이후 1483년(성종 14) 성종이 세 명의 대비(세조의 왕비 정희왕후, 덕종의 왕비 소혜왕후, 예종의 왕비 안순왕후)를 위해 수강궁을 크게 확장하고 궁의 이름을 창경궁이라 하였다. 창경궁은 창덕궁과 경계 없이 동궐(東闕)이라는 하나의 궁궐 영역이었으며 주로 왕실 가족들의 생활 공간으로 사용하였다. 창경궁은 1592년(선조 25) 임진왜란으로 소실된 것을 1616년(광해군 8) 중건하였으며, 1830년(순조 30) 대화재로 대부분의 건물들이 소실되었다가 4년 뒤에 중건하였다.</p>\r\n<p>&nbsp;</p>\r\n<p>그러나 1907년 순종이 황위에 오른 후 창경궁 내에 동물원과 식물원을 조성하면서 궁궐로서의 모습을 잃기 시작하였다. 1911년에는 일제에 의해 궁의 이름마저 창경원(昌慶苑)으로 격하되어 궁궐이 아닌 공원화가 되어 훼손이 심하였다. 광복 후 1983년에 다시 창경궁으로 명칭을 회복한 후, 궁궐 경내에 있던 동물원을 이전하고 본래 궁궐의 모습으로 복원공사가 진행되어 현재의 모습이 되었다. 창경궁은 남향으로 있는 다른 궁궐과 달리 정문과 정전이 동향으로 배치되어 있다.</p>\r\n<p>(출처 : 문화재청 궁능유적본부)</p>',
    'SUBWAY': '지하철 4호선 혜화역 4번 출구 도보 이용',
    'BUS': '창경궁 정류장 하차 도보 이용',
    'PARKING_INFO': '',
    'REG_DATE': '2024-06-12 20:44:00.0',
    'MOD_DATE': '2024-06-27 17:32:26.0'},
   {'NUM': 5.0,
    'SUBJECT_CD': '공원/광장',
    'TITLE': '서울어린이대공원 내 서울상상나라',
    'ADDR': '서울특별시 광진구 능동로 216',
    'LA': '37.5520117940291',
    'LO': '127.078770241307',
    'TEL_NO': '02-450-9311',
    'URL': 'https://www.sisul.or.kr/open_content/childrenpark/',
    'OPERATING_TIME': '5:00~22:00 (연중무휴)',
    'FREE_YN': '무료',
    'ENTR_FEE': '무료',
    'CONTENTS': '<p class="0">서울어린이대공원 능동문 앞에 위치한 서울상상나라와 원형광장은</p>\r\n<p class="0">아이들을 위한 시설로서 주간엔 놀이를 통해 체험하고 배울 수 있는 공간으로 활용되며 외부에 위치한 원형광장에선 원형벤치 안과 밖을 뛰놀며 즐기며 쉴 수 있는 공간으로 조성되어 있다<span lang="EN-US">.</span></p>\r\n<p class="0"><!-- [if !supportEmptyParas]-->&nbsp;<!--[endif]--></p>\r\n<p class="0">저녁 밤이 찾아오면 공원 나들이객을 위한 새로운 모습으로 변모한다<span lang="EN-US">. </span></p>\r\n<p class="0">능동문을 지나 공원에 발을 딛는 순간 밤하늘을 수놓은 별자리 테마의 거대한 조명 벽화를 마주치게 되는데<span lang="EN-US">, </span>공원을 방문한 아이들도<span lang="EN-US">, </span>연인들도</p>\r\n<p class="0">편히 원형 벤치에 앉아 한결 더 공원의 매력을 느껴볼 수 있을 것이다<span lang="EN-US">.</span></p>\r\n<p class="0"><!-- [if !supportEmptyParas]-->&nbsp;<!--[endif]--></p>\r\n<p class="0">외벽을 수놓을 경관조명은 일몰시부터 <span lang="EN-US">22</span>시까지 운영될 계획이다<span lang="EN-US">.</span></p>',
    'SUBWAY': '7호선 어린이대공원역 1번출구',
    'BUS': '‘세종대학교’ 정류소 하차',
    'PARKING_INFO': '운영시간 05:00 - 22:00',
    'REG_DATE': '2024-06-19 10:49:45.0',
    'MOD_DATE': '2024-12-11 15:15:22.0'},
   {'NUM': 6.0,
    'SUBJECT_CD': '문화/체육',
    'TITLE': '창덕궁',
    'ADDR': '서울특별시 종로구 율곡로 99',
    'LA': '37.57950279094907',
    'LO': '126.99103378705136',
    'TEL_NO': '02-3668-2300',
    'URL': 'https://royal.cha.go.kr/cdg',
    'OPERATING_TIME': '화~일 09:00~18:00 * 매주 월요일 정기휴관, 계절별 운영시간 상이',
    'FREE_YN': '유료',
    'ENTR_FEE': '대인 3,000원, 한복착용자 무료',
    'CONTENTS': '<p class="0">창덕궁<span lang="EN-US">(</span>昌德宮<span lang="EN-US">)</span>은 자연과 조화를 이룬 가장 한국적인 궁으로<span lang="EN-US">&nbsp;</span>유네스코 세계유산으로 등재된 궁이다<span lang="EN-US">.</span></p>\r\n<p class="0"><!-- [if !supportEmptyParas]-->&nbsp;<!--[endif]--></p>\r\n<p class="0">창덕궁<span lang="EN-US">(</span>昌德宮<span lang="EN-US">)</span>은 <span lang="EN-US">1405</span>년<span lang="EN-US">(</span>태종 <span lang="EN-US">5) </span>법궁인 경복궁의 이궁<span lang="EN-US">(</span>離宮<span lang="EN-US">)</span>으로 창건되었다<span lang="EN-US">. 1592</span>년<span lang="EN-US">(</span>선조 <span lang="EN-US">25) </span>임진왜란으로 소실되었다가 <span lang="EN-US">1610</span>년<span lang="EN-US">(</span>광해군 <span lang="EN-US">2) </span>궁궐 중 처음으로 다시 지어졌으며<span lang="EN-US">, </span>이후 역대 왕들이 <span lang="EN-US">1867</span>년 경복궁이 중건될 때까지 약 <span lang="EN-US">270</span>여년 동안 창덕궁을 더 많이 사용하여 실질적인 법궁의 역할을 하였다<span lang="EN-US">. </span>특히 대조전 부속 건물인 흥복헌은 <span lang="EN-US">1910</span>년 경술국치가 결정되었던 비운의 장소이기도 하며<span lang="EN-US">, </span>낙선재 권역은 광복 이후 대한제국의 마지막 황실 가족<span lang="EN-US">(</span>순정황후<span lang="EN-US">(</span>순종 두 번째 황후<span lang="EN-US">), </span>의민황태자비<span lang="EN-US">(</span>이방자 여사<span lang="EN-US">), </span>덕혜옹주<span lang="EN-US">(</span>고종의 딸<span lang="EN-US">))</span>이 생활하다가 세상을 떠난 곳이기도 하다<span lang="EN-US">.</span></p>\r\n<p class="0"><!-- [if !supportEmptyParas]-->&nbsp;<!--[endif]--></p>\r\n<p class="0">후원은 <span lang="EN-US">1406</span>년<span lang="EN-US">(</span>태종 <span lang="EN-US">6) </span>창덕궁 북쪽에 처음 조성되었고 <span lang="EN-US">1463</span>년<span lang="EN-US">(</span>세조 <span lang="EN-US">9) </span>확장되었다가 임진왜란 때 소실되었다<span lang="EN-US">. </span>이후 인조 대부터 순조 대까지 옥류천<span lang="EN-US">, </span>규장각<span lang="EN-US">, </span>주합루<span lang="EN-US">, </span>애련지<span lang="EN-US">, </span>의두합<span lang="EN-US">, </span>연경당 등이 추가로 조성되면서 창덕궁은 정치의 공간과 더불어 휴식과 생활의 공간이 조화를 이루었다<span lang="EN-US">.&nbsp;</span></p>\r\n<p class="0"><!-- [if !supportEmptyParas]-->&nbsp;<!--[endif]--></p>\r\n<p class="0">창덕궁은 창경궁<span lang="EN-US">(</span>昌慶宮<span lang="EN-US">)</span>과 경계 없이 <span lang="EN-US">&lsquo;</span>동궐<span lang="EN-US">(</span>東闕<span lang="EN-US">)&rsquo;</span>이라는 별칭으로 불렀다<span lang="EN-US">. </span>창덕궁은 다른 궁궐에 비해 인위적인 구조를 따르지 않고 주변 지형과 조화를 이루도록 자연스럽게 건축하여 가장 한국적인 궁궐이라는 평가를 받아 <span lang="EN-US">1997</span>년 유네스코 세계유산에 등재되었다</p>\r\n<p class="0"><span lang="EN-US">(</span>출처 <span lang="EN-US">: </span>문화재청 궁능유적본부 홈페이지<span lang="EN-US">)</span></p>',
    'SUBWAY': '지하철 1호선 종로3가역 6번 출구 도보 이용',
    'BUS': '창덕궁 정류장 하차 도보 이용',
    'PARKING_INFO': '',
    'REG_DATE': '2024-06-12 20:43:24.0',
    'MOD_DATE': '2024-12-11 15:18:46.0'},
   {'NUM': 7.0,
    'SUBJECT_CD': '공공시설',
    'TITLE': '여의도한강공원 물빛광장',
    'ADDR': '서울 영등포구 여의도동 84-9',
    'LA': '37.5312466908117',
    'LO': '126.928686496763',
    'TEL_NO': '여의도안내센터 02-3780-0566, 총괄 담당 02-3780-0652',
    'URL': ' https://hangang.seoul.go.kr/www/contents/861.do?mid=854',
    'OPERATING_TIME': '성수기(7~8월), (정각 마다 30분) 12:00 ~ 21:00(10회), 비수기(4~6월, 9~10월) (매회 30분) 12:00, 17:00, 18:00, 19:00, 20:00(5회) ',
    'FREE_YN': '무료',
    'ENTR_FEE': '',
    'CONTENTS': '<p><span style="font-size: 14pt;">여의도 물빛광장분수는 여의도 공원에서 한강으로 통하는 길목에 위치한 서울시를 대표하는 물놀이형 수경시설입니다. 지형을 이용하여 물의 흐름을 시청각화하여 다양한 볼거리 및 체험을 할 수 있는 공간으로 조성되었습니다.</span></p>\r\n<p><span style="font-size: 14pt;">야간 경관조명은 물속 바닥을 비추어 별빛을 형상화하였고 물소리를 듣고 느끼고 만지며 바라볼 수 있는 친수공간으로 각광받고 있습니다.</span></p>\r\n<p>&nbsp;</p>\r\n<p><span style="font-size: 14pt;">시설규모는 40m X 196m에 수심15cm로 도심 속에서 자연과 물의 아름다움을 느끼고 각종 공연과 한강조망을 한눈에 볼 수 있는 가족나들이 장소입니다.</span></p>\r\n<p>&nbsp;</p>\r\n<p><span style="font-size: 14pt;">가족, 친구들과 함께 도심 속에서 많은 추억을 만들어가시기 바랍니다.</span></p>',
    'SUBWAY': '지하철 5호선 여의나루역 1번, 2번 출구 도보 이용',
    'BUS': '여의도 순복음교회 앞 / 여의도공원 앞 버스정류장 하차 도보 이용',
    'PARKING_INFO': '',
    'REG_DATE': '2024-06-12 20:46:18.0',
    'MOD_DATE': '2024-06-26 14:08:03.0'},
   {'NUM': 8.0,
    'SUBJECT_CD': '공공시설',
    'TITLE': '뚝섬 자벌레(한강이야기전시관)',
    'ADDR': '서울특별시 광진구 강변북로 2202',
    'LA': '37.5308773153076',
    'LO': '127.065983191885',
    'TEL_NO': '02-3780-0517',
    'URL': 'http://www.j-bug.co.kr',
    'OPERATING_TIME': '월요일 휴관 / 화~금 9:00~18:00 / 토~일 9:00~20:00',
    'FREE_YN': '무료',
    'ENTR_FEE': '',
    'CONTENTS': '<p>한강이야기전시관은 한강의 역사와 문화적 가치를 일상에서 누리고 체험할 수 있는 오직 한강만을 주제로 한 유일한 전시관입니다.</p>',
    'SUBWAY': '지하철 2호선 자양(뚝섬한강공원)역 3번출구',
    'BUS': '노유나들목 앞 정류장 2014, 자양나들목 앞 정류장 2221, 2222, 2415',
    'PARKING_INFO': '뚝섬한강공원 주차장',
    'REG_DATE': '2024-06-12 20:48:19.0',
    'MOD_DATE': '2024-06-27 17:32:00.0'},
   {'NUM': 9.0,
    'SUBJECT_CD': '공원/광장',
    'TITLE': '청계천',
    'ADDR': '서울 중구 태평로 1가 1',
    'LA': '37.56915554121704',
    'LO': '126.97871950992457',
    'TEL_NO': '02-2290-7111~3(청계천종합상황실)',
    'URL': 'https://www.sisul.or.kr/open_content/cheonggye/',
    'OPERATING_TIME': '24시간 연중무휴(강우예보 및 우천시 출입통졔)',
    'FREE_YN': '무료',
    'ENTR_FEE': '무료',
    'CONTENTS': '<p>도심 속에 자리 잡은 청계천은 2005. 10. 1 개장, 매년 천만 명 이상의 시민과 관광객이 다녀가는 세계적인 명소로 자리매김하였습니다.</p>\r\n<p>&nbsp;</p>\r\n<p>청계광장을 중심으로 한 각종 문화행사와, 청계천 전역에 고루 분포된 다양한 동&middot;식물들을 만나면서 즐겁고 유쾌한 경험을 나누시기 바랍니다.</p>\r\n<p>&nbsp;</p>',
    'SUBWAY': '지하철 5호선 광화문역 5번출구에서 약 60m 이동 / 지하철 1, 2호선 시청역 4번출구에서 약 300m 이동',
    'BUS': '시청.서울신문사(02137, 02706) 하차 / 간선 : 101,150,501,506,708 / 지선 : 1711,7016 / 순환 : 01A',
    'PARKING_INFO': '청계광장에는 별도의 주차장이 없습니다. 대중교통이나 인근 주차장을 이용하여 주시기 바랍니다.',
    'REG_DATE': '2024-06-12 20:35:59.0',
    'MOD_DATE': '2024-07-02 09:19:05.0'},
   {'NUM': 10.0,
    'SUBJECT_CD': '공공시설',
    'TITLE': '성수대교',
    'ADDR': '서울 성동구 옥수동 484',
    'LA': '37.53617802719353',
    'LO': '127.03489368057885',
    'TEL_NO': '02-120',
    'URL': '',
    'OPERATING_TIME': '일몰 30분후 점등 ~ 23:00 소등',
    'FREE_YN': '무료',
    'ENTR_FEE': '',
    'CONTENTS': '<p>성수대교는 성동구 성수동과 강남구 압구정동을 연결하는 한강교량입니다. 총 길이는 1,160m이고 왕복 8차로 규모입니다. 구조물의 외관에 대한 고려가 이루어진 최초의 다리로 구조상 게르버 트러스트교로 하부경관이 넓어 한강수면에 경관을 이룹니다.</p>\r\n<p>성수대교 경관 조명은 비상하는 색채와 무한한 가능성을 표현하였습니다. 성수대교는 붕괴와 재시공을 통해 더욱더 아름다운 다리로 변신했습니다.</p>\r\n<p>(출처 : 서울시 및 미래한강본부, 정보소통광장 홈페이지)</p>',
    'SUBWAY': '(북단) 지하철 2호선 뚝섬역 8번출구 도보 이용, (남단) 지하철 3호선 압구정역 1번출구 도보 이용',
    'BUS': '(북단) 버스정류장 뚝섬서울숲 정류장 하차 후 도보 이용, (남단) 압구정중고등학교 정류장 하차 후 도보 이용',
    'PARKING_INFO': '',
    'REG_DATE': '2024-06-12 20:36:47.0',
    'MOD_DATE': '2024-06-27 17:31:17.0'},
   {'NUM': 17.0,
    'SUBJECT_CD': '공원/광장',
    'TITLE': '문화비축기지',
    'ADDR': '서울특별시 마포구 증산로 87',
    'LA': '37.5703466887615',
    'LO': '126.895031420115',
    'TEL_NO': ' 02-376-8410',
    'URL': 'https://parks.seoul.go.kr/template/sub/culturetank.do',
    'OPERATING_TIME': '야외공원 24시간 개방, 탱크 T1~T6 화~일요일 10:00~18:00 (월요일 휴관)',
    'FREE_YN': '무료',
    'ENTR_FEE': '',
    'CONTENTS': '<p>[석유에서 문화로(Oil to Culture)]</p>\r\n<p>마포구 서울월드컵경기장 인근 매봉산에 에워싸인 문화비축기지는 일반인의 접근과 이용이 철저히 통제됐던 산업화시대 유산인 마포 석유비축기지가 도시재생을 통해 시민 품으로 돌아오게 된 문화공원입니다.</p>\r\n<p>&nbsp;</p>\r\n<p>석유를 보관하던 탱크들은 석유 대신 매일 색다른 문화를 창출하는 문화탱크로 역할이 바뀌었습니다. 기존 5개의 탱크는 열린 문화 공간으로 탈바꿈하였고, 해체된 탱크의 철판을 활용해 만들어진 T6는 시민들의 커뮤니티 공간이 됐습니다. 비어있던 야외 공간은 아이들이 뛰어놀 수 있는 문화 마당으로 만들었습니다. 부지에 남아있던 수림은 최대한 보존하고 다양한 종류의 꽃과 나무를 심어 공원으로 조성했습니다. 매봉산으로 이어지는 산책로에서는 종종 산토끼와 청설모도 만날 수 있습니다.</p>',
    'SUBWAY': '6호선 월드컵경기장역 2·3번 출구에서 도보 10분',
    'BUS': '문화비축기지 정류장 하차 도보 이용',
    'PARKING_INFO': '',
    'REG_DATE': '2024-06-12 20:38:32.0',
    'MOD_DATE': '2024-10-29 19:19:38.0'},
   {'NUM': 11.0,
    'SUBJECT_CD': '공공시설',
    'TITLE': '마포대교',
    'ADDR': '서울 영등포구 여의도동 85-2',
    'LA': '37.5324287051867',
    'LO': '126.935734355376',
    'TEL_NO': '(경관조명 안내) 02-300-8404 (마포대교 안내) 02-2133-1978',
    'URL': '',
    'OPERATING_TIME': '일몰 30분후 점등 ~ 23:00 소등',
    'FREE_YN': '무료',
    'ENTR_FEE': '무료',
    'CONTENTS': '<p class="0">마포대교는 마포구 용강동과 영등포구 여의도동을 연결하는 한강교량입니다<span lang="EN-US">. </span>총 길이는 <span lang="EN-US">1,390m</span>이고 왕복 <span lang="EN-US">10</span>차로의 규모입니다<span lang="EN-US">. </span></p>\r\n<p class="0"><span lang="EN-US">(</span>출처 <span lang="EN-US">: </span>서울시 홈페이지 한강교량 현황<span lang="EN-US">)</span></p>\r\n<p class="0"><!-- [if !supportEmptyParas]-->&nbsp;<!--[endif]--></p>\r\n<p class="0">마포대교 경관 조명은 <span lang="EN-US">\'</span>따스한 빛을 품은 위로와 치유<span lang="EN-US">\'</span>를 테마로 밝고 따뜻한 느낌을 주는 <span lang="EN-US">\'</span>온백색<span lang="EN-US">\'</span>을 주조색으로 사용합니다<span lang="EN-US">. </span>강변북로와 올림픽대로 등 주변 도로에서도 잘 보일 수 있게 시인성 높고 선명한 <span lang="EN-US">LED(</span>발광다이오드<span lang="EN-US">)</span>조명을 사용하고<span lang="EN-US">, </span>여의도 한강공원 조명색과 유사한 색을 활용해 주변과 조화를 이루도록 했습니다<span lang="EN-US">.</span></p>\r\n<p class="0"><span lang="EN-US">(</span>출처 <span lang="EN-US">: </span>서울시 내손안에 서울 홈페이지 및 언론 보도자료<span lang="EN-US">(&lsquo;21. 06.))</span></p>',
    'SUBWAY': '북단) 지하철 5호선 마포역 1,4번출구 도보 15분 / (남단) 지하철 5호선 여의나루역 2번 출구 도보 17분',
    'BUS': '(북단) 버스정류장 강변한신코아 정류장 하차 후 도보 이용 / (남단) 버스정류장 여의도공원 정류장 하차 후 도보 이용',
    'PARKING_INFO': '',
    'REG_DATE': '2024-06-19 10:12:52.0',
    'MOD_DATE': '2024-12-11 15:28:59.0'},
   {'NUM': 12.0,
    'SUBJECT_CD': '공공시설',
    'TITLE': '난지거울분수',
    'ADDR': '서울 마포구 상암동 1536-1',
    'LA': '37.5599345342961',
    'LO': '126.88981563725',
    'TEL_NO': '난지안내센터 02-3780-0611',
    'URL': 'https://hangang.seoul.go.kr/www/facility/map.tab?srchCd=9054',
    'OPERATING_TIME': '성수기(7~8월) (매시 정각 20분) 12:00 ~ 21:00(10회) 비수기(4~6월, 9~10월) (매회 20분) 12:00, 17:00, 18:00, 19:00, 20:00(5회) ',
    'FREE_YN': '무료',
    'ENTR_FEE': '무료',
    'CONTENTS': '<p class="0"><span style="font-size: 14pt;">난지한강공원 거울분수는 직경 <span lang="EN-US">60m </span>규모로 분수를 가동하지 않을 경우는 <span lang="EN-US">1</span>만<span lang="EN-US">2300</span>㎡의 수조에 물을 담수해<span lang="EN-US">(</span>수심<span lang="EN-US">3cm) </span>거울연못으로 활용하는 수경시설입니다<span lang="EN-US">. </span>특히 정적인 분수와 동적인 분수의 조화가 아름다우며<span lang="EN-US">, </span>수조 내 담수된 물이 표면위로 주위의 배경이 투영되어 더욱 멋진 광경을 연출합니다<span lang="EN-US">. </span>난지한강공원 거울분수는 가을철 노을&sdot;하늘공원의 억새풀 광장 및 월드컵 경기장과 함께 가족나들이로 꼽히는 서울시의 대표 명소입니다<span lang="EN-US">.</span></span></p>',
    'SUBWAY': '지하철 6호선 마포구청역 7번, 6번 출구 도보 이용',
    'BUS': '마포구청역 버스정류장 하차 도보 이용',
    'PARKING_INFO': '',
    'REG_DATE': '2024-06-19 11:12:10.0',
    'MOD_DATE': '2024-12-11 15:31:05.0'},
   {'NUM': 13.0,
    'SUBJECT_CD': '공공시설',
    'TITLE': '이촌한강공원',
    'ADDR': '서울특별시 용산구 이촌로72길 62',
    'LA': '37.517820588578',
    'LO': '126.970850893942',
    'TEL_NO': '02-3780-0551~4',
    'URL': 'https://hangang.seoul.go.kr/www/contents/660.do?mid=458 ',
    'OPERATING_TIME': '상시',
    'FREE_YN': '무료',
    'ENTR_FEE': '무료',
    'CONTENTS': '<p class="0">이촌한강공원은 중랑천교와 원효대교 사이 한강 북단에 위치한 공원으로 호안을 따라 갈대<span lang="EN-US">, </span>억새<span lang="EN-US">, </span>코스모스가 철마다 피어나 산책과 조깅 코스로 자주 이용되고 있습니다<span lang="EN-US">. </span>청소년광장과 <span lang="EN-US">X-</span>게임장<span lang="EN-US">, </span>국제 규격의 인라인스케이트장<span lang="EN-US">, </span>농구장<span lang="EN-US">, </span>테니스장<span lang="EN-US">, </span>게이트볼장 등 다양한 체육시설이 여가 및 레포츠 공간으로 유용하게 활용되고 있습니다<span lang="EN-US">. </span>또한<span lang="EN-US">, </span>수상훈련장이 위치하여 개인<span lang="EN-US">, </span>학생<span lang="EN-US">, </span>직장인 등 다양한 시민의 수상레저 스포츠 체험 및 훈련에 이용되고 있습니다<span lang="EN-US">.</span></p>\r\n<p class="0">아울러 자연성 회복 사업에 따라 조성된 강변 물골<span lang="EN-US">, </span>논습지<span lang="EN-US">, </span>억새 군락과 더불어 다양한 한강예술공원 조형물들이 조화로운 경관을 이루고 있어 자연과 예술을 함께 즐길 수 있습니다<span lang="EN-US">. </span>특히<span lang="EN-US">, </span>한적한 호안 산책로를 따라 걸으며 노들섬<span lang="EN-US">, </span>한강철교<span lang="EN-US">, </span>여의도 빌딩 숲 등을 배경으로 한 낙조 및 야경을 한눈에 담을 수 있는 조망 명소로도 알려져 있습니다<span lang="EN-US">.</span></p>',
    'SUBWAY': '4호선, 경의중앙선 이촌역 4번 출구에서 도보 500m ',
    'BUS': '이촌동한강맨션, 동부이촌동, 한강대교전망카페 등 버스정류장 하차 도보 이용',
    'PARKING_INFO': '',
    'REG_DATE': '2024-06-12 20:35:01.0',
    'MOD_DATE': '2024-12-11 15:31:29.0'},
   {'NUM': 14.0,
    'SUBJECT_CD': '공원/광장',
    'TITLE': '남산공원 백범광장- 서울한양도성 성곽',
    'ADDR': '서울 중구 회현동1가 산 1-44',
    'LA': '37.5550484830696',
    'LO': '126.98043243063',
    'TEL_NO': '02-120, 02-3783-5900',
    'URL': 'https://parks.seoul.go.kr/template/sub/namsan.do',
    'OPERATING_TIME': '상시개방',
    'FREE_YN': '무료',
    'ENTR_FEE': '무료',
    'CONTENTS': '<p class="0"><span style="font-size: 14pt;">남산공원의 한양도성은 장충체육관 뒷길에서 남산공원까지 이어지는 구간으로 일제에 의해 파괴되었던 성벽을 <span lang="EN-US">1970</span>년대 이후 성곽 보존 정비 사업과 <span lang="EN-US">1990</span>년대 중반 남산 제 모습 찾기 사업을 통해 대부분 복원되었다<span lang="EN-US">.</span></span></p>',
    'SUBWAY': '지하철 4호선 명동역 4번 출구 도보 이용',
    'BUS': '힐튼호텔, 백범광장(힐튼호텔방면) 정류장 하차 도보 이용',
    'PARKING_INFO': '',
    'REG_DATE': '2024-06-19 10:54:32.0',
    'MOD_DATE': '2024-12-11 15:33:35.0'},
   {'NUM': 15.0,
    'SUBJECT_CD': '공원/광장',
    'TITLE': '사육신공원',
    'ADDR': '서울특별시 동작구 노량진로 191',
    'LA': '37.5134579901091',
    'LO': '126.949411135441',
    'TEL_NO': '(공원안내) 02-813-2130',
    'URL': '',
    'OPERATING_TIME': '운영 제한 없음',
    'FREE_YN': '무료',
    'ENTR_FEE': '무료',
    'CONTENTS': '<p><span style="font-size: 14pt;">사육신 공원은 한강대교와 노량진역 사이의 언덕에 있는 사육신묘(서울특별시유형문화재 8)일대 4만 9401㎢의 면적을 성역으로 가꾸어 문을 연 공원으로, 언덕 마루에서 한강철교 방면의 멋진 야경을 볼 수 있다.</span></p>',
    'SUBWAY': '1호선 노량진역 2번 출구 도보 10분/9호선 노들역 1번 출구 도보 10분',

In [31]:
import pandas as pd
temp = []
for d in data['viewNightSpot']['row']:
    temp.append(d)
uni = pd.DataFrame(temp)
uni

,NUM,SUBJECT_CD,TITLE,ADDR,LA,LO,TEL_NO,URL,OPERATING_TIME,FREE_YN,ENTR_FEE,CONTENTS,SUBWAY,BUS,PARKING_INFO,REG_DATE,MOD_DATE
0,1.0,문화/체육,남산서울타워,서울특별시 용산구 남산공원길 105,37.5511225714939,126.987867837993,"02-3455-9277, 9288",https://www.seoultower.co.kr/,연중무휴 * 타워내 개별시설 운영시간 상이,무료,남산공원 입장료 없음(전망대 등 개별 이용시설 요금 별도),<p>남산서울타워는 효율적인 방송전파 송수신과 한국의 전통미를 살린 관광 전망시설의...,지하철 4호선 회현역 3번 출구 도보 이용,"남산순환버스 01A번, 01B번 이용 * 남산공원 생태 환경 보호 일환으로 승용차...",,2024-06-05 00:00:00.0,2024-06-24 16:59:59.0
1,2.0,문화/체육,장충체육관,서울특별시 중구 동호로 241,37.5586406607183,127.006677513121,(안내) 02-2128-2800,http://www.sisul.or.kr/open_content/jangchung/,평일 : 9:00 ~18:00 / 주말 : 경기 또는 행사시 운영시간에 따라 상이,유료,경기·행사 시마다 상이,"<p class=""0""><span lang=""EN-US"">1963</span>년 <...",지하철 3호선 동대입구역 5번출구 (체육관 직접연결),"장충체육관앞 02-201(서울) N13, 144, 301, 7212 / 장충체육관앞...",체육관 북측 부설주차장 이용 * 행사시 일반주차 없음,2024-06-19 10:17:30.0,2024-12-11 15:11:42.0
2,3.0,공원/광장,용양봉저정 공원,서울 동작구 본동 산 3-9,37.5118003827004,126.958588093172,(공원안내) 02-820-9258,,운영 제한 없음,무료,무료,"<p class=""0"">용양봉저정은 조선시대에 정조임금이 아버지 사도세자의 묘가 있...",9호선 노들역 3번 출구 도보 20분,"동작실버센터 정류장, 흑석동효사정 하차 도보 5분",용양봉저정공원 주차장 도보 5분,2024-06-19 11:15:52.0,2024-12-11 15:12:55.0
3,4.0,문화/체육,창경궁,서울특별시 종로구 창경궁로 185,37.579412935392185,126.99522255388881,02-762-4868,https://royal.khs.go.kr/cgg,"화~일 09:00~21:00 * 매주 월요일 정기휴관, 계절별 운영시간 상이",유료,"유료 대인 1,000원, 한복착용자 무료",<p>창경궁(昌慶宮)은 성종이 세 명의 대비를 위해 옛 수강궁에 창건한 궁이다.</...,지하철 4호선 혜화역 4번 출구 도보 이용,창경궁 정류장 하차 도보 이용,,2024-06-12 20:44:00.0,2024-06-27 17:32:26.0
4,5.0,공원/광장,서울어린이대공원 내 서울상상나라,서울특별시 광진구 능동로 216,37.5520117940291,127.078770241307,02-450-9311,https://www.sisul.or.kr/open_content/childrenp...,5:00~22:00 (연중무휴),무료,무료,"<p class=""0"">서울어린이대공원 능동문 앞에 위치한 서울상상나라와 원형광장은...",7호선 어린이대공원역 1번출구,‘세종대학교’ 정류소 하차,운영시간 05:00 - 22:00,2024-06-19 10:49:45.0,2024-12-11 15:15:22.0
5,6.0,문화/체육,창덕궁,서울특별시 종로구 율곡로 99,37.57950279094907,126.99103378705136,02-3668-2300,https://royal.cha.go.kr/cdg,"화~일 09:00~18:00 * 매주 월요일 정기휴관, 계절별 운영시간 상이",유료,"대인 3,000원, 한복착용자 무료","<p class=""0"">창덕궁<span lang=""EN-US"">(</span>昌德宮...",지하철 1호선 종로3가역 6번 출구 도보 이용,창덕궁 정류장 하차 도보 이용,,2024-06-12 20:43:24.0,2024-12-11 15:18:46.0
6,7.0,공공시설,여의도한강공원 물빛광장,서울 영등포구 여의도동 84-9,37.5312466908117,126.928686496763,"여의도안내센터 02-3780-0566, 총괄 담당 02-3780-0652",https://hangang.seoul.go.kr/www/contents/861....,"성수기(7~8월), (정각 마다 30분) 12:00 ~ 21:00(10회), 비수기...",무료,,"<p><span style=""font-size: 14pt;"">여의도 물빛광장분수는 ...","지하철 5호선 여의나루역 1번, 2번 출구 도보 이용",여의도 순복음교회 앞 / 여의도공원 앞 버스정류장 하차 도보 이용,,2024-06-12 20:46:18.0,2024-06-26 14:08:03.0
7,8.0,공공시설,뚝섬 자벌레(한강이야기전시관),서울특별시 광진구 강변북로 2202,37.5308773153076,127.065983191885,02-3780-0517,http://www.j-bug.co.kr,월요일 휴관 / 화~금 9:00~18:00 / 토~일 9:00~20:00,무료,,<p>한강이야기전시관은 한강의 역사와 문화적 가치를 일상에서 누리고 체험할 수 있는...,지하철 2호선 자양(뚝섬한강공원)역 3번출구,"노유나들목 앞 정류장 2014, 자양나들목 앞 정류장 2221, 2222, 2415",뚝섬한강공원 주차장,2024-06-12 20:48:19.0,2024-06-27 17:32:00.0
8,9.0,공원/광장,청계천,서울 중구 태평로 1가 1,37.56915554121704,126.97871950992457,02-2290-7111~3(청계천종합상황실),https://www.sisul.or.kr/open_content/cheonggye/,24시간 연중무휴(강우예보 및 우천시 출입통졔),무료,무료,"<p>도심 속에 자리 잡은 청계천은 2005. 10. 1 개장, 매년 천만 명 이상...","지하철 5호선 광화문역 5번출구에서 약 60m 이동 / 지하철 1, 2호선 시청역 ...","시청.서울신문사(02137, 02706) 하차 / 간선 : 101,150,501,5...",청계광장에는 별도의 주차장이 없습니다. 대중교통이나 인근 주차장을 이용하여 주시기 ...,2024-06-12 20:35:59.0,2024-07-02 09:19:05.0
9,10.0,공공시설,성수대교,서울 성동구 옥수동 484,37.53617802719353,127.03489368057885,02-120,,일몰 30분후 점등 ~ 23:00 소등,무료,,<p>성수대교는 성동구 성수동과 강남구 압구정동을 연결하는 한강교량입니다. 총 길이...,"(북단) 지하철 2호선 뚝섬역 8번출구 도보 이용, (남단) 지하철 3호선 압구정역...","(북단) 버스정류장 뚝섬서울숲 정류장 하차 후 도보 이용, (남단) 압구정중고등학교...",,2024-06-12 20:36:47.0,2024-06-27 17:31:17.0
10,17.0,공원/광장,문화비축기지,서울특별시 마포구 증산로 87,37.5703466887615,126.895031420115,02-376-8410,https://parks.seoul.go.kr/template/sub/culture...,"야외공원 24시간 개방, 탱크 T1~T6 화~일요일 10:00~18:00 (월요일 휴관)",무료,,<p>[석유에서 문화로(Oil to Culture)]</p>\r\n<p>마포구 서울...,6호선 월드컵경기장역 2·3번 출구에서 도보 10분,문화비축기지 정류장 하차 도보 이용,,2024-06-12 20:38:32.0,2024-10-29 19:19:38.0
11,11.0,공공시설,마포대교,서울 영등포구 여의도동 85-2,37.5324287051867,126.935734355376,(경관조명 안내) 02-300-8404 (마포대교 안내) 02-2133-1978,,일몰 30분후 점등 ~ 23:00 소등,무료,무료,"<p class=""0"">마포대교는 마포구 용강동과 영등포구 여의도동을 연결하는 한강...","북단) 지하철 5호선 마포역 1,4번출구 도보 15분 / (남단) 지하철 5호선 여...",(북단) 버스정류장 강변한신코아 정류장 하차 후 도보 이용 / (남단) 버스정류장 ...,,2024-06-19 10:12:52.0,2024-12-11 15:28:59.0
12,12.0,공공시설,난지거울분수,서울 마포구 상암동 1536-1,37.5599345342961,126.88981563725,난지안내센터 02-3780-0611,https://hangang.seoul.go.kr/www/facility/map.t...,성수기(7~8월) (매시 정각 20분) 12:00 ~ 21:00(10회) 비수기(4...,무료,무료,"<p class=""0""><span style=""font-size: 14pt;"">난지...","지하철 6호선 마포구청역 7번, 6번 출구 도보 이용",마포구청역 버스정류장 하차 도보 이용,,2024-06-19 11:12:10.0,2024-12-11 15:31:05.0
13,13.0,공공시설,이촌한강공원,서울특별시 용산구 이촌로72길 62,37.517820588578,126.970850893942,02-3780-0551~4,https://hangang.seoul.go.kr/www/contents/660.d...,상시,무료,무료,"<p class=""0"">이촌한강공원은 중랑천교와 원효대교 사이 한강 북단에 위치한 ...","4호선, 경의중앙선 이촌역 4번 출구에서 도보 500m","이촌동한강맨션, 동부이촌동, 한강대교전망카페 등 버스정류장 하차 도보 이용",,2024-06-12 20:35:01.0,2024-12-11 15:31:29.0
14,14.0,공원/광장,남산공원 백범광장- 서울한양도성 성곽,서울 중구 회현동1가 산 1-44,37.5550484830696,126.98043243063,"02-120, 02-3783-5900",https://parks.seoul.go.kr/template/sub/namsan.do,상시개방,무료,무료,"<p class=""0""><span style=""font-size: 14pt;"">남산...",지하철 4호선 명동역 4번 출구 도보 이용,"힐튼호텔, 백범광장(힐튼호텔방면) 정류장 하차 도보 이용",,2024-06-19 10:54:32.0,2024-12-11 15:33:35.0
15,15.0,공원/광장,사육신공원,서울특별시 동작구 노량진로 191,37.5134579901091,126.949411135441,(공원안내) 02-813-2130,,운영 제한 없음,무료,무료,"<p><span style=""font-size: 14pt;"">사육신 공원은 한강대교...",1호선 노량진역 2번 출구 도보 10분/9호선 노들역 1번 출구 도보 10분,버스정류장 사육신공원 정류장 하차 도보 이용,,2024-06-19 11:18:01.0,2024-06-26 15:00:13.0
16,16.0,공공시설,월드컵대교,서울 마포구 상암동 1541,37.5573505544798,126.884431803276,(경관조명 안내) 02-2657-7965 (월드컵대교 안내) 02-2133-1962,,일몰 30분후 점등 ~ 23:00 소등,무료,무료,"<p class=""0""><span style=""font-size: 14pt;"">월드...","(북단) 지하철 6호선 월드컵경기장역 2, 3번 출구로 나와 도보 / (남단) 지하...",(북단) 버스정류장 월드컵공원입구(문화비축기지입구) 정류장 하차 후 도보 / (남단...,,2024-06-19 11:25:10.0,2024-12-11 15:34:28.0
17,18.0,문화/체육,숭례문(남대문),서울특별시 중구 세종대로 40,37.5599277853801,126.975359779271,02-779-8547,https://royal.khs.go.kr/ROYAL/contents/menuInf...,화~일 09:00~18:00 * 매주월요일 정기휴관,무료,,<p>숭례문(崇禮門)은 1398년(태조 7)에 완성한 한양도성의 남대문입니다.</p...,"지하철 1, 2호선 시청역 2번 출구 도보 이용",숭례문 또는 남대문시장 정류장 하차 도보 이용,,2024-06-12 20:41:28.0,2024-06-27 17:32:40.0
18,19.0,문화/체육,서울월드컵경기장,서울특별시 마포구 월드컵로 240,37.5682884450841,126.897273034482,02-2128-2002,https://www.sisul.or.kr/open_content/worldcup/,09시 ~ 18시 * 주말 경기/행사 시 상이,유료,"스타디움 투어 입장료 : 1,000원 * 경기/행사 마다 상이","<p><span style=""font-size: 14pt;"">서울월드컵경기장은 20...",,,,2024-06-26 10:39:27.0,2024-10-31 14:39:37.0
19,20.0,공원/광장,노들섬복합문화공간,서울특별시 용산구 양녕로 445,37.5176638307111,126.958036465507,02-749-4500,https://nodeul.org/,"화~금 10:00~21:00, 주말, 공휴일 10:00~22:00",무료,무료,"<p><span style=""font-size: 14pt;"">한강대교 중간에 위치한...",1호선 용산역 1번 출구 또는 4호선 신용산역 3번출구 근처 버스정류장에서 노들섬 ...,버스정류장 노들섬에서 하차 도보 이용,"유료주차(서측 69대, 동측 21대), 주차 문의 : 02-2105-2415 * ...",2024-06-26 10:56:51.0,2024-07-01 10:50:13.0
20,21.0,공원/광장,광화문광장(광화문),서울특별시 종로구 세종대로 172,37.5716228232824,126.976787992565,02-120,https://gwanghwamun.seoul.go.kr/,연중무휴,무료,무료,"<div><span style=""font-size: 14pt;"">광화문광장은 조선시...",지하철 5호선 광화문역 7번 출구 도보 이용,"세종문화회관, KT광화문지사 정류장 하차 도보 이용",,2024-06-12 20:26:33.0,2024-12-11 15:35:39.0
21,22.0,공원/광장,하늘공원(월드컵공원내),서울특별시 마포구 하늘공원로 95,37.5690794796181,126.886318397942,(공원안내) 02-300-5501 (주차장안내) 02-304-6678,https://parks.seoul.go.kr/template/sub/worldcu...,월별 운영시간 상이 (하단 공원소개 내용 참조),무료,무료,"<div class=""hwp_editor_board_content"" data-hjs...",지하철 6호선 월드컵경기장역 1번 출구에서 도보 2km,난지천공원에서 하늘공원 정상까지 맹꽁이 전기차 탑승,운영시간 09:00 - 22:00 (이후 시간 무료 개방),2024-06-05 00:00:00.0,2024-12-11 15:09:34.0
22,23.0,문화/체육,동대문디자인플라자(DDP),서울특별시 중구 을지로 281,37.56769968798189,127.00984769474137,(종합안내소) 02-2153-0000 (주차장 안내) 02-2153-0141,https://ddp.or.kr/,"10:00 ~ 20:00 (공간별 운영시간 상이, 홈페이지 참조)",무료,,"<p><span style=""font-size: 14pt;"">10주년을 맞은 동대문...","동대문역사문화공원역 1번, 2번 출구","동대문역사문화공원, 동대문디자인플라자 정류장 하차",,2024-06-05 00:00:00.0,2024-06-26 14:25:10.0
23,24.0,문화/체육,경복궁,서울특별시 종로구 사직로 161,37.5759040910202,126.976842133821,02-3700-3900,https://royal.khs.go.kr/gbg,"1월~2월, 11월~12월 09:00~17:00, 3월~5월, 9월~10월 09:0...",유료,"유료 대인 3,000원, 한복착용자 무료",<p>경복궁(景福宮)은 1392년 조선 건국 후</p>\r\n<p>1395년(태조 ...,지하철 3호선 경복궁 5번 출구 도보 이용,경복궁 정류장 하차 도보 이용,,2024-06-12 20:42:52.0,2024-10-31 14:41:14.0
24,25.0,공공시설,서울로미디어캔버스,서울특별시 중구 만리재로 215,37.5566331857979,126.968148438254,02-120,https://www.instagram.com/mediaartseoul,18:00 -23:00,무료,무료,"<p class=""0""><span style=""font-size: 14pt;"">서울...",,,,2024-06-25 14:33:28.0,2024-06-26 17:28:54.0
25,26.0,문화/체육,덕수궁,서울특별시 중구 세종대로 99,37.5656250952955,126.97469099468877,02-771-9951,https://royal.cha.go.kr/ROYAL/contents/menuInf...,09:00~21:00 (입장마감 20:00) * 월요일 휴무,유료,"개인 1,000원, 단체(10인 이상) 800원","<p><span style=""font-size: 14pt;"">덕수궁은 1897년에 ...","지하철 1, 2호선 시청역 2번 출구 도보 이용",시청앞.덕수궁 정거장 하차 도보 이용,,2024-06-05 00:00:00.0,2024-12-11 15:10:27.0
26,27.0,공공시설,반포대교 달빛무지개 분수,서울 서초구 반포동 647,37.5145518124606,126.997949287136,"반포안내센터 02-3780-0541~4, 운영사무실 02-3780-0578",https://hangang.seoul.go.kr/www/contents/856.d...,"성수기(7~8월) 12:00, 19:30, 20:00, 20:30, 21:00, 2...",무료,무료,"<p class=""0""><span style=""font-size: 14pt;"">달빛...","지하철 3, 7, 9호선 고속터미널역 8-1번, 8-2번 출구 도보 이용","반포한강공원, 반포대교남단 한강시민공윈 입구 버스정류장 하차 도보 이용",,2024-06-05 00:00:00.0,2024-12-11 15:11:09.0
27,28.0,공원/광장,서울어린이대공원 팔각당 오름광장,서울특별시 광진구 능동로 216,37.5520117940291,127.078770241307,02-450-9311,https://www.sisul.or.kr/open_content/childrenp...,5:00~22:00 (연중무휴),무료,무료,"<p class=""0""><span lang=""EN-US"">1. </span>서울어린...","5호선 아차산역 4번출구, 7호선 어린이대공원역 1번출구",‘어린이대공원후문아차산역’ 혹은 ‘세종대학교’ 정류소 하차,운영시간 05:00 - 22:00,2024-06-19 10:28:08.0,2024-12-11 15:12:19.0
28,29.0,공공시설,올림픽대교,서울 송파구 신천동 250-1,37.535968547207,127.105516076607,"(경관조명 안내) 02-2040-0367, (올림픽대교 안내) 02-2133-1954",,11~ 4월 : 일몰 30분 후 점등 ~ 23:00 소등 / 5 ~ 10월 : 일몰...,무료,무료,"<p class=""0"">올림픽대교는 광진구 구의동과 송파구 풍납동을 연결하는 한강교...",(북단)강변역 1번출구 도보 21분 / (남단)강동구청역 4번 출구 도보 37분,(북단)버스정류장 프라임아파트앞 정류장 하차 도보 이용 / (남단)버스정류장 풍납토...,,2024-06-19 11:28:50.0,2024-12-11 15:13:25.0
29,30.0,문화/체육,세빛섬,서울특별시 서초구 올림픽대로 2085-14,37.5124362037118,126.995962256954,1566-3433,https://www.somesevit.co.kr/,개별시설별 운영시간 상이,유료,"무료입장 가능, 개별 시설 이용료 별도","<p class=""0"">한강을 아름답게 밝혀줄 세 개의 빛나는 섬<span lang...","지하철 3, 7, 9호선 8-1번 출구 도보 이용",반포대교 남단 정류장 하차 도보 이용,,2024-06-12 20:27:27.0,2024-12-11 15:13:54.0
30,31.0,공원/광장,서울함 공원,서울특별시 마포구 마포나루길 407,37.5557880616618,126.893953718935,02-332-7500,https://www.seoulbattleshippark.com/,"하절기(3월-10월) 평일 10:00~19:00 / 주말,공휴일 10:00~20:0...",유료,"성인 3,000원 / 청소년, 군인 2,000원 / 어린이 1,000원(시설 방문 ...","<p class=""0"">조선시대 한강에는 나루터를 중심으로 상업이 발달하면서 물동량...",6호선 망원역 1번 출구 앞 버스정류장에서 마포09번 버스 탑승 후 '한강공원입구'...,"2, 6호선 합정역 1번 출구 앞 버스정류장에서 마포16번 버스 탑승 후 '망원유수...",운영시간 06:00 ~ 24:00 (유료 운영) 안내 문의처 070-7778-6678,2024-06-12 20:32:31.0,2024-12-11 15:14:34.0
31,32.0,공원/광장,낙산공원 - 한양도성 성곽길,서울특별시 종로구 낙산성곽서길 173,37.579840084989,127.008253028696,"(공원안내) 02-3783-5900, 02-743-7985 (주차안내) 070-89...",https://parks.seoul.go.kr/template/sub/naksan.do,상시개방,무료,무료,"<p class=""0"">서울한양도성은 외적의 침입으로부터 수도 한양을 수호하기 위해...",지하철 4호선 혜화역 2번 출구 도보 10분,"낙산공원(낙산삼거리방면), 혜화역 마로니애공원 정류장 하차 도보 이용","운영시간 상시 (일반 25대, 장애인 1대)",2024-06-19 10:57:56.0,2024-12-11 15:15:53.0
32,33.0,문화/체육,아뜰리에 광화,서울특별시 종로구 세종대로 175,37.5718478584908,126.976168275947,02-120,https://www.instagram.com/atelier_gwanghwa/,일몰후~ 22:00,무료,무료,"<p class=""0""><span style=""font-size: 14pt;"">아뜰...",지하철 5호선 광화문역 7번 출구 도보 이용,"세종문화회관, KT광화문지사 정류장 하차 도보 이용",,2024-06-19 11:01:11.0,2024-12-11 15:16:21.0
33,34.0,공공시설,당산철교,서울 영등포구 여의도동 80-3,37.54021916440686,126.90710358297696,(경관조명 안내) 02-6311-9745 (당산철교 안내) 02-6110-5588,,일몰 30분후 점등 ~ 23:00 소등,무료,,"<p><span style=""font-size: 14pt;"">당산철교는 서울 지하철...","(북단) 지하철 2호선 합정역 7번출구 도보 30분 (남단) 지하철 2호선, 9호...",(북단) 버스정류장 양화진성지 하차 후 도보 이용 (남단) 버스정류장 당산역 정류...,,2024-06-12 20:34:29.0,2024-06-26 14:11:33.0
34,35.0,문화/체육,세종문화회관,서울특별시 종로구 세종대로 175,37.5718478584908,126.976168275947,(안내) 02-399-1000,https://www.sejongpac.or.kr,월별 운영시간 상이,유료,프로그램별 상이,"<p class=""0"">세종문화회관은 서울특별시가 설립한 기관으로 서울의 대표적인 ...","지하철 5호선 광화문역 1번, 8번 출구 도보 3분",버스정류장 세종문화회관 하차 도보 이용,세종로주차장이용,2024-06-19 11:32:51.0,2024-12-11 15:16:51.0
35,36.0,공공시설,한강대교,서울특별시 용산구 이촌로29길 1-11,37.5276608637794,126.962182447512,(경관조명 안내) 02-3284-5436,,일몰 30분후 점등 ~ 23:00 소등,무료,무료,"<p class=""0""><span style=""font-size: 14pt;"">한강...","(북단) 지하철 4호선 신용산역 2,3번출구 도보 15분 / (남단) 지하철 9호선...","(북단) 버스정류장 한강대교북단, LG유플러스 정류장 하차 후 도보 이용 / (남단...",,2024-06-19 11:36:28.0,2024-12-11 15:17:21.0
36,37.0,공공시설,동작대교,서울 용산구 이촌동 385,37.51007066016623,126.98138294783693,(경관조명 안내) 02-3284-5436,,일몰 30분후 점등 ~ 23:00 소등,무료,무료,"<p class=""0""><span style=""font-size: 14pt;""><s...",(북단) 지하철 4호선 이촌역 3-1번출구 도보 20분 / (남단) 지하철 4호선 ...,"(북단) 버스정류장 금강병원, 반도아파트 정류장 하차 후 도보 이용, (남단) 버스...",,2024-06-19 12:34:46.0,2024-12-11 15:17:49.0
37,38.0,공공시설,서울시립미술관 서소문본관,서울특별시 중구 덕수궁길 61,37.5641060692766,126.973699316136,"02-2184-8800, 02-120",https://sema.seoul.go.kr/,"화~금 10:00~20:00 / 토, 일, 공휴일 하절기 10:00~19:00, 동...",무료,무료(특별전 유료),"<p class=""0""><span style=""font-size: 14pt;"">서울...","지하철 1, 2호선 시청역 1번, 10번, 11번, 12번 출구 도보 이용",버스정류장 시청.서소문청사 도보 5분,,2024-06-13 16:41:46.0,2024-12-11 15:32:04.0
38,39.0,공원/광장,서울식물원,서울특별시 강서구 마곡동로 161,37.5722444079878,126.83284283132,02-2104-9716,https://botanicpark.seoul.go.kr/,하절기(3월~10월) : 09:30~18:00(매표마감 17:00) 동절기(11월~...,유료,"주제원 유료 이용, 열린숲&호수원& 습지원 무료 이용","<p class=""0"">서울식물원은 식물원과 공원이 유기적으로 결합된 공원 속 식물...","지하철 9호선 양천향교역 8번출구 도보 10분 / 지하철 9호선, 공항철도 마곡나루...","버스정류장 겸재정원미술관, 마곡나루역 정류장 하차 도보 이용",운영시간 09:00 - 22:00 (이후 시간 무료 개방),2024-06-19 10:07:28.0,2024-12-11 15:32:33.0
39,40.0,가로/마을,덕수궁 돌담길,서울특별시 중구 세종대로 99,37.564976656898445,126.97602682975977,,,연중무휴,유료,,"<p class=""0"">덕수궁 돌담길은 덕수궁 외벽을 이루는 돌담길을 말합니다<sp...","지하철 1, 2호선 시청역 2번출구 도보 5분",버스정류장 시청덕수궁 도보 3분,,2024-06-12 20:42:01.0,2025-03-25 18:07:57.0
40,41.0,문화/체육,광진교 8번가,서울 강동구 천호동 527-2,37.5451462595072,127.112687934633,02-476-0722,https://riverview8.co.kr/rv/html/,"4월~10월(12:00~20:00), 3월,11월(12:00~18:00)",무료,무료,"<p class=""0""><span style=""font-size: 14pt;""><s...","지하철 5호선 광나루역(도보 약 15분), 지하철 5호선 천호역(도보 약 15분)","광나루 한강공원 2주차장(강동구 천호동 483-8), 광나루 한강공원 3주차장(송파...",,2024-06-12 20:47:06.0,2024-12-11 15:25:16.0
41,42.0,문화/체육,고척스카이돔,서울특별시 구로구 경인로 430,37.4982125677913,126.867088741096,1666-3102,https://www.sisul.or.kr/open_content/skydome/,연중,유료,행사 시 관람료(입장료) 발생,"<p class=""0""><span lang=""EN-US"">2015</span>년 개...",지하철 1호선 구일역 2번 출구,"버스정류장 동양미래대학, 구로성심병원 정류장 하차",,2024-06-19 10:22:04.0,2024-12-11 15:29:25.0
42,43.0,공원/광장,서울어린이대공원 후문 선형공원,서울특별시 광진구 능동로 216,37.5520117940291,127.078770241307,02-450-9311,https://www.sisul.or.kr/open_content/childrenp...,05:00~22:00 (연중무휴),무료,무료,"<p class=""0""><span style=""font-size: 14pt;"">서울...",5호선 아차산역 4번출구,‘어린이대공원후문아차산역’ 정류장에 하차,운영시간 05:00 - 22:00,2024-06-19 10:24:53.0,2024-12-11 15:30:08.0
43,44.0,공공시설,뚝섬 음악분수,서울 광진구 자양동 435,37.5278618984384,127.073807096279,"02-3780-0521, 02-3780-0652",https://hangang.seoul.go.kr/www/contents/859....,"성수기(7~8월) (정각 마다 20분) 12:00 ~ 21:00(10회), 비수기(...",무료,무료,"<p class=""0"">뚝섬한강공원에 설치된 음악분수는<span lang=""EN-U...",지하철 7호선 자양역 2번 출구 도보 이용,자양4동주민센터 앞 / 신자초등학교 앞 버스정류장 하차 도보 이용,,2024-06-12 20:45:35.0,2024-12-11 15:19:16.0
44,45.0,공원/광장,석촌호수 루미나리에(송파나루공원),서울 송파구 잠실동 22-6,37.509081251676484,127.10290138635898,,https://www.songpa.go.kr/culture/detailInfo.do...,17:30~22:30 (루미나리에 축제 경관조명 점등 시간),무료,무료,"<p class=""0"">매해 가을과 겨울 석촌호수에서 색다른 빛축제를 만날 수 있습...",지하철 2·8호선 잠실역,,,2024-06-12 20:49:04.0,2024-12-13 09:50:19.0
45,46.0,공공시설,동호대교,서울 성동구 옥수동 86,37.53866839156651,127.01914464062273,02-120,,일몰 30분후 점등 ~ 23:00 소등,무료,무료,"<p class=""0"">동호대교는 성동구 옥수동과 강남구 압구정동을 연결하는 한강교...","(북단) 지하철 3호선 옥수역 3번출구 도보 이용, (남단) 지하철 3호선 압구정역...","(북단) 버스정류장 옥수삼성아파트 정류장 하차 후 도보 이용, (남단) 버스정류장 ...",,2024-06-12 20:37:55.0,2024-12-11 15:27:40.0
46,47.0,공원/광장,선유도공원,서울특별시 영등포구 선유로 343,37.5423832345578,126.901819342041,02-2631-9368,https://parks.seoul.go.kr/template/sub/seonyud...,06:00 - 24:00,무료,무료,"<p class=""0""><span lang=""EN-US"">&ldquo;</span>...","선유도역 - 9호선 (도보 약 10분) / 당산역 - 2호선, 9호선 (도보 약 15분)","선유도 정류장 하차 도보 이용 * 장애인주차만 가능, 일반차량의 경우 양화한강공원...",,2024-06-12 20:39:08.0,2024-12-11 15:28:06.0
47,48.0,문화/체육,송파책박물관,서울특별시 송파구 송파대로37길 77,37.4988841772964,127.104383431798,02-2147-2486,https://www.bookmuseum.go.kr/,"10:00 ~ 18:00 화, 수, 목, 금, 토, 일요일(입장마감 : 폐관 30분...",무료,무료,"<p class=""0"">송파책박물관은 전국 최초 공립 책 박물관입니다<span la...",지하철 8호선 송파역 4번출구 도보 15분,송파책박물관 헬리오시티 정류장 하차 도보 이용,"24시간 (최초 30분 무료, 무료시간 경과 후 5분당 150원)",2024-06-12 20:40:51.0,2024-12-11 15:28:35.0
48,49.0,공원/광장,노원불빛정원(화랑대철도공원 내),서울특별시 노원구 화랑로 608,37.6244509765399,127.093089721731,02-2116-0552,https://www.nowon.kr/www/info/info1/info1_06/i...,"화~일요일, 일몰전 30분~22:00 ※ 월요일 휴무",무료,"무료 ※ 단, 화랑대철도공원 내 일부 문화시설(기차마을 등) 입장료 있음","<p class=""0""><span style=""font-size: 14pt;"">○ ...",6호선 화랑대역 4번출구 하차 후 도보 10분 (약 898m),"‘경춘선숲길.화랑대역공원’ 버스정류장 하차 (간선버스 202 / 지선버스 1155,...",,2024-06-19 11:06:28.0,2024-12-11 15:30:36.0
49,50.0,공원/광장,서울어린이대공원 음악분수,서울특별시 광진구 능동로 216,37.5520117940291,127.078770241307,02-450-9311,https://www.sisul.or.kr/open_content/childrenp...,5:00~22:00 (연중무휴),무료,무료,"<p class=""0"">서울어린이대공원의 대표 핫플레이스인 음악분수<span lan...",7호선 어린이대공원역 1번출구,‘세종대학교’ 정류소 하차,운영시간 05:00-22:00,2024-06-19 10:47:20.0,2024-12-11 15:33:07.0
50,51.0,공공시설,성산대교,서울 마포구 망원동 306-53,37.5514767278681,126.891604816192,(경관조명 안내) 02-2657-7965 (성산대교 안내) 02-2133-1943,,일몰 30분후 점등 ~ 23:00 소등,무료,무료,"<p class=""0""><span style=""font-size: 14pt;"">성산...",(북단) 지하철 6호선 마포구청역 6번 출구로 나와 도보 / (남단) 지하철 9호선...,(북단) 버스정류장 마포구청역 하차 후 도보 / (남단) 버스정류장 양평동한솔아파트...,,2024-06-19 11:20:42.0,2024-12-11 15:34:03.0

In [32]:
import folium

map = folium.Map(location=[37.450086, 127.167980],
                 zoom_start=11,
                 tiles='cartodbpositron')
map

In [33]:
uni

,NUM,SUBJECT_CD,TITLE,ADDR,LA,LO,TEL_NO,URL,OPERATING_TIME,FREE_YN,ENTR_FEE,CONTENTS,SUBWAY,BUS,PARKING_INFO,REG_DATE,MOD_DATE
0,1.0,문화/체육,남산서울타워,서울특별시 용산구 남산공원길 105,37.5511225714939,126.987867837993,"02-3455-9277, 9288",https://www.seoultower.co.kr/,연중무휴 * 타워내 개별시설 운영시간 상이,무료,남산공원 입장료 없음(전망대 등 개별 이용시설 요금 별도),<p>남산서울타워는 효율적인 방송전파 송수신과 한국의 전통미를 살린 관광 전망시설의...,지하철 4호선 회현역 3번 출구 도보 이용,"남산순환버스 01A번, 01B번 이용 * 남산공원 생태 환경 보호 일환으로 승용차...",,2024-06-05 00:00:00.0,2024-06-24 16:59:59.0
1,2.0,문화/체육,장충체육관,서울특별시 중구 동호로 241,37.5586406607183,127.006677513121,(안내) 02-2128-2800,http://www.sisul.or.kr/open_content/jangchung/,평일 : 9:00 ~18:00 / 주말 : 경기 또는 행사시 운영시간에 따라 상이,유료,경기·행사 시마다 상이,"<p class=""0""><span lang=""EN-US"">1963</span>년 <...",지하철 3호선 동대입구역 5번출구 (체육관 직접연결),"장충체육관앞 02-201(서울) N13, 144, 301, 7212 / 장충체육관앞...",체육관 북측 부설주차장 이용 * 행사시 일반주차 없음,2024-06-19 10:17:30.0,2024-12-11 15:11:42.0
2,3.0,공원/광장,용양봉저정 공원,서울 동작구 본동 산 3-9,37.5118003827004,126.958588093172,(공원안내) 02-820-9258,,운영 제한 없음,무료,무료,"<p class=""0"">용양봉저정은 조선시대에 정조임금이 아버지 사도세자의 묘가 있...",9호선 노들역 3번 출구 도보 20분,"동작실버센터 정류장, 흑석동효사정 하차 도보 5분",용양봉저정공원 주차장 도보 5분,2024-06-19 11:15:52.0,2024-12-11 15:12:55.0
3,4.0,문화/체육,창경궁,서울특별시 종로구 창경궁로 185,37.579412935392185,126.99522255388881,02-762-4868,https://royal.khs.go.kr/cgg,"화~일 09:00~21:00 * 매주 월요일 정기휴관, 계절별 운영시간 상이",유료,"유료 대인 1,000원, 한복착용자 무료",<p>창경궁(昌慶宮)은 성종이 세 명의 대비를 위해 옛 수강궁에 창건한 궁이다.</...,지하철 4호선 혜화역 4번 출구 도보 이용,창경궁 정류장 하차 도보 이용,,2024-06-12 20:44:00.0,2024-06-27 17:32:26.0
4,5.0,공원/광장,서울어린이대공원 내 서울상상나라,서울특별시 광진구 능동로 216,37.5520117940291,127.078770241307,02-450-9311,https://www.sisul.or.kr/open_content/childrenp...,5:00~22:00 (연중무휴),무료,무료,"<p class=""0"">서울어린이대공원 능동문 앞에 위치한 서울상상나라와 원형광장은...",7호선 어린이대공원역 1번출구,‘세종대학교’ 정류소 하차,운영시간 05:00 - 22:00,2024-06-19 10:49:45.0,2024-12-11 15:15:22.0
5,6.0,문화/체육,창덕궁,서울특별시 종로구 율곡로 99,37.57950279094907,126.99103378705136,02-3668-2300,https://royal.cha.go.kr/cdg,"화~일 09:00~18:00 * 매주 월요일 정기휴관, 계절별 운영시간 상이",유료,"대인 3,000원, 한복착용자 무료","<p class=""0"">창덕궁<span lang=""EN-US"">(</span>昌德宮...",지하철 1호선 종로3가역 6번 출구 도보 이용,창덕궁 정류장 하차 도보 이용,,2024-06-12 20:43:24.0,2024-12-11 15:18:46.0
6,7.0,공공시설,여의도한강공원 물빛광장,서울 영등포구 여의도동 84-9,37.5312466908117,126.928686496763,"여의도안내센터 02-3780-0566, 총괄 담당 02-3780-0652",https://hangang.seoul.go.kr/www/contents/861....,"성수기(7~8월), (정각 마다 30분) 12:00 ~ 21:00(10회), 비수기...",무료,,"<p><span style=""font-size: 14pt;"">여의도 물빛광장분수는 ...","지하철 5호선 여의나루역 1번, 2번 출구 도보 이용",여의도 순복음교회 앞 / 여의도공원 앞 버스정류장 하차 도보 이용,,2024-06-12 20:46:18.0,2024-06-26 14:08:03.0
7,8.0,공공시설,뚝섬 자벌레(한강이야기전시관),서울특별시 광진구 강변북로 2202,37.5308773153076,127.065983191885,02-3780-0517,http://www.j-bug.co.kr,월요일 휴관 / 화~금 9:00~18:00 / 토~일 9:00~20:00,무료,,<p>한강이야기전시관은 한강의 역사와 문화적 가치를 일상에서 누리고 체험할 수 있는...,지하철 2호선 자양(뚝섬한강공원)역 3번출구,"노유나들목 앞 정류장 2014, 자양나들목 앞 정류장 2221, 2222, 2415",뚝섬한강공원 주차장,2024-06-12 20:48:19.0,2024-06-27 17:32:00.0
8,9.0,공원/광장,청계천,서울 중구 태평로 1가 1,37.56915554121704,126.97871950992457,02-2290-7111~3(청계천종합상황실),https://www.sisul.or.kr/open_content/cheonggye/,24시간 연중무휴(강우예보 및 우천시 출입통졔),무료,무료,"<p>도심 속에 자리 잡은 청계천은 2005. 10. 1 개장, 매년 천만 명 이상...","지하철 5호선 광화문역 5번출구에서 약 60m 이동 / 지하철 1, 2호선 시청역 ...","시청.서울신문사(02137, 02706) 하차 / 간선 : 101,150,501,5...",청계광장에는 별도의 주차장이 없습니다. 대중교통이나 인근 주차장을 이용하여 주시기 ...,2024-06-12 20:35:59.0,2024-07-02 09:19:05.0
9,10.0,공공시설,성수대교,서울 성동구 옥수동 484,37.53617802719353,127.03489368057885,02-120,,일몰 30분후 점등 ~ 23:00 소등,무료,,<p>성수대교는 성동구 성수동과 강남구 압구정동을 연결하는 한강교량입니다. 총 길이...,"(북단) 지하철 2호선 뚝섬역 8번출구 도보 이용, (남단) 지하철 3호선 압구정역...","(북단) 버스정류장 뚝섬서울숲 정류장 하차 후 도보 이용, (남단) 압구정중고등학교...",,2024-06-12 20:36:47.0,2024-06-27 17:31:17.0
10,17.0,공원/광장,문화비축기지,서울특별시 마포구 증산로 87,37.5703466887615,126.895031420115,02-376-8410,https://parks.seoul.go.kr/template/sub/culture...,"야외공원 24시간 개방, 탱크 T1~T6 화~일요일 10:00~18:00 (월요일 휴관)",무료,,<p>[석유에서 문화로(Oil to Culture)]</p>\r\n<p>마포구 서울...,6호선 월드컵경기장역 2·3번 출구에서 도보 10분,문화비축기지 정류장 하차 도보 이용,,2024-06-12 20:38:32.0,2024-10-29 19:19:38.0
11,11.0,공공시설,마포대교,서울 영등포구 여의도동 85-2,37.5324287051867,126.935734355376,(경관조명 안내) 02-300-8404 (마포대교 안내) 02-2133-1978,,일몰 30분후 점등 ~ 23:00 소등,무료,무료,"<p class=""0"">마포대교는 마포구 용강동과 영등포구 여의도동을 연결하는 한강...","북단) 지하철 5호선 마포역 1,4번출구 도보 15분 / (남단) 지하철 5호선 여...",(북단) 버스정류장 강변한신코아 정류장 하차 후 도보 이용 / (남단) 버스정류장 ...,,2024-06-19 10:12:52.0,2024-12-11 15:28:59.0
12,12.0,공공시설,난지거울분수,서울 마포구 상암동 1536-1,37.5599345342961,126.88981563725,난지안내센터 02-3780-0611,https://hangang.seoul.go.kr/www/facility/map.t...,성수기(7~8월) (매시 정각 20분) 12:00 ~ 21:00(10회) 비수기(4...,무료,무료,"<p class=""0""><span style=""font-size: 14pt;"">난지...","지하철 6호선 마포구청역 7번, 6번 출구 도보 이용",마포구청역 버스정류장 하차 도보 이용,,2024-06-19 11:12:10.0,2024-12-11 15:31:05.0
13,13.0,공공시설,이촌한강공원,서울특별시 용산구 이촌로72길 62,37.517820588578,126.970850893942,02-3780-0551~4,https://hangang.seoul.go.kr/www/contents/660.d...,상시,무료,무료,"<p class=""0"">이촌한강공원은 중랑천교와 원효대교 사이 한강 북단에 위치한 ...","4호선, 경의중앙선 이촌역 4번 출구에서 도보 500m","이촌동한강맨션, 동부이촌동, 한강대교전망카페 등 버스정류장 하차 도보 이용",,2024-06-12 20:35:01.0,2024-12-11 15:31:29.0
14,14.0,공원/광장,남산공원 백범광장- 서울한양도성 성곽,서울 중구 회현동1가 산 1-44,37.5550484830696,126.98043243063,"02-120, 02-3783-5900",https://parks.seoul.go.kr/template/sub/namsan.do,상시개방,무료,무료,"<p class=""0""><span style=""font-size: 14pt;"">남산...",지하철 4호선 명동역 4번 출구 도보 이용,"힐튼호텔, 백범광장(힐튼호텔방면) 정류장 하차 도보 이용",,2024-06-19 10:54:32.0,2024-12-11 15:33:35.0
15,15.0,공원/광장,사육신공원,서울특별시 동작구 노량진로 191,37.5134579901091,126.949411135441,(공원안내) 02-813-2130,,운영 제한 없음,무료,무료,"<p><span style=""font-size: 14pt;"">사육신 공원은 한강대교...",1호선 노량진역 2번 출구 도보 10분/9호선 노들역 1번 출구 도보 10분,버스정류장 사육신공원 정류장 하차 도보 이용,,2024-06-19 11:18:01.0,2024-06-26 15:00:13.0
16,16.0,공공시설,월드컵대교,서울 마포구 상암동 1541,37.5573505544798,126.884431803276,(경관조명 안내) 02-2657-7965 (월드컵대교 안내) 02-2133-1962,,일몰 30분후 점등 ~ 23:00 소등,무료,무료,"<p class=""0""><span style=""font-size: 14pt;"">월드...","(북단) 지하철 6호선 월드컵경기장역 2, 3번 출구로 나와 도보 / (남단) 지하...",(북단) 버스정류장 월드컵공원입구(문화비축기지입구) 정류장 하차 후 도보 / (남단...,,2024-06-19 11:25:10.0,2024-12-11 15:34:28.0
17,18.0,문화/체육,숭례문(남대문),서울특별시 중구 세종대로 40,37.5599277853801,126.975359779271,02-779-8547,https://royal.khs.go.kr/ROYAL/contents/menuInf...,화~일 09:00~18:00 * 매주월요일 정기휴관,무료,,<p>숭례문(崇禮門)은 1398년(태조 7)에 완성한 한양도성의 남대문입니다.</p...,"지하철 1, 2호선 시청역 2번 출구 도보 이용",숭례문 또는 남대문시장 정류장 하차 도보 이용,,2024-06-12 20:41:28.0,2024-06-27 17:32:40.0
18,19.0,문화/체육,서울월드컵경기장,서울특별시 마포구 월드컵로 240,37.5682884450841,126.897273034482,02-2128-2002,https://www.sisul.or.kr/open_content/worldcup/,09시 ~ 18시 * 주말 경기/행사 시 상이,유료,"스타디움 투어 입장료 : 1,000원 * 경기/행사 마다 상이","<p><span style=""font-size: 14pt;"">서울월드컵경기장은 20...",,,,2024-06-26 10:39:27.0,2024-10-31 14:39:37.0
19,20.0,공원/광장,노들섬복합문화공간,서울특별시 용산구 양녕로 445,37.5176638307111,126.958036465507,02-749-4500,https://nodeul.org/,"화~금 10:00~21:00, 주말, 공휴일 10:00~22:00",무료,무료,"<p><span style=""font-size: 14pt;"">한강대교 중간에 위치한...",1호선 용산역 1번 출구 또는 4호선 신용산역 3번출구 근처 버스정류장에서 노들섬 ...,버스정류장 노들섬에서 하차 도보 이용,"유료주차(서측 69대, 동측 21대), 주차 문의 : 02-2105-2415 * ...",2024-06-26 10:56:51.0,2024-07-01 10:50:13.0
20,21.0,공원/광장,광화문광장(광화문),서울특별시 종로구 세종대로 172,37.5716228232824,126.976787992565,02-120,https://gwanghwamun.seoul.go.kr/,연중무휴,무료,무료,"<div><span style=""font-size: 14pt;"">광화문광장은 조선시...",지하철 5호선 광화문역 7번 출구 도보 이용,"세종문화회관, KT광화문지사 정류장 하차 도보 이용",,2024-06-12 20:26:33.0,2024-12-11 15:35:39.0
21,22.0,공원/광장,하늘공원(월드컵공원내),서울특별시 마포구 하늘공원로 95,37.5690794796181,126.886318397942,(공원안내) 02-300-5501 (주차장안내) 02-304-6678,https://parks.seoul.go.kr/template/sub/worldcu...,월별 운영시간 상이 (하단 공원소개 내용 참조),무료,무료,"<div class=""hwp_editor_board_content"" data-hjs...",지하철 6호선 월드컵경기장역 1번 출구에서 도보 2km,난지천공원에서 하늘공원 정상까지 맹꽁이 전기차 탑승,운영시간 09:00 - 22:00 (이후 시간 무료 개방),2024-06-05 00:00:00.0,2024-12-11 15:09:34.0
22,23.0,문화/체육,동대문디자인플라자(DDP),서울특별시 중구 을지로 281,37.56769968798189,127.00984769474137,(종합안내소) 02-2153-0000 (주차장 안내) 02-2153-0141,https://ddp.or.kr/,"10:00 ~ 20:00 (공간별 운영시간 상이, 홈페이지 참조)",무료,,"<p><span style=""font-size: 14pt;"">10주년을 맞은 동대문...","동대문역사문화공원역 1번, 2번 출구","동대문역사문화공원, 동대문디자인플라자 정류장 하차",,2024-06-05 00:00:00.0,2024-06-26 14:25:10.0
23,24.0,문화/체육,경복궁,서울특별시 종로구 사직로 161,37.5759040910202,126.976842133821,02-3700-3900,https://royal.khs.go.kr/gbg,"1월~2월, 11월~12월 09:00~17:00, 3월~5월, 9월~10월 09:0...",유료,"유료 대인 3,000원, 한복착용자 무료",<p>경복궁(景福宮)은 1392년 조선 건국 후</p>\r\n<p>1395년(태조 ...,지하철 3호선 경복궁 5번 출구 도보 이용,경복궁 정류장 하차 도보 이용,,2024-06-12 20:42:52.0,2024-10-31 14:41:14.0
24,25.0,공공시설,서울로미디어캔버스,서울특별시 중구 만리재로 215,37.5566331857979,126.968148438254,02-120,https://www.instagram.com/mediaartseoul,18:00 -23:00,무료,무료,"<p class=""0""><span style=""font-size: 14pt;"">서울...",,,,2024-06-25 14:33:28.0,2024-06-26 17:28:54.0
25,26.0,문화/체육,덕수궁,서울특별시 중구 세종대로 99,37.5656250952955,126.97469099468877,02-771-9951,https://royal.cha.go.kr/ROYAL/contents/menuInf...,09:00~21:00 (입장마감 20:00) * 월요일 휴무,유료,"개인 1,000원, 단체(10인 이상) 800원","<p><span style=""font-size: 14pt;"">덕수궁은 1897년에 ...","지하철 1, 2호선 시청역 2번 출구 도보 이용",시청앞.덕수궁 정거장 하차 도보 이용,,2024-06-05 00:00:00.0,2024-12-11 15:10:27.0
26,27.0,공공시설,반포대교 달빛무지개 분수,서울 서초구 반포동 647,37.5145518124606,126.997949287136,"반포안내센터 02-3780-0541~4, 운영사무실 02-3780-0578",https://hangang.seoul.go.kr/www/contents/856.d...,"성수기(7~8월) 12:00, 19:30, 20:00, 20:30, 21:00, 2...",무료,무료,"<p class=""0""><span style=""font-size: 14pt;"">달빛...","지하철 3, 7, 9호선 고속터미널역 8-1번, 8-2번 출구 도보 이용","반포한강공원, 반포대교남단 한강시민공윈 입구 버스정류장 하차 도보 이용",,2024-06-05 00:00:00.0,2024-12-11 15:11:09.0
27,28.0,공원/광장,서울어린이대공원 팔각당 오름광장,서울특별시 광진구 능동로 216,37.5520117940291,127.078770241307,02-450-9311,https://www.sisul.or.kr/open_content/childrenp...,5:00~22:00 (연중무휴),무료,무료,"<p class=""0""><span lang=""EN-US"">1. </span>서울어린...","5호선 아차산역 4번출구, 7호선 어린이대공원역 1번출구",‘어린이대공원후문아차산역’ 혹은 ‘세종대학교’ 정류소 하차,운영시간 05:00 - 22:00,2024-06-19 10:28:08.0,2024-12-11 15:12:19.0
28,29.0,공공시설,올림픽대교,서울 송파구 신천동 250-1,37.535968547207,127.105516076607,"(경관조명 안내) 02-2040-0367, (올림픽대교 안내) 02-2133-1954",,11~ 4월 : 일몰 30분 후 점등 ~ 23:00 소등 / 5 ~ 10월 : 일몰...,무료,무료,"<p class=""0"">올림픽대교는 광진구 구의동과 송파구 풍납동을 연결하는 한강교...",(북단)강변역 1번출구 도보 21분 / (남단)강동구청역 4번 출구 도보 37분,(북단)버스정류장 프라임아파트앞 정류장 하차 도보 이용 / (남단)버스정류장 풍납토...,,2024-06-19 11:28:50.0,2024-12-11 15:13:25.0
29,30.0,문화/체육,세빛섬,서울특별시 서초구 올림픽대로 2085-14,37.5124362037118,126.995962256954,1566-3433,https://www.somesevit.co.kr/,개별시설별 운영시간 상이,유료,"무료입장 가능, 개별 시설 이용료 별도","<p class=""0"">한강을 아름답게 밝혀줄 세 개의 빛나는 섬<span lang...","지하철 3, 7, 9호선 8-1번 출구 도보 이용",반포대교 남단 정류장 하차 도보 이용,,2024-06-12 20:27:27.0,2024-12-11 15:13:54.0
30,31.0,공원/광장,서울함 공원,서울특별시 마포구 마포나루길 407,37.5557880616618,126.893953718935,02-332-7500,https://www.seoulbattleshippark.com/,"하절기(3월-10월) 평일 10:00~19:00 / 주말,공휴일 10:00~20:0...",유료,"성인 3,000원 / 청소년, 군인 2,000원 / 어린이 1,000원(시설 방문 ...","<p class=""0"">조선시대 한강에는 나루터를 중심으로 상업이 발달하면서 물동량...",6호선 망원역 1번 출구 앞 버스정류장에서 마포09번 버스 탑승 후 '한강공원입구'...,"2, 6호선 합정역 1번 출구 앞 버스정류장에서 마포16번 버스 탑승 후 '망원유수...",운영시간 06:00 ~ 24:00 (유료 운영) 안내 문의처 070-7778-6678,2024-06-12 20:32:31.0,2024-12-11 15:14:34.0
31,32.0,공원/광장,낙산공원 - 한양도성 성곽길,서울특별시 종로구 낙산성곽서길 173,37.579840084989,127.008253028696,"(공원안내) 02-3783-5900, 02-743-7985 (주차안내) 070-89...",https://parks.seoul.go.kr/template/sub/naksan.do,상시개방,무료,무료,"<p class=""0"">서울한양도성은 외적의 침입으로부터 수도 한양을 수호하기 위해...",지하철 4호선 혜화역 2번 출구 도보 10분,"낙산공원(낙산삼거리방면), 혜화역 마로니애공원 정류장 하차 도보 이용","운영시간 상시 (일반 25대, 장애인 1대)",2024-06-19 10:57:56.0,2024-12-11 15:15:53.0
32,33.0,문화/체육,아뜰리에 광화,서울특별시 종로구 세종대로 175,37.5718478584908,126.976168275947,02-120,https://www.instagram.com/atelier_gwanghwa/,일몰후~ 22:00,무료,무료,"<p class=""0""><span style=""font-size: 14pt;"">아뜰...",지하철 5호선 광화문역 7번 출구 도보 이용,"세종문화회관, KT광화문지사 정류장 하차 도보 이용",,2024-06-19 11:01:11.0,2024-12-11 15:16:21.0
33,34.0,공공시설,당산철교,서울 영등포구 여의도동 80-3,37.54021916440686,126.90710358297696,(경관조명 안내) 02-6311-9745 (당산철교 안내) 02-6110-5588,,일몰 30분후 점등 ~ 23:00 소등,무료,,"<p><span style=""font-size: 14pt;"">당산철교는 서울 지하철...","(북단) 지하철 2호선 합정역 7번출구 도보 30분 (남단) 지하철 2호선, 9호...",(북단) 버스정류장 양화진성지 하차 후 도보 이용 (남단) 버스정류장 당산역 정류...,,2024-06-12 20:34:29.0,2024-06-26 14:11:33.0
34,35.0,문화/체육,세종문화회관,서울특별시 종로구 세종대로 175,37.5718478584908,126.976168275947,(안내) 02-399-1000,https://www.sejongpac.or.kr,월별 운영시간 상이,유료,프로그램별 상이,"<p class=""0"">세종문화회관은 서울특별시가 설립한 기관으로 서울의 대표적인 ...","지하철 5호선 광화문역 1번, 8번 출구 도보 3분",버스정류장 세종문화회관 하차 도보 이용,세종로주차장이용,2024-06-19 11:32:51.0,2024-12-11 15:16:51.0
35,36.0,공공시설,한강대교,서울특별시 용산구 이촌로29길 1-11,37.5276608637794,126.962182447512,(경관조명 안내) 02-3284-5436,,일몰 30분후 점등 ~ 23:00 소등,무료,무료,"<p class=""0""><span style=""font-size: 14pt;"">한강...","(북단) 지하철 4호선 신용산역 2,3번출구 도보 15분 / (남단) 지하철 9호선...","(북단) 버스정류장 한강대교북단, LG유플러스 정류장 하차 후 도보 이용 / (남단...",,2024-06-19 11:36:28.0,2024-12-11 15:17:21.0
36,37.0,공공시설,동작대교,서울 용산구 이촌동 385,37.51007066016623,126.98138294783693,(경관조명 안내) 02-3284-5436,,일몰 30분후 점등 ~ 23:00 소등,무료,무료,"<p class=""0""><span style=""font-size: 14pt;""><s...",(북단) 지하철 4호선 이촌역 3-1번출구 도보 20분 / (남단) 지하철 4호선 ...,"(북단) 버스정류장 금강병원, 반도아파트 정류장 하차 후 도보 이용, (남단) 버스...",,2024-06-19 12:34:46.0,2024-12-11 15:17:49.0
37,38.0,공공시설,서울시립미술관 서소문본관,서울특별시 중구 덕수궁길 61,37.5641060692766,126.973699316136,"02-2184-8800, 02-120",https://sema.seoul.go.kr/,"화~금 10:00~20:00 / 토, 일, 공휴일 하절기 10:00~19:00, 동...",무료,무료(특별전 유료),"<p class=""0""><span style=""font-size: 14pt;"">서울...","지하철 1, 2호선 시청역 1번, 10번, 11번, 12번 출구 도보 이용",버스정류장 시청.서소문청사 도보 5분,,2024-06-13 16:41:46.0,2024-12-11 15:32:04.0
38,39.0,공원/광장,서울식물원,서울특별시 강서구 마곡동로 161,37.5722444079878,126.83284283132,02-2104-9716,https://botanicpark.seoul.go.kr/,하절기(3월~10월) : 09:30~18:00(매표마감 17:00) 동절기(11월~...,유료,"주제원 유료 이용, 열린숲&호수원& 습지원 무료 이용","<p class=""0"">서울식물원은 식물원과 공원이 유기적으로 결합된 공원 속 식물...","지하철 9호선 양천향교역 8번출구 도보 10분 / 지하철 9호선, 공항철도 마곡나루...","버스정류장 겸재정원미술관, 마곡나루역 정류장 하차 도보 이용",운영시간 09:00 - 22:00 (이후 시간 무료 개방),2024-06-19 10:07:28.0,2024-12-11 15:32:33.0
39,40.0,가로/마을,덕수궁 돌담길,서울특별시 중구 세종대로 99,37.564976656898445,126.97602682975977,,,연중무휴,유료,,"<p class=""0"">덕수궁 돌담길은 덕수궁 외벽을 이루는 돌담길을 말합니다<sp...","지하철 1, 2호선 시청역 2번출구 도보 5분",버스정류장 시청덕수궁 도보 3분,,2024-06-12 20:42:01.0,2025-03-25 18:07:57.0
40,41.0,문화/체육,광진교 8번가,서울 강동구 천호동 527-2,37.5451462595072,127.112687934633,02-476-0722,https://riverview8.co.kr/rv/html/,"4월~10월(12:00~20:00), 3월,11월(12:00~18:00)",무료,무료,"<p class=""0""><span style=""font-size: 14pt;""><s...","지하철 5호선 광나루역(도보 약 15분), 지하철 5호선 천호역(도보 약 15분)","광나루 한강공원 2주차장(강동구 천호동 483-8), 광나루 한강공원 3주차장(송파...",,2024-06-12 20:47:06.0,2024-12-11 15:25:16.0
41,42.0,문화/체육,고척스카이돔,서울특별시 구로구 경인로 430,37.4982125677913,126.867088741096,1666-3102,https://www.sisul.or.kr/open_content/skydome/,연중,유료,행사 시 관람료(입장료) 발생,"<p class=""0""><span lang=""EN-US"">2015</span>년 개...",지하철 1호선 구일역 2번 출구,"버스정류장 동양미래대학, 구로성심병원 정류장 하차",,2024-06-19 10:22:04.0,2024-12-11 15:29:25.0
42,43.0,공원/광장,서울어린이대공원 후문 선형공원,서울특별시 광진구 능동로 216,37.5520117940291,127.078770241307,02-450-9311,https://www.sisul.or.kr/open_content/childrenp...,05:00~22:00 (연중무휴),무료,무료,"<p class=""0""><span style=""font-size: 14pt;"">서울...",5호선 아차산역 4번출구,‘어린이대공원후문아차산역’ 정류장에 하차,운영시간 05:00 - 22:00,2024-06-19 10:24:53.0,2024-12-11 15:30:08.0
43,44.0,공공시설,뚝섬 음악분수,서울 광진구 자양동 435,37.5278618984384,127.073807096279,"02-3780-0521, 02-3780-0652",https://hangang.seoul.go.kr/www/contents/859....,"성수기(7~8월) (정각 마다 20분) 12:00 ~ 21:00(10회), 비수기(...",무료,무료,"<p class=""0"">뚝섬한강공원에 설치된 음악분수는<span lang=""EN-U...",지하철 7호선 자양역 2번 출구 도보 이용,자양4동주민센터 앞 / 신자초등학교 앞 버스정류장 하차 도보 이용,,2024-06-12 20:45:35.0,2024-12-11 15:19:16.0
44,45.0,공원/광장,석촌호수 루미나리에(송파나루공원),서울 송파구 잠실동 22-6,37.509081251676484,127.10290138635898,,https://www.songpa.go.kr/culture/detailInfo.do...,17:30~22:30 (루미나리에 축제 경관조명 점등 시간),무료,무료,"<p class=""0"">매해 가을과 겨울 석촌호수에서 색다른 빛축제를 만날 수 있습...",지하철 2·8호선 잠실역,,,2024-06-12 20:49:04.0,2024-12-13 09:50:19.0
45,46.0,공공시설,동호대교,서울 성동구 옥수동 86,37.53866839156651,127.01914464062273,02-120,,일몰 30분후 점등 ~ 23:00 소등,무료,무료,"<p class=""0"">동호대교는 성동구 옥수동과 강남구 압구정동을 연결하는 한강교...","(북단) 지하철 3호선 옥수역 3번출구 도보 이용, (남단) 지하철 3호선 압구정역...","(북단) 버스정류장 옥수삼성아파트 정류장 하차 후 도보 이용, (남단) 버스정류장 ...",,2024-06-12 20:37:55.0,2024-12-11 15:27:40.0
46,47.0,공원/광장,선유도공원,서울특별시 영등포구 선유로 343,37.5423832345578,126.901819342041,02-2631-9368,https://parks.seoul.go.kr/template/sub/seonyud...,06:00 - 24:00,무료,무료,"<p class=""0""><span lang=""EN-US"">&ldquo;</span>...","선유도역 - 9호선 (도보 약 10분) / 당산역 - 2호선, 9호선 (도보 약 15분)","선유도 정류장 하차 도보 이용 * 장애인주차만 가능, 일반차량의 경우 양화한강공원...",,2024-06-12 20:39:08.0,2024-12-11 15:28:06.0
47,48.0,문화/체육,송파책박물관,서울특별시 송파구 송파대로37길 77,37.4988841772964,127.104383431798,02-2147-2486,https://www.bookmuseum.go.kr/,"10:00 ~ 18:00 화, 수, 목, 금, 토, 일요일(입장마감 : 폐관 30분...",무료,무료,"<p class=""0"">송파책박물관은 전국 최초 공립 책 박물관입니다<span la...",지하철 8호선 송파역 4번출구 도보 15분,송파책박물관 헬리오시티 정류장 하차 도보 이용,"24시간 (최초 30분 무료, 무료시간 경과 후 5분당 150원)",2024-06-12 20:40:51.0,2024-12-11 15:28:35.0
48,49.0,공원/광장,노원불빛정원(화랑대철도공원 내),서울특별시 노원구 화랑로 608,37.6244509765399,127.093089721731,02-2116-0552,https://www.nowon.kr/www/info/info1/info1_06/i...,"화~일요일, 일몰전 30분~22:00 ※ 월요일 휴무",무료,"무료 ※ 단, 화랑대철도공원 내 일부 문화시설(기차마을 등) 입장료 있음","<p class=""0""><span style=""font-size: 14pt;"">○ ...",6호선 화랑대역 4번출구 하차 후 도보 10분 (약 898m),"‘경춘선숲길.화랑대역공원’ 버스정류장 하차 (간선버스 202 / 지선버스 1155,...",,2024-06-19 11:06:28.0,2024-12-11 15:30:36.0
49,50.0,공원/광장,서울어린이대공원 음악분수,서울특별시 광진구 능동로 216,37.5520117940291,127.078770241307,02-450-9311,https://www.sisul.or.kr/open_content/childrenp...,5:00~22:00 (연중무휴),무료,무료,"<p class=""0"">서울어린이대공원의 대표 핫플레이스인 음악분수<span lan...",7호선 어린이대공원역 1번출구,‘세종대학교’ 정류소 하차,운영시간 05:00-22:00,2024-06-19 10:47:20.0,2024-12-11 15:33:07.0
50,51.0,공공시설,성산대교,서울 마포구 망원동 306-53,37.5514767278681,126.891604816192,(경관조명 안내) 02-2657-7965 (성산대교 안내) 02-2133-1943,,일몰 30분후 점등 ~ 23:00 소등,무료,무료,"<p class=""0""><span style=""font-size: 14pt;"">성산...",(북단) 지하철 6호선 마포구청역 6번 출구로 나와 도보 / (남단) 지하철 9호선...,(북단) 버스정류장 마포구청역 하차 후 도보 / (남단) 버스정류장 양평동한솔아파트...,,2024-06-19 11:20:42.0,2024-12-11 15:34:03.0

In [34]:
import folium

map = folium.Map(location=[37.450086, 127.167980],
                 zoom_start=11,
                 tiles='cartodbpositron')


for index, row in uni.iterrows():
    title = row['TITLE']
    lat = row['LA']
    lon = row['LO']


    folium.Marker(
        location=[lat, lon],
        popup=title,
        tooltip=title
    ).add_to(map)

map